Repository argotorg/solidity, pull requests merged in 2018-10, with the labels that each got.

#5114 Improve the create2 description in assembly.rst (and include in yul.rst)
  docs/assembly.rst
  docs/yul.rst
Labels: documentation :book:

#5084 [DOCS] Update contributing.
  docs/contributing.rst
Labels: documentation :book:

#5073 separate out a new "Design Criteria" section from "Formal Specification"
  docs/abi-spec.rst
Labels: documentation :book:, external contribution :star:

#5044 [DOCS] Update assembly.
  docs/assembly.rst
Labels: documentation :book:

#4952 Clarifying docs on event storage
  docs/abi-spec.rst
  docs/contracts.rst
Labels: documentation :book:

#3834 [DOCS] Update storage layout
  docs/miscellaneous.rst
Labels: documentation :book:

#5014 Improve error message for lookup in function types
  Changelog.md
  libsolidity/analysis/TypeChecker.cpp
  test/libsolidity/syntaxTests/nameAndTypeResolution/575_member_member_getter_call_without_parentheses.sol
  test/libsolidity/syntaxTests/nameAndTypeResolution/576_member_getter_call_without_parentheses.sol
  test/libsolidity/syntaxTests/nameAndTypeResolution/577_member_getter_call_without_parentheses_missing_function.sol
  test/libsolidity/syntaxTests/nameAndTypeResolution/578_private_member_getter_call_without_parentheses.sol
  test/libsolidity/syntaxTests/nameAndTypeResolution/579_member_getter_call_without_parentheses_private_function.sol
Labels: external contribution :star:

#4843 Link and clarify ABI type
  docs/types.rst
Labels: documentation :book:

#3047 Add strict encoding mode to the ABI spec
  docs/abi-spec.rst
Labels: documentation :book:
