Repository argotorg/solidity, pull requests merged in 2018-05, with the labels that each got.

#3386 Fixed typos in abi-spec documentation
  docs/abi-spec.rst
Labels: documentation

#3256 Full inliner
  libjulia/optimiser/FullInliner.cpp
  libjulia/optimiser/FullInliner.h
  libjulia/optimiser/NameCollector.cpp
  libjulia/optimiser/NameCollector.h
  libjulia/optimiser/NameDispenser.cpp
  libjulia/optimiser/NameDispenser.h
  test/libjulia/Inliner.cpp
Labels: in progress

#3473 Introduce Julia filter to encapsulate top level Block as a FunctionDefinition
  libjulia/optimiser/MainFunction.cpp
  libjulia/optimiser/MainFunction.h
  libjulia/optimiser/README.md
  test/libjulia/MainFunction.cpp
Labels: in progress

#3238 Add logic builtins to Julia and update type conversion prototypes
  docs/julia.rst
Labels: documentation, in progress
