Repository argotorg/solidity, pull requests merged in 2018-12, with the labels that each got.

#5437 DOCS: Move String literal and inline array FAQ items
  docs/frequently-asked-questions.rst
  docs/types.rst
Labels: documentation :book:

#5476 add a 'readable' format for large hex values
  libdevcore/CommonData.h
  libdevcore/StringUtils.h
  libsolidity/formal/SMTChecker.cpp
  test/libdevcore/CommonData.cpp
  test/libdevcore/StringUtils.cpp
  test/libsolidity/smtCheckerTests/loops/do_while_1_fail.sol
  test/libsolidity/smtCheckerTests/loops/do_while_1_false_positives.sol
  test/libsolidity/smtCheckerTests/loops/for_1_fail.sol
  test/libsolidity/smtCheckerTests/loops/for_1_false_positive.sol
  test/libsolidity/smtCheckerTests/overflow/simple_overflow.sol
  test/libsolidity/smtCheckerTests/special/many.sol
Labels: external contribution :star:

#5008 Reuse stack slots in Yul codegen
  libsolidity/codegen/AsmCodeGen.cpp
  libsolidity/codegen/AsmCodeGen.h
  libsolidity/interface/AssemblyStack.cpp
  libsolidity/interface/AssemblyStack.h
  libyul/Exceptions.h
  libyul/backends/evm/EVMCodeTransform.cpp
  libyul/backends/evm/EVMCodeTransform.h
  libyul/backends/evm/EVMObjectCompiler.cpp
  libyul/backends/evm/EVMObjectCompiler.h
  libyul/optimiser/ASTWalker.cpp
  libyul/optimiser/ASTWalker.h
  test/libyul/StackReuseCodegen.cpp
Labels: external contribution :star:

#5552 Fix conversions from rational number literals to fixed-point types.
  libsolidity/analysis/TypeChecker.cpp
  libsolidity/ast/Types.cpp
  test/libsolidity/syntaxTests/nameAndTypeResolution/313_fixed_type_size_capabilities.sol
  test/libsolidity/syntaxTests/types/rational_number_literal_to_fixed_implicit.sol
  test/libsolidity/syntaxTests/types/too_small_negative_numbers.sol
Labels: external contribution :star:

#2271 Add NatSpec to Style-Guide
  docs/layout-of-source-files.rst
  docs/style-guide.rst
Labels: documentation :book:, external contribution :star:

#4859 Create section that covers input and output function types
  docs/types.rst
Labels: documentation :book:

#5246 Updates arrays section to improve order and clarify concepts
  docs/types.rst
Labels: documentation :book:

#5683 5673 doc enum fix
  docs/contracts.rst
Labels: documentation :book:, external contribution :star:
