Repository argotorg/solidity, pull requests merged in 2018-07, with the labels that each got.

#4470 Visual Studio 2017 build-time (linking) fix and improvements
  .gitignore
  cmake/EthCompilerSettings.cmake
  cmake/jsoncpp.cmake
Labels: build-system

#4505 Update docs allowed mapping key values
  docs/types.rst
Labels: bug :bug:, documentation

#4463 isoltest: adds support for properly handling ANSI escape sequences on Windows
  test/tools/isoltest.cpp
Labels: enhancement

#4533 Fix typo
  docs/frequently-asked-questions.rst
Labels: documentation

#4520 Move note on decompiling
  docs/frequently-asked-questions.rst
  docs/index.rst
Labels: documentation, in progress

#4594 Fixes building Solidity when base directory contains spaces.
  cmake/EthBuildInfo.cmake
Labels: build-system

#4619 Clarify what ‘memory type’ is
  docs/contracts.rst
  docs/types.rst
Labels: documentation
