Repository argotorg/solidity, pull requests merged in 2018-08, with the labels that each got.

#4526 Clarify truncation with addresses
  docs/types.rst
Labels: documentation :book:

#4616 Add interface generator to tools section
  docs/index.rst
Labels: documentation :book:

#4595 fixes tests.sh to not use hard-coded working dir and adds proper cleanup
  scripts/tests.sh
Labels: build system :building_construction:

#4498 Move intro related FAQ points
  docs/frequently-asked-questions.rst
  docs/introduction-to-smart-contracts.rst
Labels: documentation :book:

#3496 Update Style Guide examples to comply with CapWords requirement for contract and file naming
  docs/style-guide.rst
Labels: documentation :book:

#4703 solc: Fixes double-quoting path names on stderr.
  solc/CommandLineInterface.cpp
  test/cmdlineTests.sh
Labels: bug :bug:

#4753 Replace boost:lexical_cast<std::string> for std::to_string.
  libdevcore/Exceptions.cpp
  libjulia/backends/evm/EVMCodeTransform.cpp
  libjulia/optimiser/NameDispenser.cpp
  liblll/Parser.cpp
  libsolidity/ast/ASTJsonConverter.cpp
  libsolidity/ast/Types.cpp
  libsolidity/codegen/ContractCompiler.cpp
  libsolidity/inlineasm/AsmAnalysis.cpp
  libsolidity/inlineasm/AsmParser.cpp
  libsolidity/interface/CompilerStack.cpp
  libsolidity/interface/Exceptions.h
  test/libevmasm/Optimiser.cpp
  test/liblll/Compiler.cpp
  test/libsolidity/SolidityOptimizer.cpp
Labels: external contribution :star:

#4665 cmake option added to make solvers optional
  cmake/EthCompilerSettings.cmake
  cmake/FindCVC4.cmake
  cmake/FindZ3.cmake
  docs/installing-solidity.rst
  libsolidity/CMakeLists.txt
Labels: external contribution :star:

#4684 [BREAKING] Underscores in numeric literals
  .gitignore
  Changelog.md
  docs/types.rst
  libsolidity/analysis/SyntaxChecker.cpp
  libsolidity/analysis/SyntaxChecker.h
  libsolidity/ast/Types.cpp
  libsolidity/parsing/Scanner.cpp
  test/libsolidity/SolidityEndToEndTest.cpp
  test/libsolidity/SolidityScanner.cpp
  test/libsolidity/syntaxTests/parsing/lexer_numbers_with_underscores_decimal.sol
  test/libsolidity/syntaxTests/parsing/lexer_numbers_with_underscores_decimal_fail.sol
  test/libsolidity/syntaxTests/parsing/lexer_numbers_with_underscores_fixed.sol
  test/libsolidity/syntaxTests/parsing/lexer_numbers_with_underscores_fixed_fail.sol
  test/libsolidity/syntaxTests/parsing/lexer_numbers_with_underscores_hex.sol
  test/libsolidity/syntaxTests/parsing/lexer_numbers_with_underscores_hex_fail.sol
Labels: feature

#4618 Add contract type to types documentation
  docs/types.rst
Labels: documentation :book:

#4796 [BREAKING] Adds support for structs in interfaces.
  Changelog.md
  libsolidity/analysis/TypeChecker.cpp
  libsolidity/analysis/TypeChecker.h
  test/libsolidity/SolidityEndToEndTest.cpp
  test/libsolidity/syntaxTests/nameAndTypeResolution/419_interface_structs.sol
Labels: feature

#4372 Add implicit convertibility to function pointer with higher state mutability
  docs/types.rst
  libsolidity/ast/Types.cpp
  libsolidity/ast/Types.h
  test/libsolidity/syntaxTests/types/function_types/function_parameter_return_types_fail.sol
  test/libsolidity/syntaxTests/types/function_types/function_parameter_return_types_success.sol
  test/libsolidity/syntaxTests/types/function_types/function_state_mutability_fail.sol
  test/libsolidity/syntaxTests/types/function_types/function_state_mutability_success.sol
Labels: external contribution :star:

#4765 [WIP] Fixes issue where computing storage size for a number would take too long (or even cause a crash).
  Changelog.md
  libsolidity/ast/Types.cpp
  libsolidity/ast/Types.h
  test/libsolidity/syntaxTests/types/too_small_negative_numbers.sol
Labels: bug :bug:

#4542 Fix: natspec annotations on constructors
  libsolidity/analysis/DocStringAnalyser.cpp
  libsolidity/analysis/DocStringAnalyser.h
  libsolidity/interface/Natspec.cpp
  libsolidity/interface/Natspec.h
  test/libsolidity/SolidityNatspecJSON.cpp
Labels: external contribution :star:

#4797 Fixes #4718: High CPU usage when using large variable names
  Changelog.md
  libdevcore/StringUtils.cpp
  libdevcore/StringUtils.h
  libsolidity/analysis/DeclarationContainer.cpp
  test/libdevcore/StringUtils.cpp
  test/libsolidity/syntaxTests/nameAndTypeResolution/573_similar_name_longer_than_80_not_suggested.sol
  test/libsolidity/syntaxTests/nameAndTypeResolution/574_similar_name_shorter_than_80_suggested.sol
Labels: external contribution :star:

#4496 Move contract related FAQ points
  docs/contracts.rst
  docs/frequently-asked-questions.rst
Labels: documentation :book:
