Repository argotorg/solidity, pull requests merged in 2018-02, with the labels that each got.

#3484 Fix segfault with undeclared array types
  libsolidity/analysis/ReferencesResolver.cpp
  test/libsolidity/SolidityNameAndTypeResolution.cpp
Labels: needs review

#3478 Format number nicely in the IULIA simplifier.
  libdevcore/CommonData.h
  libjulia/optimiser/SimplificationRules.cpp
Labels: in progress

#3489 Fix some weird zeppelin tests.
  test/externalTests.sh
Labels: in progress, nextrelease

#3477 Disable greedy exception catcher in Emscripten build
  cmake/EthCompilerSettings.cmake
Labels: in progress, nextrelease

#3374 Replace MOD with AND if constant is power of 2
  libevmasm/RuleList.h
  test/libjulia/Simplifier.cpp
Labels: in progress, nextrelease

#2818 Also test gnosis contracts.
  .travis.yml
  circle.yml
  test/externalTests.sh
Labels: in progress

#3425 Deprecate the var keyword in SyntaxChecker
  Changelog.md
  libsolidity/analysis/SyntaxChecker.cpp
  libsolidity/analysis/SyntaxChecker.h
  test/libsolidity/SolidityNameAndTypeResolution.cpp
  test/libsolidity/ViewPureChecker.cpp
Labels: needs review, nextrelease

#3497 Mention mod-and-replacement in changelog.
  Changelog.md
Labels: in progress

#3398 Allow lllc to be installed via Make
  CMakeLists.txt
  lllc/CMakeLists.txt
  scripts/release_ppa.sh
Labels: needs review, nextrelease

#3349 Avoid output messages size blow-up using huge bignums literals
  Changelog.md
  libsolidity/ast/Types.cpp
  libsolidity/ast/Types.h
  test/libsolidity/SolidityNameAndTypeResolution.cpp
Labels: needs review, nextrelease

#3147 Suggest alternatives when identifier not found. Closes #3058.
  Changelog.md
  libdevcore/StringUtils.cpp
  libdevcore/StringUtils.h
  libsolidity/analysis/DeclarationContainer.cpp
  libsolidity/analysis/DeclarationContainer.h
  libsolidity/analysis/NameAndTypeResolver.cpp
  libsolidity/analysis/NameAndTypeResolver.h
  libsolidity/analysis/ReferencesResolver.cpp
  test/libdevcore/StringUtils.cpp
  test/libsolidity/SolidityNameAndTypeResolution.cpp
Labels: nextrelease

#3498 Allow `this.f.selector` to be pure.
  Changelog.md
  libsolidity/analysis/ViewPureChecker.cpp
  libsolidity/analysis/ViewPureChecker.h
  libsolidity/codegen/ExpressionCompiler.cpp
  test/libsolidity/SolidityEndToEndTest.cpp
  test/libsolidity/SolidityNameAndTypeResolution.cpp
  test/libsolidity/ViewPureChecker.cpp
Labels: in progress, nextrelease

#3501 Prepare 0.4.20 release.
  Changelog.md
  docs/bugs_by_version.json
Labels: in progress

#3521 Disallow uninitialized storage pointers as experimental 0.5.0 feature.
  Changelog.md
  libsolidity/analysis/TypeChecker.cpp
  test/libsolidity/SolidityNameAndTypeResolution.cpp
Labels: nextrelease

#3502 Minor improvement: Check sources
  Changelog.md
  libsolidity/interface/StandardCompiler.cpp
  test/libsolidity/StandardCompiler.cpp
Labels: needs review, nextrelease

#3182 Update introduction-to-smart-contracts.rst
  docs/introduction-to-smart-contracts.rst
Labels: documentation

#3135 Convert static SourceReferenceFormatter functions to member ones
  libsolidity/interface/SourceReferenceFormatter.cpp
  libsolidity/interface/SourceReferenceFormatter.h
  solc/CommandLineInterface.cpp
  test/libjulia/Common.cpp
  test/libsolidity/GasMeter.cpp
  test/libsolidity/SolidityExecutionFramework.h
Labels: nextrelease

#3448 Clarify name documentation for mixedCase
  docs/style-guide.rst
Labels: documentation, in progress

#3357 docs: Improve assembly grammar definition
  docs/assembly.rst
Labels: documentation, needs review

#3532 libdevcore/JSON.h - new API
  Changelog.md
  libdevcore/CMakeLists.txt
  libdevcore/JSON.cpp
  libdevcore/JSON.h
  libsolc/libsolc.cpp
  libsolidity/interface/StandardCompiler.cpp
  test/Metadata.cpp
  test/RPCSession.cpp
  test/fuzzer.cpp
  test/libdevcore/JSON.cpp
  test/libsolidity/JSONCompiler.cpp
  test/libsolidity/Metadata.cpp
  test/libsolidity/SolidityABIJSON.cpp
  test/libsolidity/SolidityNatspecJSON.cpp
  test/libsolidity/StandardCompiler.cpp
Labels: nextrelease

#3427 Abstract Contracts: Add note about function type
  docs/contracts.rst
Labels: documentation, needs review

#3513 Add "Maximum Line Length" section
  docs/style-guide.rst
Labels: documentation

#3499 Run EndToEnd tests on circle, too.
  circle.yml
  scripts/tests.sh
Labels: in progress

#3426 Note deprecation of constant keyword on functions
  docs/contracts.rst
Labels: documentation, needs review

#3335 Fixes the errors in the sample ballot contract
  docs/solidity-by-example.rst
Labels: documentation, in progress

#3603 Fix links and clarify the solc-js section
  docs/installing-solidity.rst
  docs/using-the-compiler.rst
Labels: documentation

#3604 Introduce VM version ('hard fork') column for assembly opcodes
  docs/assembly.rst
  docs/julia.rst
Labels: documentation

#3476 C99/C++ scoping rules
  Changelog.md
  docs/control-structures.rst
  libsolidity/analysis/DeclarationContainer.cpp
  libsolidity/analysis/DeclarationContainer.h
  libsolidity/analysis/NameAndTypeResolver.cpp
  libsolidity/analysis/NameAndTypeResolver.h
  libsolidity/analysis/ReferencesResolver.cpp
  libsolidity/analysis/ReferencesResolver.h
  libsolidity/ast/AST.cpp
  libsolidity/ast/AST.h
  test/libsolidity/SMTChecker.cpp
  test/libsolidity/SolidityEndToEndTest.cpp
  test/libsolidity/SolidityExpressionCompiler.cpp
  test/libsolidity/SolidityNameAndTypeResolution.cpp
Labels: in progress
