Repository argotorg/solidity, pull requests merged in 2018-03, with the labels that each got.

#3406 SMTChecker: A little refactoring on SSA vars (preparation for Bool)
  libsolidity/formal/SMTChecker.cpp
  libsolidity/formal/SMTChecker.h
  libsolidity/formal/SSAVariable.cpp
  libsolidity/formal/SSAVariable.h
  libsolidity/formal/SymbolicIntVariable.cpp
  libsolidity/formal/SymbolicIntVariable.h
  libsolidity/formal/SymbolicVariable.cpp
  libsolidity/formal/SymbolicVariable.h
Labels: needs review

#3365 Documentation updates for internal constructors and function signature
  docs/abi-spec.rst
  docs/contracts.rst
Labels: documentation, needs review

#2966 Use STATICCALL for pure function calls.
  Changelog.md
  docs/contracts.rst
  libsolidity/ast/ExperimentalFeatures.h
  libsolidity/codegen/ExpressionCompiler.cpp
  test/libsolidity/SolidityEndToEndTest.cpp
Labels: nextrelease

#3308 Use returndatacopy for retrieving dynamically sized outputs.
  Changelog.md
  libsolidity/analysis/TypeChecker.cpp
  libsolidity/ast/Types.cpp
  libsolidity/ast/Types.h
  libsolidity/codegen/ABIFunctions.cpp
  libsolidity/codegen/CompilerUtils.cpp
  libsolidity/codegen/CompilerUtils.h
  libsolidity/codegen/ContractCompiler.cpp
  libsolidity/codegen/ContractCompiler.h
  libsolidity/codegen/ExpressionCompiler.cpp
  test/libsolidity/ABIDecoderTests.cpp
  test/libsolidity/SolidityNameAndTypeResolution.cpp
Labels: in progress, nextrelease
