Repository argotorg/solidity, pull requests merged in 2018-11, with the labels that each got.

#4860 Add mention of common subexpression elimination
  docs/miscellaneous.rst
Labels: documentation :book:

#4497 Move control structure related FAQ points
  docs/control-structures.rst
  docs/frequently-asked-questions.rst
Labels: documentation :book:

#5070 Docs: Clarify creating a contract example code
  docs/contracts.rst
Labels: documentation :book:

#5324 Change terminology used for input output parameters pt 2
  docs/layout-of-source-files.rst
  docs/types.rst
  docs/units-and-global-variables.rst
Labels: documentation :book:

#5323 Change terminology used for input output parameters
  docs/control-structures.rst
Labels: documentation :book:

#4523 Micropayment channel example polish
  docs/solidity-by-example.rst
Labels: documentation :book:

#5444 Removing redundant virtual from override function declaration
  libevmasm/ConstantOptimiser.h
  libsolidity/analysis/ControlFlowAnalyzer.h
  libsolidity/analysis/ControlFlowBuilder.h
  libsolidity/analysis/ControlFlowGraph.h
  libsolidity/analysis/DocStringAnalyser.h
  libsolidity/analysis/PostTypeChecker.h
  libsolidity/analysis/ReferencesResolver.h
  libsolidity/analysis/StaticAnalyzer.h
  libsolidity/analysis/SyntaxChecker.h
  libsolidity/analysis/TypeChecker.h
  libsolidity/analysis/ViewPureChecker.h
  libsolidity/ast/AST.h
  libsolidity/ast/ASTVisitor.h
  libsolidity/ast/Types.h
  libsolidity/codegen/ContractCompiler.h
  libsolidity/codegen/ExpressionCompiler.h
  libsolidity/codegen/LValue.h
  libsolidity/formal/SMTChecker.h
  libyul/backends/evm/EVMAssembly.h
  libyul/optimiser/ASTCopier.h
  libyul/optimiser/CommonSubexpressionEliminator.h
  libyul/optimiser/DataFlowAnalyzer.h
  libyul/optimiser/Disambiguator.h
  libyul/optimiser/ExpressionInliner.h
  libyul/optimiser/ExpressionSplitter.h
  libyul/optimiser/FullInliner.h
  libyul/optimiser/InlinableExpressionFunctionFinder.h
  libyul/optimiser/Metrics.h
  libyul/optimiser/NameCollector.h
  libyul/optimiser/Rematerialiser.h
  libyul/optimiser/SSAValueTracker.h
  libyul/optimiser/Semantics.h
  libyul/optimiser/Substitution.h
  libyul/optimiser/UnusedPruner.h
  test/libsolidity/ASTJSONTest.h
  test/libsolidity/SyntaxTest.h
Labels: external contribution :star:

#5434 Qualify that storage slots are shared for contiguous data
  docs/miscellaneous.rst
Labels: documentation :book:, external contribution :star:

#5328 Added Superblocks Lab IDE to the generic doc section
  docs/resources.rst
Labels: documentation :book:, external contribution :star:

#4958 error out if no output artifacts are requested.
  solc/CommandLineInterface.cpp
Labels: external contribution :star:

#5435 Define how inheritance affects storage
  docs/miscellaneous.rst
Labels: documentation :book:, external contribution :star:

#5438 DOCS: Move undefined FAQ item
  docs/frequently-asked-questions.rst
  docs/types.rst
Labels: documentation :book:

#5287 DOCS: Merge FAQ into docs on multi-dimensional arrays
  docs/control-structures.rst
  docs/frequently-asked-questions.rst
Labels: documentation :book:

#5313 Add error reporting script and use in check_style script
  scripts/check_style.sh
  scripts/report_errors.sh
Labels: external contribution :star:

#5121 Review contributing docs for language and ease, tests sections
  docs/contributing.rst
Labels: documentation :book:

#5277 DOCS: Add mention that pure functions can require and revert
  docs/contracts.rst
Labels: documentation :book:

#5289 DOCS: Updates to docs index file
  docs/index.rst
Labels: documentation :book:
