Repository argotorg/solidity, pull requests merged in 2018-09, with the labels that each got.

#4578 Update README.md
  README.md
Labels: external contribution :star:

#5010 fix code format problems
  liblll/Compiler.cpp
  liblll/Parser.cpp
  libsolidity/interface/Natspec.cpp
  libsolidity/interface/SourceReferenceFormatter.cpp
  solc/CommandLineInterface.cpp
Labels: external contribution :star:

#5004 Note how Solidity types map to ABI types
  docs/abi-spec.rst
Labels: documentation :book:

#5019 Extend section on addresses.
  docs/types.rst
Labels: documentation :book:

#4907 Blockchain basics part 1
  docs/introduction-to-smart-contracts.rst
Labels: documentation :book:

#5011 Disallow uppercase X in hex number literals
  Changelog.md
  docs/grammar.txt
  libsolidity/parsing/Scanner.cpp
  test/libsolidity/SolidityScanner.cpp
Labels: external contribution :star:

#5024 Add struct->tuple to the Solidity->ABI types table
  docs/abi-spec.rst
Labels: documentation :book:

#5021 More types.
  docs/types.rst
Labels: documentation :book:

#4865 Document array length changing behaviors
  docs/types.rst
Labels: documentation :book:, external contribution :star:

#5025 [DOCS] Update reference types.
  docs/types.rst
Labels: documentation :book:

#5003 Add syntax tests to fix #4627
  test/libsolidity/syntaxTests/multiline_comments.sol
  test/libsolidity/syntaxTests/string/string_escapes.sol
  test/libsolidity/syntaxTests/string/string_new_line.sol
  test/libsolidity/syntaxTests/string/string_terminated_by_backslash.sol
  test/libsolidity/syntaxTests/string/string_unterminated.sol
  test/libsolidity/syntaxTests/string/string_unterminated_no_new_line.sol
  test/libsolidity/syntaxTests/unicode_escape_literals.sol
  test/libsolidity/syntaxTests/unterminatedBlocks/one_dot.sol
  test/libsolidity/syntaxTests/unterminatedBlocks/one_dot_x.sol
  test/libsolidity/syntaxTests/unterminatedBlocks/zero_dot.sol
  test/libsolidity/syntaxTests/unterminatedBlocks/zero_dot_x.sol
  test/libsolidity/syntaxTests/upper_case_hex_literals.sol
Labels: external contribution :star:

#4925 Clarify docs around reserved memory byte ranges
  docs/miscellaneous.rst
Labels: documentation :book:, external contribution :star:

#5022 [DOCS] Last part of value types.
  docs/types.rst
Labels: documentation :book:

#5091 Fix the HelloWorld example in the readme
  README.md
Labels: documentation :book:

#4995 Docs: Add content from old Solidity wiki
  docs/index.rst
  docs/introduction-to-smart-contracts.rst
Labels: documentation :book:

#5006 Document modulo semantics
  docs/types.rst
Labels: documentation :book:

#5100 Rename remainder to modulo and update fixed point documentation
  docs/types.rst
Labels: documentation :book:

#5080 [DOCS] Update metadata.
  docs/metadata.rst
Labels: documentation :book:

#5085 [DOCS] Update FAQ
  docs/frequently-asked-questions.rst
Labels: documentation :book:

#5101 Return note taken from metadata and reorder
  docs/metadata.rst
Labels: documentation :book:

#5087 [DOCS] Semantics of negation.
  docs/types.rst
Labels: documentation :book:

#5032 [DOCS] More on reference types.
  docs/types.rst
Labels: documentation :book:
