Repository argotorg/solidity, pull requests merged in 2021-12, with the labels that each got.

#12348 Fix cl test script on macOS
  test/cmdlineTests.sh
Labels: external contribution :star:

#12322 Fix ExpressionSplitter example
  docs/internals/optimizer.rst
Labels: external contribution :star:

#12366 Fix several three consecutive backquotes in document
  docs/cheatsheet.rst
  docs/units-and-global-variables.rst
  docs/yul.rst
Labels: external contribution :star:

#11800 Separate control flow from error reporting in command line parser
  libsolutil/Exceptions.h
  solc/CMakeLists.txt
  solc/CommandLineInterface.cpp
  solc/CommandLineInterface.h
  solc/CommandLineParser.cpp
  solc/CommandLineParser.h
  solc/Exceptions.h
  solc/main.cpp
  test/solc/CommandLineInterface.cpp
  test/solc/CommandLineInterfaceAllowPaths.cpp
  test/solc/CommandLineParser.cpp
  test/solc/Common.cpp
  test/solc/Common.h
Labels: external contribution :star:

#12389 Remove redundant typo
  docs/brand-guide.rst
Labels: documentation :book:, external contribution :star:

#12380 External tests with native compiler binary
  .circleci/config.yml
  test/externalTests.sh
  test/externalTests/colony.sh
  test/externalTests/common.sh
  test/externalTests/ens.sh
  test/externalTests/gnosis-v2.sh
  test/externalTests/gnosis.sh
  test/externalTests/solc-js/solc-js.sh
  test/externalTests/zeppelin.sh
Labels: testing :hammer:

#12390 [Docs] Replaced dead link for Alarm Clock
  docs/introduction-to-smart-contracts.rst
Labels: documentation :book:, external contribution :star:

#12392 Fix `t_ems_test_ext_colony` nightly job
  .circleci/config.yml
Labels: testing :hammer:

#12387 [CI] Adjust job parallelism to actually match available resources
  .circleci/config.yml
  .circleci/soltest_all.sh
Labels: testing :hammer:

#12394 Make optimizer level 2 in external tests actually different from level 3
  test/externalTests/colony.sh
  test/externalTests/common.sh
  test/externalTests/ens.sh
  test/externalTests/gnosis-v2.sh
  test/externalTests/gnosis.sh
Labels: testing :hammer:

#12393 Avoid double compilation in Colony external test
  test/externalTests/colony.sh
Labels: testing :hammer:

#12381 Improve description of break/continue restrictions.
  docs/yul.rst
Labels: documentation :book:, external contribution :star:

#12370 Removed the initiation of default outputs in assembler mode
  Changelog.md
  scripts/common_cmdline.sh
  solc/CommandLineInterface.cpp
  solc/CommandLineParser.cpp
  test/cmdlineTests.sh
  test/cmdlineTests/evm_to_wasm/args
  test/cmdlineTests/evm_to_wasm_break/args
  test/cmdlineTests/linking_strict_assembly/args
  test/cmdlineTests/linking_strict_assembly/output
  test/cmdlineTests/linking_strict_assembly_qualified_library_qualified_reference/args
  test/cmdlineTests/linking_strict_assembly_qualified_library_qualified_reference/output
  test/cmdlineTests/linking_strict_assembly_qualified_library_unqualified_reference/args
  test/cmdlineTests/linking_strict_assembly_qualified_library_unqualified_reference/output
  test/cmdlineTests/linking_strict_assembly_same_library_name_different_files/args
  test/cmdlineTests/linking_strict_assembly_same_library_name_different_files/output
  test/cmdlineTests/linking_strict_assembly_same_library_name_different_files_in_link_references/args
  test/cmdlineTests/linking_strict_assembly_same_library_name_different_files_in_link_references/output
  test/cmdlineTests/linking_strict_assembly_unqualified_library_qualified_reference/args
  test/cmdlineTests/linking_strict_assembly_unqualified_library_qualified_reference/output
  test/cmdlineTests/linking_strict_assembly_unqualified_library_unqualified_reference/args
  test/cmdlineTests/linking_strict_assembly_unqualified_library_unqualified_reference/output
  test/cmdlineTests/linking_strict_assembly_unresolved_references/args
  test/cmdlineTests/linking_strict_assembly_unresolved_references/output
  test/cmdlineTests/object_compiler/args
  test/cmdlineTests/strict_asm_debug_info_print_all/args
  test/cmdlineTests/strict_asm_debug_info_print_location_only/args
  test/cmdlineTests/strict_asm_debug_info_print_none/args
  test/cmdlineTests/strict_asm_optimizer_steps/args
  test/cmdlineTests/strict_asm_optimizer_steps/output
  test/cmdlineTests/wasm_to_wasm_function_returning_multiple_values/args
  test/cmdlineTests/wasm_to_wasm_memory_instructions_alignment/args
  test/cmdlineTests/yul_function_name_clashes/args
  test/cmdlineTests/yul_function_name_clashes_different_params/args
  test/cmdlineTests/yul_optimize_runs/args
  test/cmdlineTests/yul_verbatim/args
  test/cmdlineTests/yul_verbatim_msize/args
Labels: breaking change :warning:, external contribution :star:

#12373 Explanation about operators.
  docs/types/operators.rst
Labels: documentation :book:

#12289 trial test cases extracted from SolidityEndToEndTest.cpp into .sol files
  test/libsolidity/SolidityEndToEndTest.cpp
  test/libsolidity/semanticTests/array/copying/copying_bytes_multiassign.sol
  test/libsolidity/semanticTests/calldata/copy_from_calldata_removes_bytes_data.sol
  test/libsolidity/semanticTests/enums/enum_referencing.sol
  test/libsolidity/semanticTests/fallback/call_forward_bytes.sol
  test/libsolidity/semanticTests/functionCall/bound_function_in_function.sol
  test/libsolidity/semanticTests/functionCall/bound_function_in_var.sol
  test/libsolidity/semanticTests/functionCall/bound_function_to_string.sol
  test/libsolidity/semanticTests/libraries/internal_types_in_library.sol
  test/libsolidity/semanticTests/libraries/library_call_in_homestead.sol
  test/libsolidity/semanticTests/libraries/library_stray_values.sol
  test/libsolidity/semanticTests/libraries/mapping_arguments_in_library.sol
  test/libsolidity/semanticTests/libraries/mapping_returns_in_library.sol
  test/libsolidity/semanticTests/libraries/mapping_returns_in_library_named.sol
  test/libsolidity/semanticTests/libraries/payable_function_calls_library.sol
  test/libsolidity/semanticTests/libraries/using_for_by_name.sol
  test/libsolidity/semanticTests/libraries/using_for_overload.sol
  test/libsolidity/semanticTests/libraries/using_library_mappings_public.sol
  test/libsolidity/semanticTests/libraries/using_library_mappings_return.sol
  test/libsolidity/semanticTests/libraries/using_library_structs.sol
  test/libsolidity/semanticTests/structs/struct_referencing.sol
  test/libsolidity/semanticTests/structs/using_for_function_on_struct.sol
Labels: testing :hammer:

#12396 External tests via IR
  .circleci/config.yml
  scripts/common.sh
  test/externalTests/colony.sh
  test/externalTests/common.sh
  test/externalTests/ens.sh
  test/externalTests/gnosis-v2.sh
  test/externalTests/gnosis.sh
  test/externalTests/zeppelin.sh
Labels: testing :hammer:

#12408 Update circleci mac xcode version to 13.2
  .circleci/config.yml
Labels: external contribution :star:

#12397 Enable external test presets that compile but fail tests
  test/externalTests/colony.sh
  test/externalTests/common.sh
  test/externalTests/ens.sh
  test/externalTests/gnosis-v2.sh
  test/externalTests/gnosis.sh
  test/externalTests/zeppelin.sh
Labels: testing :hammer:

#12361 Changed the message of the error thrown when the structure has all it's members omitted
  libsolidity/analysis/TypeChecker.cpp
  test/libsolidity/syntaxTests/nameAndTypeResolution/070_struct_accessor_one_array_only.sol
Labels: external contribution :star:

#12446 Fix ESLint warnings/errors in external test JS
  test/externalTests/solc-js/determinism.js
Labels: testing :hammer:

#12445 [pylint] Enable more warnings
  docs/conf.py
  scripts/endToEndExtraction/remove-testcases.py
  scripts/endToEndExtraction/verify-testcases.py
  scripts/error_codes.py
  scripts/isolate_tests.py
  scripts/pylint_all.py
  scripts/pylintrc
  scripts/regressions.py
  scripts/splitSources.py
  scripts/wasm-rebuild/docker-scripts/isolate_tests.py
  test/formal/rule.py
  test/lsp.py
Labels: testing :hammer:

#12444 [pylint] Disable the opinionated too-many-xyz warnings
  scripts/bytecodecompare/prepare_report.py
  scripts/endToEndExtraction/verify-testcases.py
  scripts/error_codes.py
  scripts/pylintrc
Labels: testing :hammer:

#12198 Switch ENS external test to ens-contracts repo
  .circleci/config.yml
  test/externalTests/common.sh
  test/externalTests/ens.sh
Labels: testing :hammer:
