Repository argotorg/solidity, pull requests merged in 2022-04, with the labels that each got.

#12868 Workarounds for ext test breakage (ethers.js downgrade, disabled polygon test in zeppelin, switch to compiler-only in elementfi)
  test/externalTests/elementfi.sh
  test/externalTests/ens.sh
  test/externalTests/euler.sh
  test/externalTests/gnosis.sh
  test/externalTests/perpetual-pools.sh
  test/externalTests/uniswap.sh
  test/externalTests/zeppelin.sh
Labels: testing :hammer:

#12702 cmake/EthCompilerSettings.cmake: generator expression fix for ninja.
  cmake/EthCompilerSettings.cmake
Labels: build system :building_construction:

#12887 Fix broken `${}` syntax in `externalTests.sh` (redo)
  test/externalTests.sh
Labels: testing :hammer:

#12873 abstract-contracts.rst: Clarify when a contract may or must be marked abstract
  docs/contracts/abstract-contracts.rst
Labels: documentation :book:, external contribution :star:

#12835 Fix MultiSigWallet.sol order of functions
  test/compilationTests/MultiSigWallet/MultiSigWallet.sol
Labels: external contribution :star:, testing :hammer:, style guide

#12179 Set handlers use unified jsonPrint with prettifier if needed
  Changelog.md
  libsolidity/ast/ASTJsonConverter.cpp
  libsolidity/ast/ASTJsonConverter.h
  solc/CommandLineInterface.cpp
  test/cmdlineTests/asm_json/args
  test/cmdlineTests/asm_json_no_pretty_print/args
  test/cmdlineTests/asm_json_no_pretty_print/input.sol
  test/cmdlineTests/asm_json_no_pretty_print/output
  test/cmdlineTests/ast_compact_json_no_pretty_json/args
  test/cmdlineTests/ast_compact_json_no_pretty_json/input.sol
  test/cmdlineTests/ast_compact_json_no_pretty_json/output
  test/cmdlineTests/ast_compact_json_with_base_path/args
  test/cmdlineTests/combined_json_abi/args
  test/cmdlineTests/combined_json_abi/input.sol
  test/cmdlineTests/combined_json_abi/output
  test/cmdlineTests/combined_json_no_pretty_print/args
  test/cmdlineTests/combined_json_no_pretty_print/input.sol
  test/cmdlineTests/combined_json_no_pretty_print/output
  test/cmdlineTests/combined_json_with_base_path/args
  test/cmdlineTests/combined_json_with_base_path/output
  test/cmdlineTests/combined_json_with_devdoc/args
  test/cmdlineTests/combined_json_with_devdoc/input.sol
  test/cmdlineTests/combined_json_with_devdoc/output
  test/cmdlineTests/combined_json_with_userdoc/args
  test/cmdlineTests/combined_json_with_userdoc/input.sol
  test/cmdlineTests/combined_json_with_userdoc/output
  test/cmdlineTests/recovery_ast_constructor/args
  test/cmdlineTests/standard_json_no_pretty_print/args
  test/cmdlineTests/standard_json_no_pretty_print/input.json
  test/cmdlineTests/standard_json_no_pretty_print/output.json
  test/cmdlineTests/storage_layout_user_defined/args
  test/cmdlineTests/storage_layout_user_defined/output
  test/cmdlineTests/storage_layout_user_defined_no_pretty_print/args
  test/cmdlineTests/storage_layout_user_defined_no_pretty_print/input.sol
  test/cmdlineTests/storage_layout_user_defined_no_pretty_print/output
  test/libsolidity/ASTJSONTest.cpp
Labels: external contribution :star:

#12899 Implements $/setTrace and uses trace logging.
  libsolidity/lsp/LanguageServer.cpp
  libsolidity/lsp/LanguageServer.h
  libsolidity/lsp/Transport.cpp
  libsolidity/lsp/Transport.h
Labels: language server

#12885 Improve error message for static array with size too large
  libsolidity/analysis/DeclarationTypeChecker.cpp
  test/libsolidity/syntaxTests/array/length/bytes32_too_large.sol
  test/libsolidity/syntaxTests/array/length/bytes32_too_large_multidim.sol
  test/libsolidity/syntaxTests/array/length/literal_conversion.sol
  test/libsolidity/syntaxTests/array/length/too_large.sol
  test/libsolidity/syntaxTests/array/length/uint_too_large_multidim.sol
Labels: external contribution :star:

#12898 Create split_on_empty_lines_into_numbered_files function in scripts/common.sh
  scripts/common.sh
  test/cmdlineTests.sh
Labels: testing :hammer:

#12804 Benchmark differ
  scripts/externalTests/benchmark_diff.py
  test/scripts/fixtures/summarized-benchmark-diff-develop-branch-humanized.md
  test/scripts/fixtures/summarized-benchmarks-branch.json
  test/scripts/fixtures/summarized-benchmarks-develop.json
  test/scripts/test_externalTests_benchmark_diff.py
Labels: testing :hammer:

#12751 updates to gas section
  docs/introduction-to-smart-contracts.rst
Labels: documentation :book:, external contribution :star:, takeover

#12283 Graceful error handling in soltest/isoltest + improved soltestAssert()
  liblangutil/Exceptions.h
  libsmtutil/Exceptions.h
  libsolutil/Assertions.h
  libsolutil/Exceptions.h
  libyul/Exceptions.h
  test/Common.cpp
  test/Common.h
  test/boostTest.cpp
  test/libsolidity/util/SoltestErrors.h
  test/tools/IsolTestOptions.cpp
  test/tools/isoltest.cpp
Labels: testing :hammer:

#12901 Clarify base contract constructors (re request of PR #12872)
  docs/contracts/inheritance.rst
Labels: documentation :book:, external contribution :star:

#12876 [Docs] clarify the reason for the memory-unsafe assembly example being unsafe
  docs/assembly.rst
Labels: documentation :book:, external contribution :star:

#12909 Add `.DS_Store` and `Thumbs.db` to `.gitignore`
  .gitignore
Labels: external contribution :star:

#12866 Renamed AssemblyStack to YulStack
  libsolidity/codegen/ir/IRGenerator.cpp
  libsolidity/interface/CompilerStack.cpp
  libsolidity/interface/StandardCompiler.cpp
  libyul/CMakeLists.txt
  libyul/YulStack.cpp
  libyul/YulStack.h
  solc/CommandLineInterface.cpp
  solc/CommandLineInterface.h
  solc/CommandLineParser.cpp
  solc/CommandLineParser.h
  test/libsolidity/InlineAssembly.cpp
  test/libsolidity/SolidityExecutionFramework.cpp
  test/libsolidity/SolidityExecutionFramework.h
  test/libyul/Common.cpp
  test/libyul/EVMCodeTransformTest.cpp
  test/libyul/EwasmTranslationTest.cpp
  test/libyul/EwasmTranslationTest.h
  test/libyul/ObjectCompilerTest.cpp
  test/libyul/ObjectParser.cpp
  test/libyul/YulInterpreterTest.cpp
  test/solc/CommandLineParser.cpp
  test/tools/ossfuzz/SolidityEvmoneInterface.h
  test/tools/ossfuzz/YulEvmoneInterface.cpp
  test/tools/ossfuzz/YulEvmoneInterface.h
  test/tools/ossfuzz/strictasm_assembly_ossfuzz.cpp
  test/tools/ossfuzz/strictasm_diff_ossfuzz.cpp
  test/tools/ossfuzz/strictasm_opt_ossfuzz.cpp
  test/tools/ossfuzz/yulProtoFuzzer.cpp
  test/tools/ossfuzz/yulProto_diff_ossfuzz.cpp
  test/tools/yulrun.cpp
Labels: external contribution :star:

#12916 inheritance.rst: Fix capitalization in multiple inheritance example
  docs/contracts/inheritance.rst
Labels: documentation :book:, external contribution :star:

#12908 Moved `docs.sh` script to `docs/`
  .circleci/config.yml
  docs/contributing.rst
  docs/docs.sh
Labels: external contribution :star:

#12562 External test for Brink
  .circleci/config.yml
  test/externalTests.sh
  test/externalTests/brink.sh
  test/externalTests/common.sh
Labels: testing :hammer:

#12936 Prevent parallel soltest runs from overwriting each other's XML test output
  .circleci/soltest.sh
Labels: testing :hammer:

#12798 LSP.py: Implement expectations directly in the test files
  scripts/tests.sh
  test/libsolidity/lsp/goto_definition.sol
  test/libsolidity/lsp/goto_definition_imports.sol
  test/libsolidity/lsp/lib.sol
  test/libsolidity/lsp/publish_diagnostics_1.sol
  test/libsolidity/lsp/publish_diagnostics_2.sol
  test/lsp.py
Labels: testing :hammer:, language server
