Repository argotorg/solidity, pull requests merged in 2022-12, with the labels that each got.

#13770 [DOCS] Remove mentions of Yul being experimental from docs
  docs/yul.rst
Labels: documentation :book:

#13760 Add optimizor club benchmark.
  test/benchmarks/OptimizorClub.sol
  test/benchmarks/run.sh
Labels: testing :hammer:

#12274 Re-use knowledge about keccak calls.
  Changelog.md
  libyul/optimiser/DataFlowAnalyzer.cpp
  libyul/optimiser/DataFlowAnalyzer.h
  libyul/optimiser/LoadResolver.cpp
  test/libsolidity/semanticTests/array/reusing_memory.sol
  test/libsolidity/semanticTests/structs/copy_substructures_to_mapping.sol
  test/libsolidity/semanticTests/structs/struct_copy.sol
  test/libyul/yulOptimizerTests/loadResolver/keccak_reuse_basic.yul
  test/libyul/yulOptimizerTests/loadResolver/keccak_reuse_expr_mstore.yul
  test/libyul/yulOptimizerTests/loadResolver/keccak_reuse_in_expression.yul
  test/libyul/yulOptimizerTests/loadResolver/keccak_reuse_msize.yul
  test/libyul/yulOptimizerTests/loadResolver/keccak_reuse_mstore.yul
  test/libyul/yulOptimizerTests/loadResolver/keccak_reuse_reassigned_branch.yul
  test/libyul/yulOptimizerTests/loadResolver/keccak_reuse_reassigned_value.yul
Labels: optimizer, priority review

#13784 Fixed typo in abi.encodeWithSignature description
  docs/cheatsheet.rst
Labels: documentation :book:, external contribution :star:

#13803 [docs]: Add Solidity favicon
  docs/_static/img/favicon.png
  docs/conf.py
Labels: documentation :book:, external contribution :star:

#13810 External tests maintenance
  .gitignore
  test/externalTests/chainlink.sh
  test/externalTests/elementfi.sh
  test/externalTests/ens.sh
  test/externalTests/euler.sh
  test/externalTests/gnosis.sh
  test/externalTests/gp2.sh
  test/externalTests/perpetual-pools.sh
  test/externalTests/pool-together.sh
  test/externalTests/prb-math.sh
  test/externalTests/trident.sh
  test/externalTests/uniswap.sh
  test/externalTests/zeppelin.sh
Labels: testing :hammer:

#13782 docs(resources.rst): update editor extensions
  docs/resources.rst
Labels: documentation :book:, external contribution :star:

#13814 Fixed some comments in `Types.h`
  libsolidity/ast/Types.h
Labels: documentation :book:, external contribution :star:

#13659 Report when no contracts to compile
  solc/CommandLineInterface.cpp
  test/cmdlineTests.sh
  test/cmdlineTests/no_contract_combined_json/args
  test/cmdlineTests/no_contract_combined_json/input.sol
  test/cmdlineTests/no_contract_combined_json/output
  test/solc/CommandLineInterface.cpp
Labels: external contribution :star:

#13830 docs: fix typos
  test/libsolidity/AnalysisFramework.h
  test/libsolidity/SolidityEndToEndTest.cpp
  test/libsolidity/semanticTests/externalContracts/snark.sol
  test/libsolidity/semanticTests/structs/struct_referencing.sol
  test/tools/ossfuzz/protoToAbiV2.cpp
Labels: external contribution :star:
