Repository argotorg/solidity, pull requests merged in 2022-07, with the labels that each got.

#13105 docs: add notice about `address` conversion prior to 0.8.0
  docs/types/conversion.rst
Labels: documentation :book:, external contribution :star:

#13240 Fix C++ compilation errors on 32-bit Raspbian due to `unsigned` -> `int` conversion
  test/Metadata.cpp
  test/libevmasm/Optimiser.cpp
  test/libsolidity/util/TestFileParser.h
Labels: external contribution :star:

#13250 Update rangev3 to 0.12.0
  cmake/range-v3.cmake
  scripts/release_ppa.sh
Labels: build system :building_construction:, external contribution :star:

#12679 tweak: expand definition of suggested collision naming convention
  docs/style-guide.rst
Labels: documentation :book:, external contribution :star:, style guide

#13096 Moved Keywords section from 'Cheatsheet' to 'Units and Globally Available Variables'
  docs/cheatsheet.rst
  docs/units-and-global-variables.rst
Labels: documentation :book:, external contribution :star:

#13255 [Docs] Fix operator docs to use an actually convertible type when describing how common type is chosen
  docs/types/operators.rst
Labels: documentation :book:, external contribution :star:

#13103 Lsp rename feature
  libsolidity/CMakeLists.txt
  libsolidity/lsp/FileRepository.h
  libsolidity/lsp/HandlerBase.h
  libsolidity/lsp/LanguageServer.cpp
  libsolidity/lsp/LanguageServer.h
  libsolidity/lsp/RenameSymbol.cpp
  libsolidity/lsp/RenameSymbol.h
  libsolidity/lsp/SemanticTokensBuilder.cpp
  test/libsolidity/lsp/rename/contract.sol
  test/libsolidity/lsp/rename/function.sol
  test/libsolidity/lsp/rename/functionCall.sol
  test/libsolidity/lsp/rename/import_directive.sol
  test/libsolidity/lsp/rename/variable.sol
  test/lsp.py
Labels: language server, priority review

#12681 tweak: update maximum line length
  docs/style-guide.rst
Labels: documentation :book:, external contribution :star:, has dependencies, style guide

#13263 lsp: Fixes lsp.py to not bail out when no response is expected.
  test/lsp.py
Labels: testing :hammer:, language server, priority review

#12994 LSP to resolve custom include paths (e.g. Hardhat)
  Changelog.md
  libsolidity/lsp/FileRepository.cpp
  libsolidity/lsp/FileRepository.h
  libsolidity/lsp/LanguageServer.cpp
  test/libsolidity/lsp/include-paths/default_include.sol
  test/libsolidity/lsp/include-paths/file_at_include_path.sol
  test/libsolidity/lsp/include-paths/file_not_found_in_searchpath.sol
  test/libsolidity/lsp/include-paths/using-custom-includes.sol
  test/libsolidity/lsp/node_modules/my-module/test.sol
  test/libsolidity/lsp/node_modules/rootlib.sol
  test/libsolidity/lsp/other-include-dir/otherlib/otherlib.sol
  test/lsp.py
Labels: language server, priority review

#13274 lsp: Fixes initialization phase if `include-paths` was not set at all then also no error should be generated.
  libsolidity/lsp/LanguageServer.cpp
Labels: language server, priority review

#13261 Only analyze memory in DataFlowAnalyzer if it is needed in the optimizer step.
  libyul/optimiser/CommonSubexpressionEliminator.cpp
  libyul/optimiser/DataFlowAnalyzer.cpp
  libyul/optimiser/DataFlowAnalyzer.h
  libyul/optimiser/EqualStoreEliminator.h
  libyul/optimiser/ExpressionSimplifier.h
  libyul/optimiser/LoadResolver.h
  libyul/optimiser/Rematerialiser.cpp
  libyul/optimiser/Rematerialiser.h
  libyul/optimiser/StackCompressor.cpp
Labels: priority review

#13273 lsp.py: Pass trace option during initialization already.
  libsolidity/lsp/LanguageServer.cpp
  test/lsp.py
Labels: language server

#13276 Settings struct for name resolution.
  libsolidity/analysis/DeclarationContainer.cpp
  libsolidity/analysis/DeclarationContainer.h
  libsolidity/analysis/NameAndTypeResolver.cpp
Labels: priority review

#13128 docs: specify memory-safe is available since 0.8.13 for inline assembly
  docs/assembly.rst
Labels: documentation :book:, external contribution :star:

#13293 Grammatical fixes in `assembly.rst`
  docs/assembly.rst
Labels: documentation :book:, external contribution :star:

#13280 Fix NULL dereference in abi.encodeCall check
  Changelog.md
  libsolidity/analysis/TypeChecker.cpp
  test/libsolidity/syntaxTests/abiEncoder/abi_encodeCall_error_free_function.sol
  test/libsolidity/syntaxTests/abiEncoder/abi_encodeCall_event_free_function.sol
  test/libsolidity/syntaxTests/abiEncoder/abi_encodeCall_free_func.sol
  test/libsolidity/syntaxTests/abiEncoder/abi_encodeCall_on_lib_func_in_free_func.sol
Labels: external contribution :star:

#13306 Disable SMT tests on Arch Linux
  .circleci/config.yml
Labels: testing :hammer:

#13131 replace boost::range::for_each with range::views:zip + loop
  test/libsolidity/util/ContractABIUtils.cpp
Labels: external contribution :star:
