Repository argotorg/solidity, pull requests merged in 2022-08, with the labels that each got.

#13279 Fix out-of-range compiler crash error for unary tuples
  Changelog.md
  libsolidity/analysis/TypeChecker.cpp
  test/libsolidity/syntaxTests/tupleAssignments/empty_tuple_assignment.sol
  test/libsolidity/syntaxTests/tupleAssignments/fixed_byte_array_assignment_in_tuple.sol
Labels: external contribution :star:

#13345 Update description of `this` in free functions
  docs/contracts/functions.rst
Labels: documentation :book:, external contribution :star:

#13354 Place calldata to calldata coder sanity checks.
  test/tools/ossfuzz/abiV2ProtoFuzzer.cpp
  test/tools/ossfuzz/protoToAbiV2.cpp
  test/tools/ossfuzz/protoToAbiV2.h
Labels: testing :hammer:

#13282 Fix wrong cleanup when copying from calldata to memory.
  Changelog.md
  docs/bugs.json
  docs/bugs_by_version.json
  libsolidity/codegen/ABIFunctions.cpp
  libsolidity/codegen/ABIFunctions.h
  libsolidity/codegen/YulUtilFunctions.cpp
  libsolidity/codegen/YulUtilFunctions.h
  test/cmdlineTests/debug_info_in_yul_snippet_escaping/output
  test/cmdlineTests/name_simplifier/output
  test/cmdlineTests/viair_subobject_optimization/output
  test/cmdlineTests/yul_string_format_ascii/output.json
  test/cmdlineTests/yul_string_format_ascii_long/output.json
  test/libsolidity/gasTests/abiv2.sol
  test/libsolidity/gasTests/abiv2_optimised.sol
  test/libsolidity/semanticTests/abiEncoderV1/abi_encode_calldata_slice.sol
  test/libsolidity/semanticTests/abiEncoderV1/calldata_bytes_bytes32_arrays.sol
  test/libsolidity/semanticTests/abiEncoderV1/memory_dynamic_array_and_calldata_bytes.sol
  test/libsolidity/semanticTests/abiEncoderV2/abi_encode_calldata_slice.sol
  test/libsolidity/semanticTests/abiEncoderV2/abi_encode_v2.sol
  test/libsolidity/semanticTests/abiEncoderV2/abi_encoder_v2_head_overflow_with_static_array_cleanup_bug.sol
  test/libsolidity/semanticTests/abiEncoderV2/calldata_array.sol
  test/libsolidity/semanticTests/abiEncoderV2/calldata_array_dynamic_static_in_library.sol
  test/libsolidity/semanticTests/abiEncoderV2/cleanup/reencoded_calldata_string.sol
  test/libsolidity/semanticTests/abiEncoderV2/memory_dynamic_array_and_calldata_bytes.sol
  test/libsolidity/semanticTests/abiEncoderV2/memory_dynamic_array_and_calldata_static_array.sol
  test/libsolidity/semanticTests/abiEncoderV2/storage_array_encoding.sol
  test/libsolidity/semanticTests/abiencodedecode/abi_decode_simple_storage.sol
  test/libsolidity/semanticTests/array/copying/bytes_storage_to_storage.sol
  test/libsolidity/semanticTests/array/copying/copy_byte_array_in_struct_to_storage.sol
  test/libsolidity/semanticTests/array/copying/function_type_array_to_storage.sol
  test/libsolidity/semanticTests/array/copying/storage_memory_nested_bytes.sol
  test/libsolidity/semanticTests/array/pop/byte_array_pop_copy_long.sol
  test/libsolidity/semanticTests/array/pop/byte_array_pop_masking_long.sol
  test/libsolidity/semanticTests/byte_array_to_storage_cleanup.sol
  test/libsolidity/semanticTests/constructor/bytes_in_constructors_packer.sol
  test/libsolidity/semanticTests/constructor/bytes_in_constructors_unpacker.sol
  test/libsolidity/semanticTests/errors/error_static_calldata_uint_array_and_dynamic_array.sol
  test/libsolidity/semanticTests/events/event_static_calldata_uint_array_and_dynamic_array.sol
  test/libsolidity/semanticTests/externalContracts/FixedFeeRegistrar.sol
  test/libsolidity/semanticTests/externalContracts/base64.sol
  test/libsolidity/semanticTests/externalContracts/deposit_contract.sol
  test/libsolidity/semanticTests/externalContracts/strings.sol
  test/libsolidity/semanticTests/functionCall/external_call_to_nonexisting.sol
  test/libsolidity/semanticTests/functionCall/external_call_to_nonexisting_debugstrings.sol
  test/libsolidity/semanticTests/various/address_code.sol
  test/libsolidity/semanticTests/various/skip_dynamic_types_for_structs.sol
  test/libsolidity/syntaxTests/bytecode_too_large.sol
  test/libsolidity/syntaxTests/bytecode_too_large_byzantium.sol
Labels: priority review

#13300 Docs — Minor grammar fixes in `abi-spec.rst`
  docs/abi-spec.rst
Labels: documentation :book:, external contribution :star:

#13286 Modify the metadata / hash document.
  docs/metadata.rst
Labels: documentation :book:, external contribution :star:

#13262 [Docs] Fixed link to internal-function-calls
  docs/contracts/functions.rst
Labels: documentation :book:, external contribution :star:

#13289 Calldata validation tests
  test/libsolidity/semanticTests/abiEncoderV2/calldata_dynamic_array_to_memory.sol
  test/libsolidity/semanticTests/abiEncoderV2/calldata_nested_array_reencode.sol
  test/libsolidity/semanticTests/abiEncoderV2/calldata_overlapped_dynamic_arrays.sol
  test/libsolidity/semanticTests/abiEncoderV2/calldata_overlapped_nested_dynamic_arrays.sol
  test/libsolidity/semanticTests/abiEncoderV2/calldata_struct_array_reencode.sol
  test/libsolidity/semanticTests/abiEncoderV2/calldata_three_dimensional_dynamic_array_index_access.sol
  test/libsolidity/semanticTests/abiEncoderV2/calldata_with_garbage.sol
Labels: testing :hammer:

#13370 Little enhancements to the ppa release script
  .gitignore
  scripts/release_ppa.sh
Labels: build system :building_construction:

#13380 Permit multiple indirections in coding calldata to and from memory/calldata
  test/tools/ossfuzz/AbiV2IsabelleFuzzer.cpp
  test/tools/ossfuzz/SolidityEvmoneInterface.cpp
  test/tools/ossfuzz/SolidityEvmoneInterface.h
  test/tools/ossfuzz/abiV2Proto.proto
  test/tools/ossfuzz/abiV2ProtoFuzzer.cpp
  test/tools/ossfuzz/protoToAbiV2.cpp
  test/tools/ossfuzz/protoToAbiV2.h
  test/tools/ossfuzz/solProtoFuzzer.cpp
Labels: testing :hammer:

#13177 Check overflow after multiplication operation is executed.
  Changelog.md
  libsolidity/codegen/YulUtilFunctions.cpp
  test/formal/checked_int_mul_12.py
  test/formal/checked_int_mul_16.py
  test/formal/checked_uint_mul_12.py
  test/formal/signed_integer_cleanup_function.py
  test/formal/unsigned_integer_cleanup_function.py
  test/formal/util.py
  test/libsolidity/semanticTests/abiEncoderV2/storage_array_encoding.sol
  test/libsolidity/semanticTests/array/copying/array_copy_including_array.sol
  test/libsolidity/semanticTests/array/copying/array_copy_nested_array.sol
  test/libsolidity/semanticTests/array/copying/array_copy_storage_storage_struct.sol
  test/libsolidity/semanticTests/array/copying/array_copy_target_leftover.sol
  test/libsolidity/semanticTests/array/copying/array_nested_calldata_to_storage.sol
  test/libsolidity/semanticTests/array/copying/array_of_struct_calldata_to_storage.sol
  test/libsolidity/semanticTests/externalContracts/base64.sol
  test/libsolidity/semanticTests/externalContracts/ramanujan_pi.sol
  test/libsolidity/semanticTests/externalContracts/snark.sol
  test/libsolidity/semanticTests/externalContracts/strings.sol
  test/libsolidity/semanticTests/salted_create/salted_create_with_value.sol
  test/libsolidity/semanticTests/viaYul/detect_mul_overflow_signed.sol
Labels: priority review

#12837 Rephrase comment about arrays of arrays in code example.
  docs/types/reference-types.rst
Labels: documentation :book:, external contribution :star:, takeover

#12844 Update operators.rst
  docs/types/operators.rst
Labels: documentation :book:, external contribution :star:

#12954 Link to address literals from address value types
  docs/types/value-types.rst
Labels: documentation :book:, external contribution :star:

#12852 Update reference-types.rst
  docs/types/reference-types.rst
Labels: documentation :book:, external contribution :star:

#13256 Added build flag to disable pedantic builds
  CMakeLists.txt
  cmake/EthCompilerSettings.cmake
  docs/installing-solidity.rst
Labels: build system :building_construction:, external contribution :star:

#13346 Update description of input parameter type and return type limitations
  docs/contracts/functions.rst
  docs/layout-of-source-files.rst
Labels: documentation :book:, external contribution :star:

#13374 Update the default free memory pointer in Yul.rst
  docs/yul.rst
Labels: documentation :book:, external contribution :star:

#13389 Fix "signed/unsigned mismatch" warnings (MSVC)
  libyul/optimiser/FullInliner.cpp
Labels: external contribution :star:

#12855 Rephrase named vs unnamed parameters in function definitions (in control-structures.rst).
  docs/control-structures.rst
Labels: documentation :book:, external contribution :star:

#13388 Fix iter_swap build issue
  libsolidity/ast/ASTJsonExporter.cpp
Labels: waiting for more input, external contribution :star:

#13401 Enable highlighting for more code blocks in the docs
  docs/internals/layout_in_storage.rst
  docs/introduction-to-smart-contracts.rst
  docs/natspec-format.rst
Labels: documentation :book:

#13398 test/cmdlineTests.sh: fix verbosity.
  test/cmdlineTests.sh
Labels: testing :hammer:

#13404 Peg hardhat-ethers version
  test/externalTests/gnosis.sh
Labels: testing :hammer:

#13287 Document in ``solc --help`` usage of ``--metadata`` better.
  solc/CommandLineParser.cpp
Labels: documentation :book:

#13411 Fix spelling mistakes and CI spellcheck job
  .circleci/config.yml
  libevmasm/KnownState.h
  liblangutil/Scanner.cpp
  libsolutil/StringUtils.h
  scripts/codespell_ignored_lines.txt
  scripts/codespell_whitelist.txt
  test/externalTests/README.md
  test/libevmasm/Optimiser.cpp
  test/liblangutil/Scanner.cpp
  test/libsolidity/SolidityExpressionCompiler.cpp
  test/libsolidity/semanticTests/externalContracts/_prbmath/PRBMathCommon.sol
  test/libsolidity/semanticTests/externalContracts/_prbmath/PRBMathUD60x18.sol
Labels: testing :hammer:

#13413 Use long option for spellchecker in CI
  .circleci/config.yml
Labels: testing :hammer:, low effort, low impact

#13400 [buildpack] Switch to unsplash/comment-on-pr@v1.3.0.
  .github/workflows/buildpack-deps.yml
Labels: build system :building_construction:

#12762 Optimize ``return(x,0) -> pop(x) return(0,0)`` (and also for ``revert``).
  Changelog.md
  libyul/optimiser/DataFlowAnalyzer.cpp
  libyul/optimiser/DataFlowAnalyzer.h
  libyul/optimiser/ExpressionSimplifier.cpp
  libyul/optimiser/ExpressionSimplifier.h
  test/cmdlineTests/debug_info_in_yul_and_evm_asm_print_all/output
  test/cmdlineTests/debug_info_in_yul_and_evm_asm_print_location_only/output
  test/cmdlineTests/debug_info_in_yul_and_evm_asm_print_none/output
  test/cmdlineTests/ir_compiler_subobjects/output
  test/cmdlineTests/ir_with_assembly_no_memoryguard_creation/output
  test/cmdlineTests/ir_with_assembly_no_memoryguard_runtime/output
  test/cmdlineTests/standard_debug_info_in_yul_and_evm_asm_print_all/output.json
  test/cmdlineTests/standard_debug_info_in_yul_and_evm_asm_print_location_only/output.json
  test/cmdlineTests/standard_debug_info_in_yul_and_evm_asm_print_none/output.json
  test/cmdlineTests/viair_subobjects/output
  test/externalTests/chainlink.sh
  test/libsolidity/semanticTests/abiEncoderV1/abi_encode_calldata_slice.sol
  test/libsolidity/semanticTests/abiEncoderV2/abi_encode_calldata_slice.sol
  test/libsolidity/semanticTests/array/copying/array_copy_storage_storage_dyn_dyn.sol
  test/libsolidity/semanticTests/array/copying/function_type_array_to_storage.sol
  test/libsolidity/semanticTests/array/dynamic_array_cleanup.sol
  test/libsolidity/semanticTests/array/dynamic_arrays_in_storage.sol
  test/libsolidity/semanticTests/array/fixed_array_cleanup.sol
  test/libsolidity/semanticTests/array/pop/byte_array_pop_long_storage_empty_garbage_ref.sol
  test/libsolidity/semanticTests/array/push/nested_bytes_push.sol
  test/libsolidity/semanticTests/array/push/push_no_args_2d.sol
  test/libsolidity/semanticTests/array/push/push_no_args_bytes.sol
  test/libsolidity/semanticTests/events/event_dynamic_array_storage.sol
  test/libsolidity/semanticTests/events/event_dynamic_array_storage_v2.sol
  test/libsolidity/semanticTests/events/event_dynamic_nested_array_storage_v2.sol
  test/libsolidity/semanticTests/events/event_emit_from_other_contract.sol
  test/libsolidity/semanticTests/events/event_indexed_string.sol
  test/libsolidity/semanticTests/externalContracts/FixedFeeRegistrar.sol
  test/libsolidity/semanticTests/externalContracts/base64.sol
  test/libsolidity/semanticTests/functionCall/gas_and_value_basic.sol
  test/libsolidity/semanticTests/functionCall/gas_and_value_brace_syntax.sol
  test/libsolidity/semanticTests/structs/struct_delete_storage_with_array.sol
  test/libsolidity/semanticTests/structs/structs.sol
  test/libsolidity/semanticTests/userDefinedValueType/calldata.sol
  test/libsolidity/semanticTests/various/contract_binary_dependencies.sol
  test/libsolidity/semanticTests/various/swap_in_storage_overwrite.sol
  test/libsolidity/semanticTests/viaYul/array_storage_index_access.sol
  test/libsolidity/semanticTests/viaYul/array_storage_index_zeroed_test.sol
  test/libsolidity/semanticTests/viaYul/array_storage_push_empty.sol
  test/libsolidity/semanticTests/viaYul/copy_struct_invalid_ir_bug.sol
  test/libyul/yulOptimizerTests/expressionSimplifier/side_effects_in_for_condition.yul
  test/libyul/yulOptimizerTests/expressionSimplifier/zero_length_read.yul
Labels: optimizer, priority review

#13150 LSP analyze all files in project
  Changelog.md
  libsolidity/lsp/FileRepository.cpp
  libsolidity/lsp/LanguageServer.cpp
  libsolidity/lsp/LanguageServer.h
  libsolidity/lsp/Transport.cpp
  test/libsolidity/lsp/analyze-full-project/C.sol
  test/libsolidity/lsp/analyze-full-project/D.sol
  test/libsolidity/lsp/analyze-full-project/E.sol
  test/libsolidity/lsp/include-paths-nested-2/A/B/C/foo.sol
  test/libsolidity/lsp/include-paths-nested-2/A/B/foo.sol
  test/libsolidity/lsp/include-paths-nested-2/A/foo.sol
  test/libsolidity/lsp/include-paths-nested-2/foo.sol
  test/libsolidity/lsp/include-paths-nested/A/B/C/foo.sol
  test/libsolidity/lsp/include-paths-nested/A/B/foo.sol
  test/libsolidity/lsp/include-paths-nested/A/foo.sol
  test/libsolidity/lsp/include-paths-nested/foo.sol
  test/libsolidity/lsp/other-include-dir/otherlib/second.sol
  test/lsp.py
Labels: language server, priority review

#12923 [Circle CI] Parameterize b_bytecode_ubu and b_bytecode_osx build job
  .circleci/config.yml
Labels: external contribution :star:, testing :hammer:

#13397 Update Metadata docs
  docs/metadata.rst
Labels: documentation :book:

#13430 Fix inconsistent nested dependency in safe-contracts
  test/externalTests/gnosis.sh
Labels: testing :hammer:

#13444 Fix pylint warning
  scripts/common/rest_api_helpers.py
  test/scripts/test_externalTests_benchmark_downloader.py
Labels: priority review

#13429 Fix warning about DOWNLOAD_EXTRACT_TIMESTAMP on CMake 3.24
  cmake/EthPolicy.cmake
Labels: build system :building_construction:, external contribution :star:

#13449 [Tiny] Fix undefined order of evaluation
  libyul/backends/evm/EVMDialect.cpp
Labels: low effort, low impact

#13409 Reduce duplication in AST helpers for finding try/catch clauses
  libsolidity/ast/AST.cpp
Labels: external contribution :star:

#13292 Placeholder elaboration in function-modifiers.rst
  docs/contracts/function-modifiers.rst
Labels: documentation :book:, external contribution :star:

#13457 Explained Checks-Effects-Interactions
  docs/security-considerations.rst
Labels: documentation :book:, external contribution :star:

#13387 Add detail about limitation in voting contract to fix #12478
  docs/examples/voting.rst
Labels: documentation :book:, external contribution :star:
