Repository argotorg/solidity, pull requests merged in 2022-06, with the labels that each got.

#13083 lsp.py: Fix various problems with subdirectory edge cases
  .circleci/config.yml
  test/lsp.py
Labels: language server

#13088 Fix new warnings from pylint 2.14 and adjust pylint config
  .circleci/config.yml
  scripts/gas_diff_stats.py
  scripts/pylintrc
Labels: testing :hammer:

#13087 Workaround for the spurious `control reaches end of non-void function` warning in GCC 12.1
  libsmtutil/CVC4Interface.cpp
  libsmtutil/Z3Interface.cpp
  libsolidity/ast/ASTJsonImporter.cpp
  libsolidity/parsing/Parser.cpp
  libyul/AsmJsonImporter.cpp
  libyul/backends/evm/StackHelpers.h
  tools/yulPhaser/Phaser.cpp
Labels: has dependencies

#13092 Disabling more OpenZeppelin tests that expect reverts with specific error
  test/externalTests/zeppelin.sh
Labels: testing :hammer:

#13097 Skipping benchmark diff when previous run failed
  .circleci/config.yml
  scripts/common/rest_api_helpers.py
  scripts/externalTests/download_benchmarks.py
Labels: testing :hammer:

#13093 lsp.py: Add missing check for non-interactive
  test/lsp.py
Labels: testing :hammer:

#13079 Sort grammar rules of SolidityLexer.g4
  docs/grammar/SolidityLexer.g4
Labels: external contribution :star:

#13005 Display human readable type name in conversion error message
  libsolidity/analysis/TypeChecker.cpp
  libsolidity/ast/Types.cpp
  libsolidity/ast/Types.h
  test/libsolidity/syntaxTests/conversion/explicit_conversion_error_to_bytes4.sol
  test/libsolidity/syntaxTests/conversion/explicit_conversion_event_to_bytes4.sol
  test/libsolidity/syntaxTests/conversion/explicit_conversion_from_error.sol
  test/libsolidity/syntaxTests/conversion/explicit_conversion_from_event.sol
Labels: external contribution :star:

#12580 External test for Chainlink
  .circleci/config.yml
  test/externalTests.sh
  test/externalTests/chainlink.sh
Labels: testing :hammer:

#12575 External test for Gnosis Protocol v2
  .circleci/config.yml
  test/externalTests.sh
  test/externalTests/gp2.sh
Labels: testing :hammer:

#13115 Fix comment position in the voting example
  docs/examples/voting.rst
Labels: external contribution :star:

#13117 Remove all-whitespace lines from docs.
  docs/examples/voting.rst
Labels: documentation :book:

#13140 Changed sed command in `zeppelin.sh` to match renamed test file in openzeppelin project.
  test/externalTests/zeppelin.sh
Labels: testing :hammer:

#13138 Operator precedence table shared between Cheatsheet and Operators
  docs/cheatsheet.rst
  docs/types/operator-precedence-table.rst
  docs/types/operators.rst
Labels: documentation :book:

#13141 Add documentation section about dangling references.
  docs/types/reference-types.rst
Labels: documentation :book:

#13152 Add warning comment to dangling references docs.
  docs/types/reference-types.rst
Labels: documentation :book:

#13154 Fix release regex and add Ubuntu Kinetic to PPA scripts
  scripts/deps-ppa/static_z3.sh
  scripts/release_ppa.sh
Labels: build system :building_construction:

#12166 Disallowed --metadata-literal, --model-checker-show-unproved, --model-checker-div-mod-no-slacks outside of compiler mode
  Changelog.md
  solc/CommandLineParser.cpp
  test/solc/CommandLineParser.cpp
Labels: external contribution :star:, takeover

#12976 Add simplification rules for `mod(mul(X, Y), A)` & `mod(add(X, Y), A)`
  Changelog.md
  libevmasm/RuleList.h
  test/formal/mod_add_to_addmod.py
  test/formal/mod_mul_to_mulmod.py
  test/formal/opcodes.py
  test/libyul/yulOptimizerTests/expressionSimplifier/combine_add_and_mod_constant.yul
  test/libyul/yulOptimizerTests/expressionSimplifier/combine_mul_and_mod_constant.yul
Labels: external contribution :star:

#13183 Add all path locations to the IdentifierPath ASTNode
  libsolidity/ast/AST.h
  libsolidity/ast/ASTJsonExporter.cpp
  libsolidity/ast/ASTJsonImporter.cpp
  libsolidity/parsing/Parser.cpp
  test/libsolidity/ASTJSON/assembly/slot_offset.json
  test/libsolidity/ASTJSON/assembly/slot_offset_parseOnly.json
  test/libsolidity/ASTJSON/base_constructor_call.json
  test/libsolidity/ASTJSON/base_constructor_call_parseOnly.json
  test/libsolidity/ASTJSON/contract_dep_order.json
  test/libsolidity/ASTJSON/contract_dep_order_parseOnly.json
  test/libsolidity/ASTJSON/enum_value_declaration.json
  test/libsolidity/ASTJSON/enum_value_declaration_parseOnly.json
  test/libsolidity/ASTJSON/fail_after_parsing_parseOnly.json
  test/libsolidity/ASTJSON/inheritance_specifier.json
  test/libsolidity/ASTJSON/inheritance_specifier_parseOnly.json
  test/libsolidity/ASTJSON/mappings.json
  test/libsolidity/ASTJSON/mappings_parseOnly.json
  test/libsolidity/ASTJSON/modifier_definition.json
  test/libsolidity/ASTJSON/modifier_definition_parseOnly.json
  test/libsolidity/ASTJSON/modifier_invocation.json
  test/libsolidity/ASTJSON/modifier_invocation_parseOnly.json
  test/libsolidity/ASTJSON/not_existing_import_parseOnly.json
  test/libsolidity/ASTJSON/override.json
  test/libsolidity/ASTJSON/override_parseOnly.json
  test/libsolidity/ASTJSON/two_base_functions.json
  test/libsolidity/ASTJSON/two_base_functions_parseOnly.json
  test/libsolidity/ASTJSON/userDefinedValueType.json
  test/libsolidity/ASTJSON/userDefinedValueType_parseOnly.json
  test/libsolidity/ASTJSON/using_for_directive.json
  test/libsolidity/ASTJSON/using_for_directive_parseOnly.json
Labels: language server

#13182 Add all path declarations in IdentifierPath annotation
  libsolidity/analysis/NameAndTypeResolver.cpp
  libsolidity/analysis/NameAndTypeResolver.h
  libsolidity/analysis/ReferencesResolver.cpp
  libsolidity/ast/ASTAnnotations.h
Labels: language server
