Repository argotorg/solidity, pull requests merged in 2022-02, with the labels that each got.

#12606 [docs] Correct type of address.code
  docs/types/value-types.rst
Labels: documentation :book:

#12611 Fix breakage in Bleeps and Perpetual Pools external tests
  .circleci/config.yml
  test/externalTests/bleeps.sh
  test/externalTests/elementfi.sh
  test/externalTests/perpetual-pools.sh
  test/externalTests/trident.sh
  test/externalTests/uniswap.sh
Labels: testing :hammer:

#12595 Update release checklist for new solc-js publish process
  ReleaseChecklist.md
Labels: has dependencies

#12624 Adjust solc-js installation to match the new release process
  scripts/bytecodecompare/storebytecode.sh
  scripts/solc-bin/bytecode_reports_for_modified_binaries.sh
  test/externalTests/colony.sh
  test/externalTests/gnosis-v2.sh
  test/externalTests/gnosis.sh
Labels: testing :hammer:

#12599 [DOCS] Adding a few resources to resources section
  docs/resources.rst
Labels: documentation :book:

#12629 Re-enable Bleeps external test without the failing governor test
  .circleci/config.yml
  test/externalTests/bleeps.sh
Labels: testing :hammer:

#12625 Docs: fix slot calculation for mappings of strings/byte arrays
  docs/internals/layout_in_storage.rst
Labels: documentation :book:, external contribution :star:

#12623 plain `address` can be sent Ether too
  docs/types/value-types.rst
Labels: documentation :book:, external contribution :star:

#12636 Fix signature of pop member
  docs/types/reference-types.rst
Labels: documentation :book:, external contribution :star:

#12633 Always run Hardhat on node.js 16
  .circleci/config.yml
Labels: testing :hammer:

#12632 Clarify symlink handling on Windows
  docs/contributing.rst
  test/FilesystemUtils.cpp
Labels: documentation :book:

#12642 Remove a reference to unused SolidityFixedFeeRegistrar (retry)
  test/boostTest.cpp
Labels: testing :hammer:, has dependencies

#11896 Simplifying CircleCi Config: Job aliases
  .circleci/config.yml
Labels: external contribution :star:, testing :hammer:, takeover

#12638 Note about storage compatibility mode
  docs/internals/layout_in_storage.rst
Labels: documentation :book:, external contribution :star:

#12594 solc-js external test on a local checkout
  test/externalTests/common.sh
  test/externalTests/solc-js/solc-js.sh
Labels: testing :hammer:

#12441 Benchmarking external tests
  .circleci/config.yml
  scripts/externalTests/merge_benchmarks.sh
  scripts/externalTests/parse_eth_gas_report.py
  scripts/externalTests/summarize_benchmarks.sh
  test/externalTests.sh
  test/externalTests/bleeps.sh
  test/externalTests/colony.sh
  test/externalTests/common.sh
  test/externalTests/elementfi.sh
  test/externalTests/ens.sh
  test/externalTests/euler.sh
  test/externalTests/gnosis-v2.sh
  test/externalTests/gnosis.sh
  test/externalTests/perpetual-pools.sh
  test/externalTests/pool-together.sh
  test/externalTests/prb-math.sh
  test/externalTests/trident.sh
  test/externalTests/uniswap.sh
  test/externalTests/yield-liquidator.sh
  test/externalTests/zeppelin.sh
  test/scripts/fixtures/eth_gas_report_gnosis.rst
  test/scripts/test_externalTests_parse_eth_gas_report.py
Labels: testing :hammer:

#12462 [docs] fix issue with delegating votes to wallets who cannot vote.
  docs/examples/voting.rst
Labels: documentation :book:, external contribution :star:

#12673 Bypass an expiration check in ElementFi until it's fixed upstream
  test/externalTests/elementfi.sh
Labels: testing :hammer:

#12678 Fix: remove lower_case_with_underscores and Capitalized_Words_With_Underscores
  docs/050-breaking-changes.rst
  docs/assembly.rst
  docs/contracts/functions.rst
  docs/style-guide.rst
  docs/types/mapping-types.rst
  docs/types/reference-types.rst
Labels: documentation :book:, external contribution :star:, style guide

#12698 fixed grammar on doc.
  docs/introduction-to-smart-contracts.rst
Labels: documentation :book:, external contribution :star:

#12701 Fix running path-related tests from any Windows drive
  libsolidity/interface/FileReader.cpp
  libsolidity/interface/FileReader.h
  test/libsolidity/interface/FileReader.cpp
  test/solc/CommandLineInterface.cpp
Labels: testing :hammer:

#12697 Revive wasm rebuild scripts
  scripts/bytecodecompare/storebytecode.sh
  scripts/wasm-rebuild/docker-scripts/rebuild_current.sh
  scripts/wasm-rebuild/docker-scripts/rebuild_tags.sh
Labels: solc-bin

#12689 Fix typos on doc
  docs/assembly.rst
  docs/contracts/using-for.rst
Labels: documentation :book:, external contribution :star:
