Repository argotorg/solidity, pull requests merged in 2022-10, with the labels that each got.

#13572 [Docs] Clarify relative path normalization rules
  docs/path-resolution.rst
Labels: documentation :book:

#13560 Updated Whiskers for checking invalid tags
  libsolutil/Whiskers.cpp
  libsolutil/Whiskers.h
  test/libsolutil/Whiskers.cpp
Labels: external contribution :star:

#13612 Clarify github issues vs forum posts in docs.
  docs/contributing.rst
Labels: documentation :book:

#13546 test copy_from_calldata.sol folder location update
  test/libsolidity/semanticTests/array/copying/calldata_1d_array_into_2d_memory_array_element.sol
Labels: external contribution :star:, testing :hammer:

#13593 Add test for selfdestruct
  test/libsolidity/SolidityEndToEndTest.cpp
  test/libsolidity/semanticTests/various/selfdestruct.sol
Labels: testing :hammer:

#13587 [Trivial] Forward declare Instruction enum in EVMVersion
  liblangutil/EVMVersion.cpp
  liblangutil/EVMVersion.h
  libyul/AsmAnalysis.cpp
  libyul/backends/evm/EVMCodeTransform.cpp
  libyul/backends/evm/OptimizedEVMCodeTransform.cpp
  libyul/optimiser/ReasoningBasedSimplifier.cpp
Labels: refactor

#13636 Rename command-line tests for the `--no-cbor-metadata`/`appendCBOR` option
  test/cmdlineTests/no_cbor_metadata/args
  test/cmdlineTests/no_cbor_metadata/input.sol
  test/cmdlineTests/no_cbor_metadata/output
  test/cmdlineTests/no_cbor_metadata_with_metadata_hash/args
  test/cmdlineTests/no_cbor_metadata_with_metadata_hash/err
  test/cmdlineTests/no_cbor_metadata_with_metadata_hash/exit
  test/cmdlineTests/no_cbor_metadata_with_metadata_hash/input.sol
  test/cmdlineTests/standard_no_append_cbor/args
  test/cmdlineTests/standard_no_append_cbor/input.json
  test/cmdlineTests/standard_no_append_cbor/output.json
  test/cmdlineTests/standard_no_append_cbor_with_metadata_hash/args
  test/cmdlineTests/standard_no_append_cbor_with_metadata_hash/input.json
  test/cmdlineTests/standard_no_append_cbor_with_metadata_hash/output.json
Labels: testing :hammer:

#13578 [libsolidity] Refactor Compiler Stack imported source type.
  libsolidity/interface/CompilerStack.cpp
  libsolidity/interface/CompilerStack.h
Labels: refactor

#13642 Increase euler external tests container size
  .circleci/config.yml
Labels: testing :hammer:

#13501 Document UnusedStoreEliminator
  docs/internals/optimizer.rst
  libyul/optimiser/UnusedStoreEliminator.h
Labels: documentation :book:, optimizer

#13644 test: Move hashing algorithm tests to semanticTests
  test/libsolidity/SolidityEndToEndTest.cpp
  test/libsolidity/semanticTests/builtinFunctions/keccak256.sol
  test/libsolidity/semanticTests/builtinFunctions/keccak256_packed.sol
  test/libsolidity/semanticTests/builtinFunctions/keccak256_packed_complex_types.sol
  test/libsolidity/semanticTests/builtinFunctions/ripemd160.sol
  test/libsolidity/semanticTests/builtinFunctions/ripemd160_packed.sol
  test/libsolidity/semanticTests/builtinFunctions/sha256.sol
  test/libsolidity/semanticTests/builtinFunctions/sha256_packed.sol
Labels: testing :hammer:

#13594 EVMHost: implement selfdestruct better
  test/EVMHost.cpp
  test/EVMHost.h
Labels: refactor

#13577 [solc] Refactor valid input modes.
  solc/CommandLineInterface.cpp
Labels: refactor

#13643 Fix gp2 ext test failing to build, not being able to resolve the the keyv dependency
  scripts/externalTests/update_external_repos.sh
  test/externalTests/gp2.sh
Labels: testing :hammer:

#13309 Fix misspelling in bug name in `bugs.json` (`NestedCallataArrayAbiReencodingSizeValidation`)
  docs/bugs.json
  docs/bugs_by_version.json
Labels: documentation :book:, external contribution :star:

#13609 Adds basic `textDocument/hover`
  Changelog.md
  libsolidity/CMakeLists.txt
  libsolidity/lsp/DocumentHoverHandler.cpp
  libsolidity/lsp/DocumentHoverHandler.h
  libsolidity/lsp/LanguageServer.cpp
  libsolidity/lsp/LanguageServer.h
  test/libsolidity/lsp/hover/hover.sol
Labels: language server

#13405 [libevmasm] Add Assembly::OptimiserSettings::translateSettings.
  libevmasm/Assembly.cpp
  libevmasm/Assembly.h
  libsolidity/codegen/CompilerContext.cpp
  libsolidity/codegen/CompilerContext.h
  libyul/YulStack.cpp
Labels: priority review

#13657 Update README.md to clarify how the docs are hosted
  README.md
Labels: documentation :book:, external contribution :star:

#13655 raised resource class of `t_ubu_ubsan_clang_cli` to medium
  .circleci/config.yml
Labels: testing :hammer:
