Repository argotorg/solidity, pull requests merged in 2022-03, with the labels that each got.

#12722 Ignore cex in SMT test
  test/libsolidity/smtCheckerTests/userTypes/multisource_module.sol
Labels: testing :hammer:

#12733 Workaround for a race condition in Perpetual Pools ext test due to parallel compilation on Hardhat 2.9.0
  test/externalTests/perpetual-pools.sh
Labels: testing :hammer:

#11842 [BREAKING] Revert commit and Make basefee a reserved identifier in 0.9.0
  Changelog.md
  docs/090-breaking-changes.rst
  libyul/backends/evm/EVMDialect.cpp
  scripts/error_codes.py
  test/libsolidity/syntaxTests/inlineAssembly/basefee_berlin_function.sol
  test/libsolidity/syntaxTests/types/magic_block_basefee_error.sol
Labels: breaking change :warning:, external contribution :star:, takeover

#12659 Add Base64 test cases with and without inline assembly
  test/libsolidity/semanticTests/externalContracts/_base64/base64_inline_asm.sol
  test/libsolidity/semanticTests/externalContracts/_base64/base64_no_inline_asm.sol
  test/libsolidity/semanticTests/externalContracts/base64.sol
Labels: external contribution :star:, testing :hammer:

#12764 Disable flaky ElementFi tests in `mockERC20YearnVaultTest`
  test/externalTests/elementfi.sh
Labels: testing :hammer:

#12195 Run GnosisSafe external tests with Hardhat and directly on upstream
  .circleci/config.yml
  test/externalTests.sh
  test/externalTests/gnosis-v2.sh
  test/externalTests/gnosis.sh
Labels: testing :hammer:

#12763 doc: improve explanation of interfaces
  docs/contracts/interfaces.rst
Labels: documentation :book:, external contribution :star:

#12765 Increase Hardhat timeout in Euler ext test
  test/externalTests/common.sh
  test/externalTests/euler.sh
Labels: testing :hammer:

#12768 Euler timeout fix: switch to TEST_TIMEOUT variable
  test/externalTests/euler.sh
Labels: testing :hammer:

#12746 Remove use of `using namespace` in header file
  libsolidity/analysis/ControlFlowAnalyzer.cpp
  libsolidity/analysis/ControlFlowRevertPruner.cpp
  libsolidity/analysis/FunctionCallGraph.cpp
  libsolidity/analysis/PostTypeChecker.cpp
  libsolidity/analysis/PostTypeContractLevelChecker.cpp
  libsolidity/analysis/TypeChecker.cpp
  libsolidity/ast/AST.cpp
  libsolidity/ast/ASTAnnotations.h
  libsolidity/ast/ASTJsonConverter.cpp
  libsolidity/codegen/CompilerContext.cpp
  libsolidity/codegen/ContractCompiler.cpp
  libsolidity/codegen/ExpressionCompiler.cpp
  libsolidity/codegen/LValue.cpp
  libsolidity/codegen/ir/IRGenerator.cpp
  libsolidity/formal/CHC.cpp
  libsolidity/formal/Invariants.cpp
  libsolidity/formal/Predicate.cpp
  libsolidity/formal/SMTEncoder.cpp
  libsolidity/formal/SymbolicState.cpp
  libsolidity/formal/SymbolicTypes.cpp
  libsolidity/interface/CompilerStack.cpp
  libsolidity/lsp/LanguageServer.cpp
  libsolidity/lsp/Transport.h
  libsolutil/IpfsHash.cpp
  libyul/Object.cpp
  libyul/optimiser/DataFlowAnalyzer.cpp
  libyul/optimiser/EqualStoreEliminator.cpp
  solc/CommandLineInterface.cpp
  solc/CommandLineParser.cpp
  test/CommonSyntaxTest.cpp
  test/libsolidity/SemanticTest.cpp
  test/libsolidity/SolidityEndToEndTest.cpp
  test/libsolidity/SolidityExpressionCompiler.cpp
  test/libsolidity/SolidityOptimizer.cpp
  test/libsolidity/analysis/FunctionCallGraph.cpp
  test/libsolidity/util/BytesUtils.cpp
  test/libsolidity/util/TestFileParser.cpp
  test/libsolidity/util/TestFunctionCall.cpp
  test/solc/CommandLineInterface.cpp
Labels: external contribution :star:

#12736 Re-enable running tests via IR in external tests in cases where they don't pass due to Hardhat heuristics
  test/externalTests/elementfi.sh
  test/externalTests/gnosis.sh
  test/externalTests/prb-math.sh
  test/externalTests/zeppelin.sh
Labels: testing :hammer:

#12708 Document behaviour of ternary operator of literals.
  docs/types/operators.rst
  docs/types/value-types.rst
  test/libsolidity/semanticTests/literals/ternary_operator_with_literal_types_overflow.sol
  test/libsolidity/syntaxTests/literals/ternary_operator_return_type_with_literal_arguments.sol
Labels: documentation :book:

#12430 LSP goto definition
  Changelog.md
  libsolidity/CMakeLists.txt
  libsolidity/ast/ASTUtils.cpp
  libsolidity/ast/ASTUtils.h
  libsolidity/lsp/GotoDefinition.cpp
  libsolidity/lsp/GotoDefinition.h
  libsolidity/lsp/HandlerBase.cpp
  libsolidity/lsp/HandlerBase.h
  libsolidity/lsp/LanguageServer.cpp
  libsolidity/lsp/LanguageServer.h
  libsolidity/lsp/Utils.cpp
  libsolidity/lsp/Utils.h
  test/libsolidity/lsp/goto_definition.sol
  test/libsolidity/lsp/goto_definition_imports.sol
  test/libsolidity/lsp/lib.sol
  test/lsp.py
Labels: language server

#12696 Fix unreliable ASTJson tests
  test/libsolidity/ASTJSON/address_payable.json
  test/libsolidity/ASTJSON/address_payable.sol
  test/libsolidity/ASTJSON/address_payable_parseOnly.json
  test/libsolidity/ASTJSON/assembly/nested_functions.json
  test/libsolidity/ASTJSON/assembly/nested_functions.sol
  test/libsolidity/ASTJSON/assembly/nested_functions_parseOnly.json
  test/libsolidity/ASTJSON/assembly/switch.json
  test/libsolidity/ASTJSON/assembly/switch.sol
  test/libsolidity/ASTJSON/assembly/switch_parseOnly.json
  test/libsolidity/ASTJSON/event_with_variables_of_internal_types.json
  test/libsolidity/ASTJSON/fail_after_parsing.sol
  test/libsolidity/ASTJSON/fail_after_parsing_parseOnly.json
  test/libsolidity/ASTJSON/function_type.json
  test/libsolidity/ASTJSON/function_type.sol
  test/libsolidity/ASTJSON/function_type_parseOnly.json
  test/libsolidity/ASTJSON/non_utf8.json
  test/libsolidity/ASTJSON/non_utf8.sol
  test/libsolidity/ASTJSON/non_utf8_parseOnly.json
  test/libsolidity/ASTJSON/not_existing_import.json
  test/libsolidity/ASTJSON/not_existing_import.sol
  test/libsolidity/ASTJSON/source_location.json
  test/libsolidity/ASTJSON/source_location.sol
  test/libsolidity/ASTJSON/source_location_parseOnly.json
  test/libsolidity/ASTJSON/used_errors.json
  test/libsolidity/ASTJSON/used_errors.sol
  test/libsolidity/ASTJSON/used_errors_parseOnly.json
  test/libsolidity/ASTJSONTest.cpp
  test/libsolidity/ASTJSONTest.h
Labels: testing :hammer:

#12288 Using global
  Changelog.md
  docs/contracts/using-for.rst
  docs/grammar/SolidityLexer.g4
  docs/grammar/SolidityParser.g4
  libsolidity/analysis/SyntaxChecker.cpp
  libsolidity/analysis/TypeChecker.cpp
  libsolidity/ast/AST.h
  libsolidity/ast/ASTJsonConverter.cpp
  libsolidity/ast/ASTJsonImporter.cpp
  libsolidity/ast/Types.cpp
  libsolidity/parsing/Parser.cpp
  test/libsolidity/ASTJSON/using_for_directive.json
  test/libsolidity/ASTJSON/using_for_directive_parseOnly.json
  test/libsolidity/semanticTests/using/recursive_import.sol
  test/libsolidity/semanticTests/using/using_global_for_global.sol
  test/libsolidity/semanticTests/using/using_global_invisible.sol
  test/libsolidity/semanticTests/using/using_global_library.sol
  test/libsolidity/syntaxTests/using/global_and_local.sol
  test/libsolidity/syntaxTests/using/global_for_asterisk.sol
  test/libsolidity/syntaxTests/using/global_for_non_user_defined.sol
  test/libsolidity/syntaxTests/using/global_for_type_defined_elsewhere.sol
  test/libsolidity/syntaxTests/using/global_for_type_from_other_file.sol
  test/libsolidity/syntaxTests/using/global_inside_contract.sol
  test/libsolidity/syntaxTests/using/global_local_clash.sol
  test/libsolidity/syntaxTests/using/global_nonglobal.sol
  test/libsolidity/syntaxTests/using/global_working.sol
Labels: has dependencies

#12680 fix: corrects _ prefixes
  docs/assembly.rst
  docs/common-patterns.rst
  docs/contracts/constant-state-variables.rst
  docs/contracts/creating-contracts.rst
  docs/contracts/events.rst
  docs/contracts/function-modifiers.rst
  docs/contracts/functions.rst
  docs/contracts/inheritance.rst
  docs/contracts/libraries.rst
  docs/contracts/using-for.rst
  docs/introduction-to-smart-contracts.rst
  docs/ir-breaking-changes.rst
  docs/security-considerations.rst
  docs/smtchecker.rst
  docs/types/mapping-types.rst
  docs/types/reference-types.rst
Labels: documentation :book:, external contribution :star:, style guide

#12773 Fix encodeCall bug.
  Changelog.md
  docs/bugs.json
  docs/bugs_by_version.json
  libsolidity/codegen/ExpressionCompiler.cpp
  libsolidity/codegen/ir/IRGeneratorForStatements.cpp
  test/libsolidity/semanticTests/abiencodedecode/abi_encode_call_uint_bytes.sol
Labels: takeover

#12724 Implement & use markers in existing test framework
  test/libsolidity/lsp/didOpen_with_import.sol
  test/libsolidity/lsp/lib.sol
  test/libsolidity/lsp/publish_diagnostics_1.sol
  test/libsolidity/lsp/publish_diagnostics_2.sol
  test/libsolidity/lsp/publish_diagnostics_3.sol
  test/lsp.py
Labels: language server

#12839 lsp.py: Adds --fail-fast (-f) to terminate early on first failure.
  test/lsp.py
Labels: language server

#12874 Fix broken `${}` syntax in `externalTests.sh`
  test/externalTests.sh
Labels: testing :hammer:
