Repository argotorg/solidity, pull requests merged in 2022-01, with the labels that each got.

#12477 Added specificity to data location.
  docs/types/reference-types.rst
Labels: external contribution :star:

#12436 Test batcher.
  .circleci/config.yml
  .circleci/soltest.sh
  .circleci/soltest_all.sh
  test/Common.cpp
  test/Common.h
  test/boostTest.cpp
  test/tools/isoltest.cpp
Labels: testing :hammer:

#12276 Yul interpreter: Changes required before merging Redundant store eliminator
  test/libyul/EwasmTranslationTest.cpp
  test/libyul/YulInterpreterTest.cpp
  test/tools/ossfuzz/strictasm_diff_ossfuzz.cpp
  test/tools/ossfuzz/yulFuzzerCommon.cpp
  test/tools/ossfuzz/yulFuzzerCommon.h
  test/tools/ossfuzz/yulProto_diff_ossfuzz.cpp
  test/tools/yulInterpreter/EVMInstructionInterpreter.cpp
  test/tools/yulInterpreter/EVMInstructionInterpreter.h
  test/tools/yulInterpreter/Interpreter.cpp
  test/tools/yulInterpreter/Interpreter.h
  test/tools/yulrun.cpp
Labels: testing :hammer:, optimizer

#12272 Equal store eliminator.
  Changelog.md
  docs/internals/optimizer.rst
  libsolidity/interface/OptimiserSettings.h
  libyul/CMakeLists.txt
  libyul/optimiser/EqualStoreEliminator.cpp
  libyul/optimiser/EqualStoreEliminator.h
  libyul/optimiser/OptimizerUtilities.cpp
  libyul/optimiser/OptimizerUtilities.h
  libyul/optimiser/Suite.cpp
  libyul/optimiser/UnusedAssignEliminator.cpp
  libyul/optimiser/UnusedStoreBase.cpp
  libyul/optimiser/UnusedStoreBase.h
  test/libsolidity/semanticTests/externalContracts/deposit_contract.sol
  test/libsolidity/semanticTests/functionCall/mapping_array_internal_argument.sol
  test/libsolidity/semanticTests/structs/struct_copy.sol
  test/libyul/YulOptimizerTestCommon.cpp
  test/libyul/yulOptimizerTests/equalStoreEliminator/branching.yul
  test/libyul/yulOptimizerTests/equalStoreEliminator/forloop.yul
  test/libyul/yulOptimizerTests/equalStoreEliminator/functionbody.yul
  test/libyul/yulOptimizerTests/equalStoreEliminator/indirect_inferrence.yul
  test/libyul/yulOptimizerTests/equalStoreEliminator/mstore_with_keccak.yul
  test/libyul/yulOptimizerTests/equalStoreEliminator/value_change.yul
  test/libyul/yulOptimizerTests/equalStoreEliminator/verbatim.yul
  test/libyul/yulOptimizerTests/fullSuite/stack_compressor_msize.yul
  test/libyul/yulOptimizerTests/fullSuite/unusedFunctionParameterPruner_loop.yul
  test/libyul/yulOptimizerTests/fullSuite/unusedFunctionParameterPruner_simple.yul
  test/yulPhaser/Chromosome.cpp
Labels: optimizer

#12197 External tests for sushiswap/trident
  .circleci/config.yml
  test/externalTests.sh
  test/externalTests/common.sh
  test/externalTests/trident.sh
Labels: testing :hammer:

#12510 Parallel run number in gitter CI notifcations
  .circleci/config.yml
Labels: testing :hammer:

#12509 Pin Trident external test to a specific commit to work around failing tests on master
  test/externalTests/colony.sh
  test/externalTests/common.sh
  test/externalTests/ens.sh
  test/externalTests/gnosis-v2.sh
  test/externalTests/gnosis.sh
  test/externalTests/trident.sh
  test/externalTests/zeppelin.sh
Labels: testing :hammer:

#12440 Preset selection in external tests
  test/externalTests/colony.sh
  test/externalTests/common.sh
  test/externalTests/ens.sh
  test/externalTests/gnosis-v2.sh
  test/externalTests/gnosis.sh
  test/externalTests/zeppelin.sh
Labels: testing :hammer:

#12512 Fix preset selection in Trident external test
  test/externalTests/trident.sh
Labels: testing :hammer:

#12511 Deterministic test order in Trident external test
  test/externalTests/trident.sh
Labels: testing :hammer:

#12530 External test for Yield Protocol Liquidator v2
  .circleci/config.yml
  test/externalTests.sh
  test/externalTests/yield-liquidator.sh
Labels: testing :hammer:

#12536 [CI] Use `large` resource class for macOS and use `-j` without spaces
  .circleci/config.yml
Labels: testing :hammer:

#12531 External test for Bleeps
  .circleci/config.yml
  test/externalTests.sh
  test/externalTests/bleeps.sh
Labels: testing :hammer:

#12452 [CI] Templates for parameterized jobs
  .circleci/config.yml
Labels: testing :hammer:

#12560 External test for PoolTogether v4
  .circleci/config.yml
  test/externalTests.sh
  test/externalTests/pool-together.sh
Labels: testing :hammer:

#12561 External test for Tracer Perpetual Pools
  .circleci/config.yml
  test/externalTests.sh
  test/externalTests/common.sh
  test/externalTests/perpetual-pools.sh
Labels: testing :hammer:

#12532 External test for Uniswap v3
  .circleci/config.yml
  test/externalTests.sh
  test/externalTests/common.sh
  test/externalTests/uniswap.sh
Labels: testing :hammer:

#12542 External test for PRBMath
  .circleci/config.yml
  test/externalTests.sh
  test/externalTests/prb-math.sh
Labels: testing :hammer:

#12574 External test for ElementFi
  .circleci/config.yml
  test/externalTests.sh
  test/externalTests/elementfi.sh
Labels: testing :hammer:

#12582 Switch from `solcjs` to `solc.js` in external tests
  scripts/solc-bin/bytecode_reports_for_modified_binaries.sh
  test/externalTests/common.sh
Labels: testing :hammer:

#12583 Compatibility fixes for solc-js TypeScript migration
  Changelog.md
  ReleaseChecklist.md
  scripts/bytecodecompare/prepare_report.js
  scripts/bytecodecompare/storebytecode.sh
  scripts/solc-bin/bytecode_reports_for_modified_binaries.sh
  scripts/wasm-rebuild/docker-scripts/rebuild_tags.sh
  test/externalTests/common.sh
Labels: testing :hammer:

#12491 Write down version policy
  docs/installing-solidity.rst
Labels: documentation :book:, external contribution :star:

#12592 Add blank line to make it consistency
  docs/style-guide.rst
Labels: documentation :book:, external contribution :star:

#11999 [docs] Separate "Visibility and getters" section for state variables and functions
  docs/contracts/visibility-and-getters.rst
Labels: documentation :book:, external contribution :star:

#12261 [BREAKING] Disallow codecopy and codesize in pure functions.
  Changelog.md
  docs/contracts/functions.rst
  libevmasm/SemanticInformation.cpp
  test/libsolidity/syntaxTests/inlineAssembly/hex_switch_case.sol
  test/libsolidity/syntaxTests/inlineAssembly/string_literal_switch_case.sol
  test/libsolidity/syntaxTests/viewPureChecker/assembly.sol
Labels: breaking change :warning:

#12608 Patch ElementFi external test on for disallowed `delete` on `breaking`
  test/externalTests/elementfi.sh
Labels: testing :hammer:
