Repository argotorg/solidity, pull requests merged in 2022-09, with the labels that each got.

#13465 README.md: added comma
  README.md
Labels: documentation :book:, external contribution :star:

#13460 Set CMake policy `CMP0115` to `NEW`: "Source file extensions must be explicit"
  cmake/EthPolicy.cmake
Labels: build system :building_construction:, external contribution :star:

#13481 Fix compiler version check in hardhat artifacts json
  test/externalTests/common.sh
  test/externalTests/zeppelin.sh
Labels: priority review

#13363 Release checklist update and tweaks after 0.8.16
  ReleaseChecklist.md
Labels: documentation :book:, priority review

#13463 Grammar fix
  docs/types/value-types.rst
Labels: documentation :book:, external contribution :star:

#13489 Pin hardhat version in yield-liquidator tests
  test/externalTests/yield-liquidator.sh
Labels: testing :hammer:

#13474 Add note about peephole optimizer in docs
  docs/internals/optimizer.rst
Labels: documentation :book:

#13479 Fix of unused store remover storage bug.
  Changelog.md
  docs/bugs.json
  docs/bugs_by_version.json
  libyul/optimiser/UnusedStoreEliminator.cpp
  test/libsolidity/semanticTests/unused_store_storage_removal_bug.sol
  test/libyul/yulOptimizerTests/unusedStoreEliminator/store_before_conditionally_terminating_function_call.yul
  test/libyul/yulOptimizerTests/unusedStoreEliminator/store_before_conditionally_terminating_function_call_complex_control_flow.yul
  test/libyul/yulOptimizerTests/unusedStoreEliminator/store_before_conditionally_terminating_function_call_revert.yul
  test/libyul/yulOptimizerTests/unusedStoreEliminator/store_before_indirectly_conditionally_terminating_function_call.yul
  test/libyul/yulOptimizerTests/unusedStoreEliminator/store_before_unconditionally_terminating_function_call.yul
Labels: bug :bug:, optimizer

#13509 Update PPA instructions for Z3 in checklist
  ReleaseChecklist.md
Labels: documentation :book:

#13510 Release checklist: recommend checking if all PRs have changelog entries
  ReleaseChecklist.md
Labels: documentation :book:

#13500 Fix dynamic array spec
  docs/abi-spec.rst
Labels: documentation :book:, external contribution :star:

#13498 Update ReleaseChecklist.md
  ReleaseChecklist.md
Labels: documentation :book:, external contribution :star:

#13376 Make hardcoded parts of the optimizer sequence configurable
  Changelog.md
  docs/internals/optimizer.rst
  docs/yul.rst
  libsolidity/codegen/CompilerContext.cpp
  libsolidity/interface/CompilerStack.cpp
  libsolidity/interface/OptimiserSettings.h
  libsolidity/interface/StandardCompiler.cpp
  libyul/YulStack.cpp
  libyul/optimiser/Suite.cpp
  libyul/optimiser/Suite.h
  solc/CommandLineParser.cpp
  test/cmdlineTests/standard_optimizer_yulDetails_optimiserSteps_invalid_nested_delimiter/args
  test/cmdlineTests/standard_optimizer_yulDetails_optimiserSteps_invalid_nested_delimiter/in.sol
  test/cmdlineTests/standard_optimizer_yulDetails_optimiserSteps_invalid_nested_delimiter/input.json
  test/cmdlineTests/standard_optimizer_yulDetails_optimiserSteps_invalid_nested_delimiter/output.json
  test/cmdlineTests/standard_optimizer_yulDetails_optimiserSteps_mutliple_delimiters/args
  test/cmdlineTests/standard_optimizer_yulDetails_optimiserSteps_mutliple_delimiters/in.sol
  test/cmdlineTests/standard_optimizer_yulDetails_optimiserSteps_mutliple_delimiters/input.json
  test/cmdlineTests/standard_optimizer_yulDetails_optimiserSteps_mutliple_delimiters/output.json
  test/cmdlineTests/standard_optimizer_yulDetails_optimiserSteps_with_cleanup_sequence/args
  test/cmdlineTests/standard_optimizer_yulDetails_optimiserSteps_with_cleanup_sequence/in.sol
  test/cmdlineTests/standard_optimizer_yulDetails_optimiserSteps_with_cleanup_sequence/input.json
  test/cmdlineTests/standard_optimizer_yulDetails_optimiserSteps_with_cleanup_sequence/output.json
  test/cmdlineTests/standard_optimizer_yulDetails_optimiserSteps_with_empty_cleanup_sequence/args
  test/cmdlineTests/standard_optimizer_yulDetails_optimiserSteps_with_empty_cleanup_sequence/in.sol
  test/cmdlineTests/standard_optimizer_yulDetails_optimiserSteps_with_empty_cleanup_sequence/input.json
  test/cmdlineTests/standard_optimizer_yulDetails_optimiserSteps_with_empty_cleanup_sequence/output.json
  test/cmdlineTests/standard_optimizer_yulDetails_optimiserSteps_with_empty_optimisation_sequence/args
  test/cmdlineTests/standard_optimizer_yulDetails_optimiserSteps_with_empty_optimisation_sequence/in.sol
  test/cmdlineTests/standard_optimizer_yulDetails_optimiserSteps_with_empty_optimisation_sequence/input.json
  test/cmdlineTests/standard_optimizer_yulDetails_optimiserSteps_with_empty_optimisation_sequence/output.json
  test/cmdlineTests/standard_optimizer_yulDetails_optimiserSteps_with_empty_sequence/args
  test/cmdlineTests/standard_optimizer_yulDetails_optimiserSteps_with_empty_sequence/in.sol
  test/cmdlineTests/standard_optimizer_yulDetails_optimiserSteps_with_empty_sequence/input.json
  test/cmdlineTests/standard_optimizer_yulDetails_optimiserSteps_with_empty_sequence/output.json
  test/cmdlineTests/yul_optimizer_steps_short_sequence/args
  test/cmdlineTests/yul_optimizer_steps_short_sequence/input.sol
  test/cmdlineTests/yul_optimizer_steps_short_sequence/output
  test/cmdlineTests/yul_optimizer_steps_with_empty_cleanup_sequence/args
  test/cmdlineTests/yul_optimizer_steps_with_empty_cleanup_sequence/input.sol
  test/cmdlineTests/yul_optimizer_steps_with_empty_cleanup_sequence/output
  test/cmdlineTests/yul_optimizer_steps_with_empty_optimization_sequence/args
  test/cmdlineTests/yul_optimizer_steps_with_empty_optimization_sequence/input.sol
  test/cmdlineTests/yul_optimizer_steps_with_empty_optimization_sequence/output
  test/libsolidity/Metadata.cpp
  test/libsolidity/StandardCompiler.cpp
  test/libyul/YulOptimizerTestCommon.cpp
  test/solc/CommandLineParser.cpp
Labels: optimizer

#13524 Remove std qualifier from string in Metadata tests
  test/libsolidity/Metadata.cpp
Labels: refactor

#13464 Add tests for copying reference types between data locations
  test/libsolidity/semanticTests/array/copying/array_elements_to_mapping.sol
  test/libsolidity/semanticTests/array/copying/array_nested_storage_to_memory.sol
  test/libsolidity/semanticTests/array/copying/array_to_mapping.sol
  test/libsolidity/semanticTests/array/copying/calldata_array_to_mapping.sol
  test/libsolidity/semanticTests/array/copying/elements_of_nested_array_of_structs_calldata_to_storage.sol
  test/libsolidity/semanticTests/array/copying/elements_of_nested_array_of_structs_memory_to_storage.sol
  test/libsolidity/semanticTests/array/copying/nested_array_element_calldata_to_memory.sol
  test/libsolidity/semanticTests/array/copying/nested_array_element_calldata_to_storage.sol
  test/libsolidity/semanticTests/array/copying/nested_array_element_memory_to_memory.sol
  test/libsolidity/semanticTests/array/copying/nested_array_element_memory_to_storage.sol
  test/libsolidity/semanticTests/array/copying/nested_array_element_storage_to_memory.sol
  test/libsolidity/semanticTests/array/copying/nested_array_element_storage_to_storage.sol
  test/libsolidity/semanticTests/array/copying/nested_array_of_structs_calldata_to_memory.sol
  test/libsolidity/semanticTests/array/copying/nested_array_of_structs_calldata_to_storage.sol
  test/libsolidity/semanticTests/array/copying/nested_array_of_structs_memory_to_memory.sol
  test/libsolidity/semanticTests/array/copying/nested_array_of_structs_memory_to_storage.sol
  test/libsolidity/semanticTests/array/copying/nested_array_of_structs_storage_to_storage.sol
  test/libsolidity/semanticTests/array/copying/nested_array_of_structs_with_nested_array_from_storage_to_memory.sol
  test/libsolidity/semanticTests/array/copying/nested_dynamic_array_element_calldata_to_storage.sol
  test/libsolidity/semanticTests/structs/copy_from_mapping.sol
  test/libsolidity/semanticTests/structs/copy_struct_with_nested_array_from_calldata_to_memory.sol
  test/libsolidity/semanticTests/structs/copy_struct_with_nested_array_from_calldata_to_storage.sol
  test/libsolidity/semanticTests/structs/copy_struct_with_nested_array_from_memory_to_memory.sol
  test/libsolidity/semanticTests/structs/copy_struct_with_nested_array_from_storage_to_storage.sol
  test/libsolidity/semanticTests/structs/copy_substructures_from_mapping.sol
  test/libsolidity/semanticTests/structs/copy_substructures_to_mapping.sol
  test/libsolidity/semanticTests/structs/copy_to_mapping.sol
  test/libsolidity/semanticTests/types/mapping/copy_from_mapping_to_mapping.sol
  test/libsolidity/semanticTests/types/mapping/copy_struct_to_array_stored_in_mapping.sol
Labels: testing :hammer:

#13542 Fix Euler tests by pinning v3-periphery
  test/externalTests/euler.sh
Labels: testing :hammer:

#13162 cleaning up helpers around errors
  liblangutil/Exceptions.cpp
  liblangutil/Exceptions.h
  liblangutil/SourceReferenceExtractor.cpp
  liblangutil/SourceReferenceExtractor.h
  liblangutil/SourceReferenceFormatter.cpp
  liblangutil/SourceReferenceFormatter.h
  libsolidity/interface/StandardCompiler.cpp
  libsolidity/lsp/LanguageServer.cpp
  solc/CommandLineInterface.cpp
  test/cmdlineTests/standard_urls_existing_and_missing/contract.sol
  test/cmdlineTests/standard_urls_existing_and_missing/input.json
  test/cmdlineTests/standard_urls_existing_and_missing/output.json
  test/cmdlineTests/standard_urls_missing/contract.sol
  test/cmdlineTests/standard_urls_missing/input.json
  test/cmdlineTests/standard_urls_missing/output.json
  test/libsolidity/ErrorCheck.cpp
  test/libsolidity/SyntaxTest.cpp
  test/libyul/SyntaxTest.cpp
  test/tools/ossfuzz/yulProto_diff_ossfuzz.cpp
Labels: priority review

#13549 Fix stripping in CLI tests does not produce correct JSON formatting
  test/cmdlineTests.sh
  test/cmdlineTests/standard_urls_existing_and_missing/args
  test/cmdlineTests/standard_urls_existing_and_missing/output.json
  test/cmdlineTests/standard_urls_missing/args
  test/cmdlineTests/standard_urls_missing/output.json
Labels: external contribution :star:

#13548 Add v0.6.0 change notes for inline assembly opcode syntax changes.
  docs/060-breaking-changes.rst
Labels: documentation :book:, external contribution :star:

#13540 renames lspAssert() to lspRequire + documentation
  libsolidity/lsp/FileRepository.cpp
  libsolidity/lsp/LanguageServer.cpp
  libsolidity/lsp/Transport.h
Labels: language server

#13556 Update ambiguous CVC4::BitVector ctor call
  libsmtutil/CVC4Interface.cpp
Labels: external contribution :star:

#13580 Fix: improve docs typos & phrasing
  docs/examples/blind-auction.rst
  docs/examples/micropayment.rst
Labels: documentation :book:, external contribution :star:

#13568 [Docs] Contributing: Update meeting link to meet.soliditylang.org
  docs/contributing.rst
Labels: documentation :book:
