Repository argotorg/solidity, pull requests merged in 2022-05, with the labels that each got.

#12956 Add a require statement to the Ballot contract
  docs/examples/voting.rst
Labels: documentation :book:, external contribution :star:

#12468 Always allow full filesystem access to LSP.
  .circleci/config.yml
  Changelog.md
  libsolidity/CMakeLists.txt
  libsolidity/lsp/FileRepository.cpp
  libsolidity/lsp/FileRepository.h
  libsolidity/lsp/HandlerBase.cpp
  libsolidity/lsp/LanguageServer.cpp
  libsolidity/lsp/LanguageServer.h
  libsolidity/lsp/Transport.cpp
  libsolidity/lsp/Transport.h
  libsolidity/lsp/Utils.cpp
  libsolidity/lsp/Utils.h
  solc/CommandLineInterface.cpp
  test/lsp.py
Labels: language server

#12999 Disable non-deterministic counterexamples in some SMT tests
  test/libsolidity/smtCheckerTests/blockchain_state/balance_receive_4.sol
  test/libsolidity/smtCheckerTests/userTypes/conversion_4.sol
Labels: testing :hammer:

#13020 Workaround for `getStorageAt()` bug in Hardhat 2.9.5 for gnosis external test
  test/externalTests/gnosis.sh
Labels: testing :hammer:

#13027 Workaround for problems caused by forcing ethers@5.6.1 in external tests
  test/externalTests/gnosis.sh
  test/externalTests/perpetual-pools.sh
Labels: testing :hammer:

#12993 LSP: Implement semantic token requests
  Changelog.md
  libsolidity/CMakeLists.txt
  libsolidity/lsp/LanguageServer.cpp
  libsolidity/lsp/LanguageServer.h
  libsolidity/lsp/SemanticTokensBuilder.cpp
  libsolidity/lsp/SemanticTokensBuilder.h
  test/libsolidity/lsp/semanticTokens/enums.sol
  test/libsolidity/lsp/semanticTokens/functions.sol
  test/libsolidity/lsp/semanticTokens/modifiers.sol
  test/libsolidity/lsp/semanticTokens/structs.sol
  test/lsp.py
Labels: language server

#12831 CSE optimization
  libevmasm/CommonSubexpressionEliminator.h
  libevmasm/ExpressionClasses.cpp
  libevmasm/ExpressionClasses.h
Labels: performance :racehorse:, optimizer

#12929 [CI] Automate preparation of release binaries for publishing (via workspace)
  .circleci/config.yml
  ReleaseChecklist.md
Labels: testing :hammer:

#12938 Script for keeping main branches of external test repos in sync with upstream
  scripts/externalTests/update_external_repos.sh
Labels: testing :hammer:

#13024 Remove notes section from Cheatsheet
  docs/cheatsheet.rst
Labels: documentation :book:, external contribution :star:

#13010 Re-enable the optimized IR preset in all external tests
  test/externalTests/euler.sh
  test/externalTests/perpetual-pools.sh
  test/externalTests/uniswap.sh
Labels: testing :hammer:

#12818 Benchmark downloader (script + CI job)
  .circleci/config.yml
  scripts/common/git_helpers.py
  scripts/common/rest_api_helpers.py
  scripts/externalTests/download_benchmarks.py
  test/scripts/test_externalTests_benchmark_downloader.py
Labels: testing :hammer:

#13061 expect -> except in docs/contributing.rst
  docs/contributing.rst
Labels: documentation :book:, external contribution :star:

#13063 External test workarounds for Gnosis and Euler external test failures
  test/externalTests/ens.sh
  test/externalTests/euler.sh
  test/externalTests/gnosis.sh
Labels: testing :hammer:

#13067 Disable more zeppelin test cases in which Hardhat's heuristics break after relaxing inlining.
  test/externalTests/zeppelin.sh
Labels: testing :hammer:

#13048 Move operator precedence from cheatsheet to operators
  docs/cheatsheet.rst
  docs/types/operators.rst
Labels: documentation :book:, external contribution :star:

#13072 Added option to allow soltest in CI print errors to stderr in addition to the XML report.
  .circleci/soltest.ps1
  .circleci/soltest.sh
Labels: testing :hammer:

#13084 Revert workaround introduced in euler tests because it is no longer needed
  test/externalTests/euler.sh
Labels: testing :hammer:

#13076 Updated broken link for Yul optimizations
  docs/internals/optimizer.rst
  docs/yul.rst
Labels: documentation :book:, external contribution :star:
