Repository argotorg/solidity, pull requests merged in 2022-11, with the labels that each got.

#13669 Remove the mention of RadSpec
  docs/natspec-format.rst
Labels: documentation :book:

#13668 [DOCS] Translations: Updated links and adding new language repos
  docs/contributing.rst
  docs/index.rst
Labels: documentation :book:

#13666 [Documentation] Change text to be hyperlink
  docs/contributing.rst
Labels: documentation :book:, external contribution :star:

#13419 Update misleading information about OpenZeppelin's ECDSA library
  docs/units-and-global-variables.rst
Labels: documentation :book:, external contribution :star:

#13569 Document legacy and IR behavior for call to zero initialized variable of function type
  test/libsolidity/semanticTests/functionTypes/call_to_zero_initialized_function_type_ir.sol
  test/libsolidity/semanticTests/functionTypes/call_to_zero_initialized_function_type_legacy.sol
Labels: testing :hammer:, stale

#13579 [libsolutil] Add new JSON helper functions.
  libsolutil/JSON.h
  test/libsolutil/JSON.cpp
Labels: refactor

#13068 CI config tweaks after CircleCI review
  .circleci/config.yml
  .circleci/soltest.sh
  scripts/bytecodecompare/storebytecode.sh
  scripts/solc-bin/bytecode_reports_for_modified_binaries.sh
Labels: testing :hammer:

#13676 Fix grammar mistake
  ReleaseChecklist.md
Labels: external contribution :star:

#13675 Peg hardhat-tenderly to fix GP2 external tests
  test/externalTests/gp2.sh
Labels: testing :hammer:

#13685 Call Graph and AST naming corrections
  libsolidity/ast/AST.h
  libsolidity/ast/AST_accept.h
  test/libsolidity/analysis/FunctionCallGraph.cpp
  test/libsolidity/syntaxTests/controlFlow/localStorageVariables/ternary_assignment_fine.sol
Labels: refactor

#13391 Add Natspec devdoc inheritance support for events
  Changelog.md
  libsolidity/interface/Natspec.cpp
  test/libsolidity/SolidityNatspecJSON.cpp
Labels: external contribution :star:

#13631 Clarify that a contract without `receive` can still receive Ether through payable function calls
  docs/contracts/functions.rst
Labels: documentation :book:, external contribution :star:

#13686 [README] Update maintainers
  README.md
Labels: documentation :book:

#13691 test: Properly clear storage dirty flag
  test/EVMHost.cpp
  test/libsolidity/semanticTests/abiEncoderV2/abi_encode_v2_in_modifier_used_in_v1_contract.sol
  test/libsolidity/semanticTests/array/byte_array_storage_layout.sol
  test/libsolidity/semanticTests/array/copying/array_copy_including_array.sol
  test/libsolidity/semanticTests/array/copying/array_nested_memory_to_storage.sol
  test/libsolidity/semanticTests/array/copying/bytes_storage_to_storage.sol
  test/libsolidity/semanticTests/array/copying/copy_byte_array_in_struct_to_storage.sol
  test/libsolidity/semanticTests/array/copying/function_type_array_to_storage.sol
  test/libsolidity/semanticTests/array/dynamic_array_cleanup.sol
  test/libsolidity/semanticTests/array/fixed_array_cleanup.sol
  test/libsolidity/semanticTests/array/invalid_encoding_for_storage_byte_array.sol
  test/libsolidity/semanticTests/array/pop/array_pop_array_transition.sol
  test/libsolidity/semanticTests/array/push/push_no_args_2d.sol
  test/libsolidity/semanticTests/storage/empty_nonempty_empty.sol
  test/libsolidity/semanticTests/structs/copy_struct_array_from_storage.sol
  test/libsolidity/semanticTests/structs/struct_containing_bytes_copy_and_delete.sol
  test/libsolidity/semanticTests/structs/struct_delete_storage_with_array.sol
  test/libsolidity/semanticTests/userDefinedValueType/calldata.sol
  test/libsolidity/semanticTests/various/destructuring_assignment.sol
  test/libsolidity/semanticTests/viaYul/array_storage_index_access.sol
  test/libsolidity/semanticTests/viaYul/array_storage_index_boundary_test.sol
  test/libsolidity/semanticTests/viaYul/array_storage_index_zeroed_test.sol
  test/libsolidity/semanticTests/viaYul/array_storage_length_access.sol
  test/libsolidity/semanticTests/viaYul/array_storage_push_empty.sol
  test/libsolidity/semanticTests/viaYul/array_storage_push_empty_length_address.sol
  test/libsolidity/semanticTests/viaYul/array_storage_push_pop.sol
Labels: external contribution :star:

#13696 Replace "miners" with "block builders"
  docs/security-considerations.rst
Labels: external contribution :star:

#13381 Clarify cleanup in docs.
  docs/internals/variable_cleanup.rst
Labels: documentation :book:

#13537 Upgrade to evmone 0.9.1 and hera 0.6.0 in buildpack
  scripts/docker/buildpack-deps/Dockerfile.ubuntu1604.clang.ossfuzz
  scripts/docker/buildpack-deps/Dockerfile.ubuntu2004
  scripts/docker/buildpack-deps/Dockerfile.ubuntu2004.clang
Labels: build system :building_construction:, has dependencies

#13532 Upgrade to evmc10 + evmone9
  .circleci/config.yml
  .circleci/osx_install_dependencies.sh
  scripts/install_evmone.ps1
  test/Common.h
  test/EVMHost.cpp
  test/EVMHost.h
  test/ExecutionFramework.cpp
  test/ExecutionFramework.h
  test/evmc/README.md
  test/evmc/evmc.h
  test/evmc/evmc.hpp
  test/evmc/filter_iterator.hpp
  test/evmc/helpers.h
  test/evmc/hex.hpp
  test/evmc/loader.c
  test/evmc/loader.h
  test/evmc/mocked_host.hpp
  test/evmc/utils.h
  test/tools/ossfuzz/SolidityEvmoneInterface.cpp
  test/tools/ossfuzz/SolidityEvmoneInterface.h
  test/tools/ossfuzz/StackReuseCodegenFuzzer.cpp
  test/tools/ossfuzz/YulEvmoneInterface.cpp
  test/tools/ossfuzz/YulEvmoneInterface.h
Labels: build system :building_construction:, has dependencies, priority review

#13693 Resolved `FunctionDefinition` instead of `FunctionCall` in CFG
  libsolidity/analysis/ControlFlowBuilder.cpp
  libsolidity/analysis/ControlFlowBuilder.h
  libsolidity/analysis/ControlFlowGraph.cpp
  libsolidity/analysis/ControlFlowGraph.h
  libsolidity/analysis/ControlFlowRevertPruner.cpp
Labels: refactor

#13682 Use hash of candidates for CSE.
  libyul/optimiser/BlockHasher.cpp
  libyul/optimiser/BlockHasher.h
  libyul/optimiser/CommonSubexpressionEliminator.cpp
  libyul/optimiser/CommonSubexpressionEliminator.h
  libyul/optimiser/DataFlowAnalyzer.h
  libyul/optimiser/SyntacticalEquality.cpp
  libyul/optimiser/SyntacticalEquality.h
Labels: optimizer

#13613 Clarification to the documentation on converting payable to non payable functions.
  docs/types/value-types.rst
Labels: documentation :book:, external contribution :star:

#13529 optimize and_shl distribution operation
  libevmasm/RuleList.h
  test/formal/and_distributed_over_shl.py
  test/libsolidity/semanticTests/abiEncoderV1/struct/struct_storage_ptr.sol
  test/libsolidity/semanticTests/array/arrays_complex_from_and_to_storage.sol
  test/libsolidity/semanticTests/array/byte_array_transitional_2.sol
  test/libsolidity/semanticTests/array/copying/array_copy_cleanup_uint40.sol
  test/libsolidity/semanticTests/array/copying/array_copy_storage_storage_different_base.sol
  test/libsolidity/semanticTests/array/copying/array_copy_storage_storage_different_base_nested.sol
  test/libsolidity/semanticTests/array/copying/array_copy_storage_storage_dynamic_dynamic.sol
  test/libsolidity/semanticTests/array/copying/array_copy_storage_to_memory_nested.sol
  test/libsolidity/semanticTests/array/copying/array_copy_target_leftover.sol
  test/libsolidity/semanticTests/array/copying/array_copy_target_simple.sol
  test/libsolidity/semanticTests/array/copying/array_copy_target_simple_2.sol
  test/libsolidity/semanticTests/array/copying/array_of_structs_containing_arrays_memory_to_storage.sol
  test/libsolidity/semanticTests/array/copying/cleanup_during_multi_element_per_slot_copy.sol
  test/libsolidity/semanticTests/array/copying/storage_memory_packed_dyn.sol
  test/libsolidity/semanticTests/array/delete/bytes_delete_element.sol
  test/libsolidity/semanticTests/array/dynamic_array_cleanup.sol
  test/libsolidity/semanticTests/array/dynamic_multi_array_cleanup.sol
  test/libsolidity/semanticTests/array/pop/array_pop_uint16_transition.sol
  test/libsolidity/semanticTests/array/pop/array_pop_uint24_transition.sol
  test/libsolidity/semanticTests/array/pop/byte_array_pop_copy_long.sol
  test/libsolidity/semanticTests/array/pop/byte_array_pop_long_storage_empty.sol
  test/libsolidity/semanticTests/array/pop/byte_array_pop_long_storage_empty_garbage_ref.sol
  test/libsolidity/semanticTests/array/pop/byte_array_pop_masking_long.sol
  test/libsolidity/semanticTests/array/push/array_push.sol
  test/libsolidity/semanticTests/array/push/byte_array_push_transition.sol
  test/libsolidity/semanticTests/array/push/push_no_args_2d.sol
  test/libsolidity/semanticTests/array/push/push_no_args_bytes.sol
  test/libsolidity/semanticTests/events/event_dynamic_nested_array_storage_v2.sol
  test/libsolidity/semanticTests/events/event_indexed_string.sol
  test/libsolidity/semanticTests/structs/struct_delete_storage_with_arrays_small.sol
  test/libsolidity/semanticTests/various/destructuring_assignment.sol
  test/libsolidity/semanticTests/viaYul/array_storage_index_access.sol
  test/libsolidity/semanticTests/viaYul/array_storage_index_zeroed_test.sol
  test/libyul/yulOptimizerTests/expressionSimplifier/optimize_shl_over_and.yul
Labels: optimizer

#13277 Improved output of formatNumberReadable
  Changelog.md
  libsolutil/CMakeLists.txt
  libsolutil/StringUtils.cpp
  libsolutil/StringUtils.h
  test/libsolidity/smtCheckerTests/operators/division_3.sol
  test/libsolidity/smtCheckerTests/overflow/signed_div_overflow.sol
  test/libsolidity/smtCheckerTests/overflow/signed_guard_sub_overflow.sol
  test/libsolidity/smtCheckerTests/overflow/signed_guard_sum_overflow.sol
  test/libsolidity/smtCheckerTests/overflow/signed_mul_overflow.sol
  test/libsolidity/smtCheckerTests/overflow/signed_sub_overflow.sol
  test/libsolidity/smtCheckerTests/overflow/signed_sum_overflow.sol
  test/libsolidity/smtCheckerTests/unchecked/signed_mod.sol
  test/libsolutil/StringUtils.cpp
Labels: external contribution :star:

#13679 [Documentation] Set error placement in contract, match example to specified order
  docs/style-guide.rst
Labels: documentation :book:, external contribution :star:, style guide

#12132 Use side-effects of user defined functions in evm code transform.
  Changelog.md
  libyul/backends/evm/ControlFlowGraph.h
  libyul/backends/evm/ControlFlowGraphBuilder.cpp
  libyul/backends/evm/ControlFlowGraphBuilder.h
  libyul/backends/evm/OptimizedEVMCodeTransform.cpp
  libyul/backends/evm/StackLayoutGenerator.cpp
  libyul/backends/evm/StackLayoutGenerator.h
  test/externalTests/zeppelin.sh
  test/libsolidity/semanticTests/abiEncoderV1/abi_encode_calldata_slice.sol
  test/libsolidity/semanticTests/abiEncoderV2/abi_encode_calldata_slice.sol
  test/libsolidity/semanticTests/array/array_storage_index_zeroed_test.sol
  test/libsolidity/semanticTests/array/pop/byte_array_pop_long_storage_empty_garbage_ref.sol
  test/libsolidity/semanticTests/byte_array_to_storage_cleanup.sol
  test/libsolidity/semanticTests/externalContracts/base64.sol
  test/libsolidity/semanticTests/externalContracts/snark.sol
  test/libsolidity/semanticTests/externalContracts/strings.sol
  test/libsolidity/semanticTests/functionCall/external_call_to_nonexisting_debugstrings.sol
  test/libyul/evmCodeTransform/after_terminating_function.yul
  test/libyul/yulControlFlowGraph/function.yul
  test/libyul/yulStackLayout/function.yul
Labels: priority review

#13736 Add "appendCBOR" to example JSON in metadata docs
  docs/metadata.rst
Labels: external contribution :star:

#13739 Code reshuffling before custom operators
  libsolidity/analysis/TypeChecker.cpp
  libsolidity/analysis/ViewPureChecker.cpp
  libsolidity/analysis/ViewPureChecker.h
  libsolidity/ast/Types.cpp
Labels: refactor

#13576 [tests] Refactor scripts/ASTImportTest.sh.
  scripts/ASTImportTest.sh
  scripts/common.sh
  test/cmdlineTests.sh
Labels: refactor

#13705 Only count variables if only variables are needed.
  libyul/backends/evm/EVMCodeTransform.cpp
  libyul/optimiser/ExpressionJoiner.cpp
  libyul/optimiser/LoopInvariantCodeMotion.cpp
  libyul/optimiser/NameCollector.cpp
  libyul/optimiser/NameCollector.h
  libyul/optimiser/Rematerialiser.cpp
  libyul/optimiser/UnusedFunctionParameterPruner.cpp
Labels: optimizer

#13581 Let the nightlies call themselves 'nightly', the return.
  scripts/build_emscripten.sh
  scripts/ci/build.sh
  scripts/ci/build_emscripten.sh
Labels: build system :building_construction:

#13743 Add updated solc-bin update call to ReleaseChecklist.md
  ReleaseChecklist.md
Labels: documentation :book:, external contribution :star:

#13753 Rename close stale action
  .github/workflows/stale.yml
Labels: has dependencies

#13755 Make isoltest not check SMTChecker counterexamples by default
  test/libsolidity/SMTCheckerTest.cpp
Labels: SMT

#13763 Array member clarification
  docs/types/reference-types.rst
Labels: documentation :book:, external contribution :star:

#13744 Update the review checklist to address common external PR problems
  ReviewChecklist.md
Labels: documentation :book:
