Repository argotorg/solidity, pull requests merged in 2023-06, with the labels that each got.

#14290 Remove unnecessary line from OZ external test script
  test/externalTests/zeppelin.sh
Labels: testing :hammer:

#14291 Disable gp2 tests
  .circleci/config.yml
Labels: testing :hammer:

#14289 Move hard-coded tests out of `cmdlineTests.sh`
  test/cmdlineTests.sh
  test/cmdlineTests/~assembler_modes/test.sh
  test/cmdlineTests/~ast_export_with_stop_after_parsing/test.sh
  test/cmdlineTests/~ast_import_export/test.sh
  test/cmdlineTests/~compilation_tests/test.sh
  test/cmdlineTests/~documentation_examples/test.sh
  test/cmdlineTests/~library_checksum/test.sh
  test/cmdlineTests/~library_long_names/test.sh
  test/cmdlineTests/~linking/test.sh
  test/cmdlineTests/~overwriting_files/test.sh
  test/cmdlineTests/~soljson_via_fuzzer/test.sh
  test/cmdlineTests/~standard_input/test.sh
  test/cmdlineTests/~unknown_options/test.sh
  test/cmdlineTests/~update_bugs_by_version/test.sh
  test/cmdlineTests/~via_ir_equivalence/test.sh
  test/stopAfterParseTests.sh
Labels: testing :hammer:

#14292 Document the command-line tests
  docs/contributing.rst
Labels: documentation :book:

#14268 Resurrect Yul optimizer CLI options
  Changelog.md
  solc/CommandLineInterface.cpp
  solc/CommandLineParser.cpp
  solc/CommandLineParser.h
  test/cmdlineTests/strict_asm_invalid_option_optimize_yul/args
  test/cmdlineTests/strict_asm_invalid_option_optimize_yul/err
  test/cmdlineTests/strict_asm_invalid_option_optimize_yul/exit
  test/cmdlineTests/strict_asm_invalid_option_optimize_yul/input.yul
  test/solc/CommandLineParser.cpp
  test/solc/Common.h
Labels: optimizer

#14243 Remove redundant Yul optimization from `IRGenerator`
  Changelog.md
  libsolidity/codegen/ir/IRGenerationContext.h
  libsolidity/codegen/ir/IRGenerator.cpp
  libsolidity/codegen/ir/IRGenerator.h
  libsolidity/interface/CompilerStack.cpp
  test/cmdlineTests/~via_ir_equivalence/test.sh
Labels: optimizer

#14310 Do not let low-level semantic test calls depend on a well-defined contract ABI.
  test/libsolidity/SemanticTest.cpp
Labels: testing :hammer:

#14321 Fix Bash syntax error that shows up in CLI test output when updating expectations
  test/cmdlineTests.sh
Labels: testing :hammer:

#14327 Sanitize metadata in Standard JSON output in command-line tests
  test/cmdlineTests.sh
  test/cmdlineTests/metadata/args
  test/cmdlineTests/metadata/input.sol
  test/cmdlineTests/metadata/output
  test/cmdlineTests/standard_metadata/args
  test/cmdlineTests/standard_metadata/in.sol
  test/cmdlineTests/standard_metadata/input.json
  test/cmdlineTests/standard_metadata/output.json
Labels: testing :hammer:

#14336 Remove unused Travis deploy key for bytecode compare
  scripts/bytecodecompare/deploy_key.enc
Labels: testing :hammer:

#14338 Add `--exclude` option to `cmdlineTests.sh`
  docs/contributing.rst
  test/cmdlineTests.sh
Labels: testing :hammer:

#14342 Disable failing OZ tests
  test/externalTests/zeppelin.sh
Labels: testing :hammer:

#14339 Parallelize CLI tests
  .circleci/config.yml
  .circleci/parallel_cli_tests.py
Labels: testing :hammer:

#14330 Generate CLI and Standard JSON bytecode reports in parallel
  .circleci/config.yml
Labels: performance :racehorse:, testing :hammer:

#14350 Bytecode report presets
  scripts/bytecodecompare/prepare_report.js
  scripts/bytecodecompare/prepare_report.py
  test/scripts/test_bytecodecompare_prepare_report.py
Labels: testing :hammer:

#14353 Unify and simplify bytecode report generation in CI
  .circleci/compare_bytecode_reports.sh
  .circleci/config.yml
  .circleci/parallel_bytecode_report.sh
  scripts/bytecodecompare/storebytecode.sh
Labels: testing :hammer:

#14354 Parallelize optimized and unoptimized bytecode reports in CI
  .circleci/compare_bytecode_reports.sh
  .circleci/config.yml
  .circleci/parallel_bytecode_report.sh
Labels: testing :hammer:, has dependencies

#14281 Change installation documentation for Arch Linux
  docs/installing-solidity.rst
Labels: documentation :book:, external contribution :star:

#14344 Fix error in SMTChecker: Use rich indentifier instead of external identifier to encode member access to functions
  Changelog.md
  libsolidity/formal/SMTEncoder.cpp
  test/libsolidity/smtCheckerTests/functions/functions_library_internal.sol
Labels: smt

#14351 Deduplicate environment variables in CI
  .circleci/config.yml
Labels: refactor
