Repository argotorg/solidity, pull requests merged in 2023-03, with the labels that each got.

#13785 Strict assembly fuzzer: Change optimization setting from full to minimal
  test/tools/ossfuzz/strictasm_assembly_ossfuzz.cpp
Labels: fuzz blocker

#14010 Initialize vars before use
  liblangutil/Scanner.cpp
Labels: external contribution :star:

#14030 Fix `b_ubu_ubsan_clang` running the address sanitizer instead of the undefined behavior sanitizer
  .circleci/config.yml
Labels: testing :hammer:

#14031 Update openzeppelin external tests with basic hardhat via-ir support
  test/externalTests/zeppelin.sh
Labels: testing :hammer:

#14034 Migrate from gitter to matrix api
  .circleci/config.yml
Labels: testing :hammer:

#14042 docs/grammer: Fix the writing of unicodeStringLiteral rules.
  docs/grammar/SolidityLexer.g4
Labels: external contribution :star:

#14057 Keep test/lsp.py working when not on a tty
  test/lsp.py
Labels: external contribution :star:

#13752 Reimplement unused eliminators
  Changelog.md
  libyul/optimiser/UnusedAssignEliminator.cpp
  libyul/optimiser/UnusedAssignEliminator.h
  libyul/optimiser/UnusedStoreBase.cpp
  libyul/optimiser/UnusedStoreBase.h
  libyul/optimiser/UnusedStoreEliminator.cpp
  libyul/optimiser/UnusedStoreEliminator.h
  test/libsolidity/semanticTests/externalContracts/deposit_contract.sol
  test/libyul/yulOptimizerTests/unusedAssignEliminator/conditionally_assign_before_conditional_revert.yul
  test/libyul/yulOptimizerTests/unusedAssignEliminator/conditionally_assign_before_leave.yul
  test/libyul/yulOptimizerTests/unusedAssignEliminator/conditionally_assign_before_revert.yul
  test/libyul/yulOptimizerTests/unusedAssignEliminator/for_deep_noremove.yul
  test/libyul/yulOptimizerTests/unusedAssignEliminator/revert_after_assign_return.yul
Labels: optimizer

#14061 Fix small typos in abi-spec.rst
  docs/abi-spec.rst
Labels: external contribution :star:

#14036 Include suffix definition as a secondary location in errors
  libsolidity/analysis/TypeChecker.cpp
Labels: has dependencies, roadmap

#14052 Update Metadata Documentation
  docs/metadata.rst
Labels: documentation :book:, external contribution :star:
