Repository argotorg/solidity, pull requests merged in 2023-07, with the labels that each got.

#14390 Fixed typo in protoToAbiv2.h
  test/tools/ossfuzz/protoToAbiV2.h
Labels: external contribution :star:

#14391 docs: Update compiler standard input docs to reflect all available evm options
  docs/using-the-compiler.rst
Labels: documentation :book:, external contribution :star:

#14382 docs: fix unintentionally commented out warning block
  docs/contracts/interfaces.rst
  docs/smtchecker.rst
  docs/units-and-global-variables.rst
Labels: documentation :book:, external contribution :star:

#14411 Update OpenZeppelin ext test to account for recently moved and/or removed test cases
  test/externalTests/zeppelin.sh
Labels: testing :hammer:

#14355 Via IR bytecode comparison
  .circleci/config.yml
  .circleci/parallel_bytecode_report.sh
  scripts/bytecodecompare/prepare_report.js
  scripts/bytecodecompare/prepare_report.py
  test/scripts/test_bytecodecompare_prepare_report.py
Labels: testing :hammer:, has dependencies

#14407 Fix ``FullInliner`` not preserving evaluation order of call arguments
  Changelog.md
  docs/bugs.json
  docs/bugs_by_version.json
  docs/internals/optimizer.rst
  libyul/optimiser/FullInliner.cpp
  libyul/optimiser/FullInliner.h
  test/libyul/YulOptimizerTestCommon.cpp
  test/libyul/yulOptimizerTests/fullInliner/call_arguments_with_side_effects.yul
  test/libyul/yulOptimizerTests/fullInliner/call_arguments_without_side_effects.yul
  test/libyul/yulOptimizerTests/fullInliner/move_up_rightwards_argument.yul
  test/libyul/yulOptimizerTests/fullInliner/multi_fun.yul
  test/libyul/yulOptimizerTests/fullInlinerWithoutSplitter/call_arguments_with_side_effects.yul
  test/libyul/yulOptimizerTests/fullInlinerWithoutSplitter/call_arguments_without_side_effects.yul
  test/libyul/yulOptimizerTests/fullInlinerWithoutSplitter/simple.sol
  test/libyul/yulOptimizerTests/fullSuite/call_arguments_with_side_effects.yul
  test/libyul/yulOptimizerTests/fullSuite/call_arguments_without_side_effects.yul
Labels: optimizer

#14426 Fix minor typos
  CMakeLists.txt
  ReleaseChecklist.md
  docs/060-breaking-changes.rst
  docs/using-the-compiler.rst
Labels: documentation :book:, external contribution :star:

#14428 Update solidity-website links in release checklist
  ReleaseChecklist.md
Labels: documentation :book:

#14441 Add TMP and remove TODO and FIXME from pylint note tags list
  scripts/pylintrc
Labels: testing :hammer:

#13873 Foundry prbmath external test
  .circleci/config.yml
  scripts/externalTests/runners/base.py
  scripts/externalTests/runners/foundry.py
  scripts/externalTests/test_helpers.py
  test/externalTests/prb-math.py
  test/externalTests/prb-math.sh
  test/external_tests.py
Labels: testing :hammer:

#14434 Fix ICE when emitting event from another contract
  Changelog.md
  libsolidity/interface/Natspec.cpp
  test/libsolidity/ABIJson/event_emitted_from_foreign_contract.sol
  test/libsolidity/ASTJSON/event_emitted_from_foreign_contract.json
  test/libsolidity/ASTJSON/event_emitted_from_foreign_contract.sol
  test/libsolidity/ASTJSON/event_emitted_from_foreign_contract_parseOnly.json
  test/libsolidity/SolidityNatspecJSON.cpp
  test/libsolidity/semanticTests/events/event_emit_from_a_foreign_contract.sol
  test/libsolidity/semanticTests/events/event_emit_from_a_foreign_contract_same_name.sol
  test/libsolidity/semanticTests/events/event_emit_interface_event_via_library.sol
  test/libsolidity/semanticTests/events/event_emit_via_interface.sol
Labels: bug :bug:, natspec

#14315 docs: Fixes for some minor mistakes/typos
  docs/path-resolution.rst
  docs/types/reference-types.rst
  docs/using-the-compiler.rst
  docs/yul.rst
Labels: documentation :book:, external contribution :star:

#14437 [Docs website] Update "Edit on GitHub" path to `develop` branch
  docs/_static/js/initialize.js
Labels: documentation :book:

#14446 SMTChecker tests: Keep counterexamples when updating expectations
  test/libsolidity/SMTCheckerTest.cpp
  test/libsolidity/SMTCheckerTest.h
  test/libsolidity/smtCheckerTests/array_members/pop_1_unsafe.sol
  test/libsolidity/smtCheckerTests/array_members/pop_constructor_unsafe.sol
  test/libsolidity/smtCheckerTests/array_members/push_zero_unsafe.sol
  test/libsolidity/smtCheckerTests/control_flow/short_circuit_and_fail.sol
  test/libsolidity/smtCheckerTests/control_flow/short_circuit_and_need_both_fail.sol
  test/libsolidity/smtCheckerTests/control_flow/short_circuit_or_fail.sol
  test/libsolidity/smtCheckerTests/control_flow/short_circuit_or_need_both_fail.sol
  test/libsolidity/smtCheckerTests/external_calls/call_mutex_unsafe.sol
  test/libsolidity/smtCheckerTests/external_calls/external_reentrancy_2.sol
  test/libsolidity/smtCheckerTests/external_calls/underflow_only_in_external_call.sol
  test/libsolidity/smtCheckerTests/file_level/easy.sol
  test/libsolidity/smtCheckerTests/file_level/struct.sol
  test/libsolidity/smtCheckerTests/functions/functions_identity_1_fail.sol
  test/libsolidity/smtCheckerTests/functions/functions_identity_2_fail.sol
  test/libsolidity/smtCheckerTests/functions/getters/array_2.sol
  test/libsolidity/smtCheckerTests/functions/getters/array_of_structs_2.sol
  test/libsolidity/smtCheckerTests/functions/getters/mapping_1.sol
  test/libsolidity/smtCheckerTests/functions/getters/mapping_2.sol
  test/libsolidity/smtCheckerTests/functions/getters/struct_1.sol
  test/libsolidity/smtCheckerTests/functions/getters/struct_2.sol
  test/libsolidity/smtCheckerTests/functions/getters/struct_with_reassignment.sol
  test/libsolidity/smtCheckerTests/functions/getters/uint.sol
  test/libsolidity/smtCheckerTests/functions/super_function_assert.sol
  test/libsolidity/smtCheckerTests/inheritance/base_contract_assertion_fail_1.sol
  test/libsolidity/smtCheckerTests/inheritance/base_contract_assertion_fail_2.sol
  test/libsolidity/smtCheckerTests/inheritance/base_contract_assertion_fail_3.sol
  test/libsolidity/smtCheckerTests/inheritance/base_contract_assertion_fail_4.sol
  test/libsolidity/smtCheckerTests/inheritance/base_contract_assertion_fail_5.sol
  test/libsolidity/smtCheckerTests/inheritance/base_contract_assertion_fail_6.sol
  test/libsolidity/smtCheckerTests/inheritance/base_contract_assertion_fail_7.sol
  test/libsolidity/smtCheckerTests/inheritance/base_contract_assertion_fail_8.sol
  test/libsolidity/smtCheckerTests/inheritance/base_contract_assertion_fail_9.sol
  test/libsolidity/smtCheckerTests/inheritance/diamond_super_1.sol
  test/libsolidity/smtCheckerTests/inheritance/diamond_super_2.sol
  test/libsolidity/smtCheckerTests/inheritance/diamond_super_3.sol
  test/libsolidity/smtCheckerTests/loops/while_loop_simple_1.sol
  test/libsolidity/smtCheckerTests/operators/assignment_chain_tuple_contract_2.sol
  test/libsolidity/smtCheckerTests/operators/assignment_chain_tuple_contract_3.sol
  test/libsolidity/smtCheckerTests/operators/bitwise_and_int.sol
  test/libsolidity/smtCheckerTests/operators/shifts/shift_cex.sol
  test/libsolidity/smtCheckerTests/operators/unary_add.sol
  test/libsolidity/smtCheckerTests/operators/unary_sub.sol
  test/libsolidity/smtCheckerTests/out_of_bounds/fixed_bytes_2.sol
  test/libsolidity/smtCheckerTests/simple/cex_smoke_test.sol
  test/libsolidity/smtCheckerTests/try_catch/try_3.sol
  test/libsolidity/smtCheckerTests/types/array_literal_2.sol
  test/libsolidity/smtCheckerTests/types/array_literal_3.sol
  test/libsolidity/smtCheckerTests/types/array_literal_5.sol
  test/libsolidity/smtCheckerTests/types/array_literal_6.sol
  test/libsolidity/smtCheckerTests/types/bool_simple_1.sol
  test/libsolidity/smtCheckerTests/types/mapping_1_fail.sol
  test/libsolidity/smtCheckerTests/types/struct/struct_constructor_named_args.sol
  test/libsolidity/smtCheckerTests/types/tuple_function.sol
  test/libsolidity/smtCheckerTests/types/tuple_function_2.sol
  test/libsolidity/smtCheckerTests/types/tuple_function_3.sol
  test/libsolidity/smtCheckerTests/userTypes/constant.sol
Labels: testing :hammer:, smt

#14439 [Docs website] Fix docs layout and link bugs [Fixes #14436]
  docs/_static/css/custom.css
  docs/_static/fonts/overpass-bold.otf
  docs/_static/fonts/overpass-bold.woff2
  docs/_static/fonts/overpass-italic.otf
  docs/_static/fonts/overpass-light.otf
  docs/_static/fonts/overpass-mono-bold.otf
  docs/_static/fonts/overpass-mono-bold.woff2
  docs/_static/fonts/overpass-mono-regular.otf
  docs/_static/fonts/overpass-mono-regular.woff2
  docs/_static/fonts/overpass-mono/overpass-mono-bold.otf
  docs/_static/fonts/overpass-mono/overpass-mono-regular.otf
  docs/_static/fonts/overpass-regular.otf
  docs/_static/fonts/overpass-regular.woff2
  docs/_static/fonts/overpass-semibold.otf
  docs/_static/fonts/overpass/overpass-bold.otf
  docs/_static/fonts/overpass/overpass-italic.otf
  docs/_static/fonts/overpass/overpass-light.otf
  docs/_static/fonts/overpass/overpass-regular.otf
  docs/_static/fonts/overpass/overpass-semibold.otf
  docs/_static/js/initialize.js
  docs/conf.py
Labels: documentation :book:

#14451 [DOCS] Re-upload original Solidity Logo to Brand Guide Section
  docs/brand-guide.rst
  docs/solidity_logo.svg
Labels: documentation :book:
