Repository argotorg/solidity, pull requests merged in 2023-05, with the labels that each got.

#14079 Update security-considerations.rst
  docs/security-considerations.rst
Labels: documentation :book:

#14160 [docs]: Fix metadata JSON "version" field being a string
  docs/metadata.rst
Labels: external contribution :star:

#14185 Changed order of menu and spelling
  docs/index.rst
Labels: documentation :book:

#14191 Migrate to new external tests script
  .circleci/config.yml
Labels: testing :hammer:

#14154 Optimize multiplicity map
  libyul/backends/evm/StackHelpers.h
  libyul/backends/evm/StackLayoutGenerator.cpp
Labels: external contribution :star:

#14164 Switch to Gen2 macOS resources on CircleCI
  .circleci/config.yml
  .circleci/osx_install_dependencies.sh
Labels: build system :building_construction:, external contribution :star:

#14228 Add sudo to buildpack-deps images
  scripts/docker/buildpack-deps/Dockerfile.emscripten
  scripts/docker/buildpack-deps/Dockerfile.ubuntu.clang.ossfuzz
  scripts/docker/buildpack-deps/Dockerfile.ubuntu2004
  scripts/docker/buildpack-deps/Dockerfile.ubuntu2204
  scripts/docker/buildpack-deps/Dockerfile.ubuntu2204.clang
Labels: build system :building_construction:

#14248 Bump buildpack-deps images
  .circleci/config.yml
  scripts/build_emscripten.sh
Labels: has dependencies

#14252 Fix small typo on "Units and Globally Available Variables" page
  docs/units-and-global-variables.rst
Labels: external contribution :star:

#14261 Clean up via-IR equivalence command-line test
  test/cmdlineTests.sh
Labels: testing :hammer:

#14226 Mention `immutableReferences` in immutables docs
  docs/contracts/constant-state-variables.rst
Labels: external contribution :star:

#14266 Disallow `--optimize-yul` and `--no-optimize-yul` at the same time
  Changelog.md
  solc/CommandLineParser.cpp
  test/cmdlineTests/optimizer_enabled_invalid_yul_optimizer_enabled_and_disabled/args
  test/cmdlineTests/optimizer_enabled_invalid_yul_optimizer_enabled_and_disabled/err
  test/cmdlineTests/optimizer_enabled_invalid_yul_optimizer_enabled_and_disabled/exit
  test/cmdlineTests/optimizer_enabled_invalid_yul_optimizer_enabled_and_disabled/input.sol
  test/cmdlineTests/strict_asm_optimizer_invalid_yul_optimizer_enabled_and_disabled/args
  test/cmdlineTests/strict_asm_optimizer_invalid_yul_optimizer_enabled_and_disabled/err
  test/cmdlineTests/strict_asm_optimizer_invalid_yul_optimizer_enabled_and_disabled/exit
  test/cmdlineTests/strict_asm_optimizer_invalid_yul_optimizer_enabled_and_disabled/input.yul
Labels: optimizer

#14264 Remove a few leftover mentions of Ewasm from optimizer docs
  docs/internals/optimizer.rst
Labels: documentation :book:

#14262 Fix help text about standard input usage
  solc/CommandLineParser.cpp
Labels: external contribution :star:

#14269 [SMTChecker] Remember verification targets from trusted external calls
  Changelog.md
  libsolidity/formal/CHC.cpp
  test/libsolidity/smtCheckerTests/deployment/deploy_trusted_flow.sol
  test/libsolidity/smtCheckerTests/external_calls/underflow_only_in_external_call.sol
Labels: external contribution :star:

#14280 Misspelling and terms inconsistencies
  .github/ISSUE_TEMPLATE/bug_report.md
  CODING_STYLE.md
  ReleaseChecklist.md
  docs/050-breaking-changes.rst
  docs/060-breaking-changes.rst
  docs/080-breaking-changes.rst
  docs/abi-spec.rst
  docs/assembly.rst
  docs/cheatsheet.rst
  docs/contracts/function-modifiers.rst
  docs/contracts/functions.rst
  docs/contracts/inheritance.rst
  docs/contributing.rst
  docs/control-structures.rst
  docs/examples/micropayment.rst
  docs/examples/modular.rst
  docs/installing-solidity.rst
  docs/introduction-to-smart-contracts.rst
  docs/ir-breaking-changes.rst
  docs/metadata.rst
  docs/path-resolution.rst
  docs/resources.rst
  docs/smtchecker.rst
  docs/style-guide.rst
  docs/types/conversion.rst
  docs/types/reference-types.rst
  docs/types/value-types.rst
  docs/units-and-global-variables.rst
  docs/using-the-compiler.rst
  docs/yul.rst
  tools/yulPhaser/README.md
Labels: documentation :book:

#14282 Remove sed commands targeting deleted files in openzeppelin external test
  test/externalTests/zeppelin.sh
Labels: testing :hammer:
