Repository argotorg/solidity, pull requests merged in 2023-11, with the labels that each got.

#14660 Patch codegen issues enough to make tests pass in experimental analysis
  libsolidity/experimental/codegen/IRGeneratorForStatements.cpp
  test/libsolidity/syntaxTests/experimental/builtin/builtin_type_definition.sol
Labels: experimental

#14635 Adjust `polymorphicInstance()`
  libsolidity/experimental/analysis/TypeInference.cpp
  libsolidity/experimental/analysis/TypeInference.h
  test/libsolidity/syntaxTests/experimental/builtin/builtin_type_definition.sol
  test/libsolidity/syntaxTests/experimental/inference/monomorphic_function_call_type_mismatch.sol
  test/libsolidity/syntaxTests/experimental/inference/polymorphic_function_call.sol
  test/libsolidity/syntaxTests/experimental/inference/polymorphic_function_call_let_polymorphism.sol
  test/libsolidity/syntaxTests/experimental/inference/polymorphic_function_call_type_mismatch.sol
  test/libsolidity/syntaxTests/experimental/inference/polymorphic_type.sol
  test/libsolidity/syntaxTests/experimental/inference/polymorphic_type_abs_and_rep.sol
  test/libsolidity/syntaxTests/experimental/inference/polymorphic_type_instantiation_and_operators.sol
Labels: experimental

#14665 Update README.md for X (Twitter) new brand guidelines
  README.md
Labels: external contribution :star:

#14649 Fix assembly item comparison for verbatim.
  Changelog.md
  docs/bugs.json
  docs/bugs_by_version.json
  libevmasm/AssemblyItem.h
  test/cmdlineTests/~deduplicator-verbatim-bug/test.sh
  test/cmdlineTests/~deduplicator-verbatim-bug/verbatim_inside_identical_blocks.yul
  test/libyul/objectCompiler/verbatim_bug.yul
Labels: optimizer

#14678 Make JS version of bytecode report indicate progress on stdout to prevent CI timeouts
  .circleci/config.yml
  .circleci/parallel_bytecode_report.sh
  scripts/bytecodecompare/prepare_report.js
  scripts/solc-bin/bytecode_reports_for_modified_binaries.sh
Labels: testing :hammer:

#14650 Update optimizer docs to include new unchecked loop increment
  docs/internals/optimizer.rst
Labels: documentation :book:

#14696 fix:typo errors
  docs/yul.rst
Labels: external contribution :star:

#14654 Use type class as a sort for its type variable
  libsolidity/experimental/analysis/TypeClassRegistration.cpp
  libsolidity/experimental/analysis/TypeInference.cpp
  libsolidity/experimental/ast/TypeSystem.cpp
  libsolidity/experimental/ast/TypeSystem.h
Labels: has dependencies, experimental

#14602 Fix typos
  test/compilationTests/corion/premium.sol
  test/compilationTests/corion/token.sol
Labels: external contribution :star:, testing :hammer:

#14708 Update contributing.rst
  docs/contributing.rst
Labels: external contribution :star:

#14712 Purge using namespace from test/libyul
  scripts/check_style.sh
  test/libyul/Common.cpp
  test/libyul/CompilabilityChecker.cpp
  test/libyul/ControlFlowGraphTest.cpp
  test/libyul/ControlFlowSideEffectsTest.cpp
  test/libyul/EVMCodeTransformTest.cpp
  test/libyul/FunctionSideEffects.cpp
  test/libyul/Inliner.cpp
  test/libyul/KnowledgeBaseTest.cpp
  test/libyul/Metrics.cpp
  test/libyul/ObjectCompilerTest.cpp
  test/libyul/ObjectParser.cpp
  test/libyul/Parser.cpp
  test/libyul/StackLayoutGeneratorTest.cpp
  test/libyul/StackShufflingTest.cpp
  test/libyul/SyntaxTest.cpp
  test/libyul/YulInterpreterTest.cpp
  test/libyul/YulOptimizerTest.cpp
  test/libyul/YulOptimizerTestCommon.cpp
Labels: refactor
