Repository argotorg/solidity, pull requests merged in 2023-02, with the labels that each got.

#13894 [DOCS] Update copyright year and description
  docs/conf.py
Labels: documentation :book:, refactor

#13909 Replace references to `sha3` in the docs with `keccak`
  docs/abi-spec.rst
Labels: documentation :book:, external contribution :star:

#13911 Fix broken docs links and redirects
  docs/contracts/creating-contracts.rst
  docs/contracts/events.rst
  docs/contributing.rst
  docs/examples/micropayment.rst
  docs/index.rst
  docs/introduction-to-smart-contracts.rst
  docs/layout-of-source-files.rst
  docs/natspec-format.rst
  docs/resources.rst
  docs/style-guide.rst
Labels: documentation :book:

#13914 Fix pylint 2.16 warnings
  scripts/bytecodecompare/prepare_report.py
  scripts/gas_diff_stats.py
  scripts/pylintrc
  test/lsp.py
Labels: testing :hammer:

#13916 Fix mapping style in docs
  docs/common-patterns.rst
  docs/contracts/function-modifiers.rst
  docs/contracts/visibility-and-getters.rst
  docs/examples/modular.rst
  docs/internals/layout_in_storage.rst
  docs/introduction-to-smart-contracts.rst
  docs/security-considerations.rst
  docs/types/mapping-types.rst
  docs/types/reference-types.rst
Labels: external contribution :star:

#13781 Update debian/compat to version 13
  scripts/deps-ppa/static_z3.sh
  scripts/release_ppa.sh
Labels: build system :building_construction:, external contribution :star:

#13919 libsolutil: Add missing include
  liblangutil/EVMVersion.h
  libsolutil/Common.h
Labels: external contribution :star:

#13929 Fixes minor compilation errors with some clangs
  libsolidity/lsp/DocumentHoverHandler.cpp
Labels: external contribution :star:

#13935 Tweak wording in value type docs
  docs/types/value-types.rst
Labels: documentation :book:

#13932 libsolidity: Redundant std::move
  libsolidity/ast/AST.h
Labels: external contribution :star:

#13934 specify "receive" as having no "name"
  docs/abi-spec.rst
Labels: documentation :book:, external contribution :star:

#12958 Yul grammar generator: Bound memory accesses.
  test/libyul/yulInterpreterTests/and_create.yul
  test/libyul/yulInterpreterTests/and_create2.yul
  test/libyul/yulInterpreterTests/zero_length_reads.yul
  test/libyul/yulInterpreterTests/zero_length_reads_and_revert.yul
  test/libyul/yulInterpreterTests/zero_range.yul
  test/libyul/yulOptimizerTests/loadResolver/zero_length_reads.yul
  test/tools/ossfuzz/protoToYul.cpp
  test/tools/ossfuzz/protoToYul.h
  test/tools/yulInterpreter/EVMInstructionInterpreter.cpp
  test/tools/yulInterpreter/EVMInstructionInterpreter.h
Labels: testing :hammer:, fuzz-blocker

#13953 Type recognition workaround for some GCC compilers
  libsolidity/ast/ASTJsonExporter.cpp
  libsolidity/codegen/ir/IRGeneratorForStatements.cpp
Labels: external contribution :star:

#13702 Re-implement KnowledgeBase using groups of constantly-spaced variables.
  libyul/optimiser/DataFlowAnalyzer.cpp
  libyul/optimiser/KnowledgeBase.cpp
  libyul/optimiser/KnowledgeBase.h
  libyul/optimiser/UnusedStoreEliminator.cpp
  libyul/optimiser/UnusedStoreEliminator.h
  test/libsolidity/semanticTests/array/copying/function_type_array_to_storage.sol
  test/libyul/KnowledgeBaseTest.cpp
Labels: optimizer

#13926 Release checklist tweaks and clarifications
  ReleaseChecklist.md
  scripts/list_contributors.sh
Labels: documentation :book:

#13976 Skipping flaky openzeppelin tests
  test/externalTests/zeppelin.sh
Labels: testing :hammer:

#13977 Remove openzeppelin workaround
  test/externalTests/zeppelin.sh
Labels: testing :hammer:

#13888 Remove obsolete endToEndExtraction script
  scripts/endToEndExtraction/create_traces.sh
  scripts/endToEndExtraction/remove-testcases.py
  scripts/endToEndExtraction/verify-testcases.py
Labels: external contribution :star:, testing :hammer:, takeover

#13990 docs: remove unnecessary text in yul.rst
  docs/yul.rst
Labels: external contribution :star:

#13804 Do not duplicate subassemblies.
  Changelog.md
  libevmasm/Assembly.cpp
  libevmasm/LinkerObject.cpp
  libevmasm/LinkerObject.h
  test/libsolidity/semanticTests/deployedCodeExclusion/subassembly_deduplication.sol
  test/libsolidity/semanticTests/functionCall/failed_create.sol
  test/libsolidity/semanticTests/libraries/library_references_preserve.sol
  test/libyul/objectCompiler/subObjectAccess.yul
Labels: bug :bug:, low effort

#13980 Update documentation block time discussion
  docs/introduction-to-smart-contracts.rst
Labels: documentation :book:, external contribution :star:

#13963 Add recommendation for leading underscore
  docs/style-guide.rst
Labels: external contribution :star:

#14002 Update smtchecker docs to reflect the only 2 Reported Inferred Inductive Invariants
  docs/smtchecker.rst
Labels: documentation :book:, SMT

#13415 User defined literal suffix parallel work
  libsolidity/analysis/TypeChecker.cpp
  libsolidity/ast/Types.cpp
  libsolidity/ast/Types.h
  libsolidity/codegen/ExpressionCompiler.cpp
  test/libsolidity/syntaxTests/literalSuffixes/parameters/exponent_out_of_range.sol
  test/libsolidity/syntaxTests/literalSuffixes/parameters/integer_out_of_range.sol
  test/libsolidity/syntaxTests/literalSuffixes/parameters/mantissa_out_of_range.sol
  test/libsolidity/syntaxTests/literalSuffixes/suffixableLiterals/invalid_suffixed_decimal_mantissa_too_large.sol
  test/libsolidity/syntaxTests/literalSuffixes/suffixableLiterals/invalid_suffixed_integer_too_large.sol
Labels: has dependencies, roadmap
