Repository argotorg/solidity, pull requests merged in 2023-01, with the labels that each got.

#13833 fix sphinx version to 5.* since 6.0 is not supported by code
  docs/requirements.txt
Labels: documentation :book:, external contribution :star:

#13876 Correct the return values in the example with multiple modifier placeholders in `ir-breaking-changes.rst`
  docs/ir-breaking-changes.rst
Labels: documentation :book:, external contribution :star:

#13878 Remove workarounds for latest dependencies from gnosis ext test
  test/externalTests/gnosis.sh
Labels: testing :hammer:

#13816 Disallow several `indexed` attributes for the same event parameter
  Changelog.md
  libsolidity/parsing/Parser.cpp
  test/libsolidity/syntaxTests/constants/file_level_multiple_constant_keywords.sol
  test/libsolidity/syntaxTests/errors/elementary_non_address_state_mutability_error_argument.sol
  test/libsolidity/syntaxTests/errors/invalid_parameter_indexed.sol
  test/libsolidity/syntaxTests/errors/invalid_parameter_location.sol
  test/libsolidity/syntaxTests/errors/invalid_parameter_mutability.sol
  test/libsolidity/syntaxTests/errors/invalid_parameter_visibility.sol
  test/libsolidity/syntaxTests/events/anonymous_event_multiple_anonymous_specifiers.sol
  test/libsolidity/syntaxTests/events/elementary_non_address_state_mutability_event_argument.sol
  test/libsolidity/syntaxTests/events/event_multiple_indexed_of_one_parameter.sol
  test/libsolidity/syntaxTests/events/invalid_parameter_location.sol
  test/libsolidity/syntaxTests/events/invalid_parameter_mutability.sol
  test/libsolidity/syntaxTests/events/invalid_parameter_visibility.sol
  test/libsolidity/syntaxTests/modifiers/elementary_non_address_state_mutability_modifier_argument.sol
  test/libsolidity/syntaxTests/modifiers/invalid_parameter_indexed.sol
  test/libsolidity/syntaxTests/modifiers/invalid_parameter_mutability.sol
  test/libsolidity/syntaxTests/modifiers/invalid_parameter_visibility.sol
  test/libsolidity/syntaxTests/modifiers/multiple_parameter_location.sol
  test/libsolidity/syntaxTests/parsing/address_invalid_state_mutability.sol
  test/libsolidity/syntaxTests/parsing/elemantary_non_address_payable_state_variable.sol
  test/libsolidity/syntaxTests/parsing/elementary_non_address_payable_argument.sol
  test/libsolidity/syntaxTests/parsing/elementary_non_address_payable_local.sol
  test/libsolidity/syntaxTests/parsing/elementary_non_address_payable_return.sol
  test/libsolidity/syntaxTests/parsing/elementary_non_address_state_mutability_argument.sol
  test/libsolidity/syntaxTests/parsing/elementary_non_address_state_mutability_file_var.sol
  test/libsolidity/syntaxTests/parsing/elementary_non_address_state_mutability_local.sol
  test/libsolidity/syntaxTests/parsing/elementary_non_address_state_mutability_return.sol
  test/libsolidity/syntaxTests/parsing/elementary_non_address_state_mutability_state_variable.sol
  test/libsolidity/syntaxTests/parsing/invalid_function_parameter_and_return_var_indexed.sol
  test/libsolidity/syntaxTests/parsing/invalid_function_parameter_and_return_var_mutability.sol
  test/libsolidity/syntaxTests/parsing/invalid_state_variable_location.sol
  test/libsolidity/syntaxTests/parsing/invalid_variable_indexed.sol
  test/libsolidity/syntaxTests/parsing/invalid_variable_mutablity.sol
  test/libsolidity/syntaxTests/parsing/location_specifiers_for_file_level_var.sol
  test/libsolidity/syntaxTests/parsing/location_specifiers_for_fn_returns_multi.sol
  test/libsolidity/syntaxTests/parsing/location_specifiers_for_locals_multi.sol
  test/libsolidity/syntaxTests/parsing/location_specifiers_for_params_multi.sol
  test/libsolidity/syntaxTests/parsing/location_specifiers_for_state_variables_multi.sol
  test/libsolidity/syntaxTests/parsing/multiple_mutability_specifiers.sol
  test/libsolidity/syntaxTests/parsing/multiple_state_mutability_specifiers.sol
  test/libsolidity/syntaxTests/parsing/multiple_statemutability_specifiers.sol
  test/libsolidity/syntaxTests/parsing/multiple_visibility_specifiers.sol
  test/libsolidity/syntaxTests/parsing/payable_accessor.sol
  test/libsolidity/syntaxTests/pragma/experimental_multiple_experimental.sol
  test/libsolidity/syntaxTests/tryCatch/elementary_non_address_state_mutability_catch.sol
  test/libsolidity/syntaxTests/tryCatch/elementary_non_address_state_mutability_try_returns.sol
  test/libsolidity/syntaxTests/tryCatch/invalid_catch_parameter_location_calldata.sol
  test/libsolidity/syntaxTests/tryCatch/invalid_catch_parameter_location_storage.sol
  test/libsolidity/syntaxTests/tryCatch/invalid_returns_var_location.sol
  test/libsolidity/syntaxTests/tryCatch/invalid_returns_vars_and_catch_parameter_indexed.sol
  test/libsolidity/syntaxTests/tryCatch/invalid_returns_vars_and_catch_parameter_mutability.sol
  test/libsolidity/syntaxTests/tryCatch/invalid_returns_vars_and_catch_parameter_visibility.sol
  test/libsolidity/syntaxTests/tryCatch/multiple_returns_vars_and_catch_parameter_location.sol
  test/libsolidity/syntaxTests/using/global_multiple_global_keywords.sol
  test/libsolidity/syntaxTests/visibility/file_level_variable_visibility.sol
  test/libsolidity/syntaxTests/visibility/invalid_function_parameter_and_return_var_visibility.sol
  test/libsolidity/syntaxTests/visibility/invalid_variable_visibility.sol
  test/libsolidity/syntaxTests/visibility/multiple_visibility_specifiers.sol
  test/libsolidity/syntaxTests/visibility/multiple_visibility_specifiers_external.sol
Labels: external contribution :star:

#13905 `optimizer.rst`: Remove redundant word in `UnusedStoreEliminator` description
  docs/internals/optimizer.rst
Labels: documentation :book:, external contribution :star:
