Repository argotorg/solidity, pull requests merged in 2023-04, with the labels that each got.

#14077 Fix a couple of small errors in docs: broken/missing backticks, broken code blocks, bad capitalization
  docs/bugs.rst
  docs/contracts/events.rst
  docs/contributing.rst
  docs/ir-breaking-changes.rst
  docs/path-resolution.rst
  docs/smtchecker.rst
  docs/style-guide.rst
  docs/types/value-types.rst
  docs/using-the-compiler.rst
Labels: external contribution :star:

#14008 Uniform naming convention for github labels
  .github/workflows/stale.yml
Labels: has dependencies

#14020 Update Solidity scripts to remove unencrypted git protocol
  scripts/deps-ppa/static_z3.sh
  scripts/release_ppa.sh
Labels: external contribution :star:

#14071 docs: correct small errors in yul.rst
  docs/yul.rst
Labels: documentation :book:, external contribution :star:

#14096 fix(docs): not displaying svg images in PDF
  docs/conf.py
Labels: documentation :book:, external contribution :star:

#14102 Fix dark mode in grammar
  docs/_static/css/dark.css
Labels: documentation :book:, external contribution :star:

#14107 Introduce `Shanghai` version and `push0` support
  .circleci/soltest_all.sh
  Changelog.md
  docs/using-the-compiler.rst
  libevmasm/Assembly.cpp
  libevmasm/Instruction.cpp
  libevmasm/Instruction.h
  liblangutil/EVMVersion.h
  scripts/tests.sh
  solc/CommandLineParser.cpp
  test/EVMHost.cpp
  test/libevmasm/Assembler.cpp
  test/libsolidity/GasCosts.cpp
  test/libsolidity/SolidityCompiler.cpp
  test/libsolidity/SolidityExpressionCompiler.cpp
  test/libsolidity/semanticTests/shanghai/evmone_support.sol
  test/libsolidity/semanticTests/shanghai/push0.sol
  test/libsolidity/syntaxTests/bytecode_too_large.sol
  test/libsolidity/syntaxTests/bytecode_too_large_abiencoder_v1.sol
  test/libsolidity/syntaxTests/inlineAssembly/push0_disallowed.sol
  test/libyul/yulSyntaxTests/invalid/push0_disallowed.yul
  test/tools/yulInterpreter/EVMInstructionInterpreter.cpp
Labels: external contribution :star:

#14103 A few extra tests for operators, denominations and virtual functions
  test/libsolidity/semanticTests/literals/denominations_in_array_sizes.sol
  test/libsolidity/semanticTests/literals/fractional_denominations.sol
  test/libsolidity/semanticTests/operators/userDefined/operator_parameter_and_return_cleanup_between_calls.sol
  test/libsolidity/semanticTests/virtualFunctions/virtual_override_changing_mutability_internal.sol
  test/libsolidity/semanticTests/virtualFunctions/virtual_override_changing_mutability_public.sol
  test/libsolidity/syntaxTests/denominations/denominations_in_array_sizes.sol
  test/libsolidity/syntaxTests/denominations/invalid_denomination_address.sol
  test/libsolidity/syntaxTests/denominations/invalid_denomination_on_bool.sol
  test/libsolidity/syntaxTests/denominations/invalid_denomination_on_string.sol
Labels: testing :hammer:

#14113 Team meetings change
  docs/contributing.rst
Labels: documentation :book:

#14101 fix(docs): fix missing backticks, remove latexpdfja, fix the missing help message of latexpdf, and remove unnecessary whitespace
  docs/080-breaking-changes.rst
  docs/Makefile
  docs/contracts/inheritance.rst
  docs/contributing.rst
  docs/control-structures.rst
  docs/installing-solidity.rst
  docs/internals/layout_in_storage.rst
  docs/internals/optimizer.rst
  docs/internals/source_mappings.rst
  docs/ir-breaking-changes.rst
  docs/make.bat
  docs/yul.rst
Labels: documentation :book:, external contribution :star:

#14084 Cheatsheet: Segregated codes based on type
  docs/cheatsheet.rst
  docs/units-and-global-variables.rst
Labels: documentation :book:, external contribution :star:

#14081 Update Side Menu
  docs/index.rst
Labels: documentation :book:

#14128 Fix incompatibilities with Golang parser generation
  docs/grammar/SolidityParser.g4
Labels: external contribution :star:

#14123 Literal-related documentation and index tweaks
  docs/contracts/functions.rst
  docs/contracts/using-for.rst
  docs/control-structures.rst
  docs/types/conversion.rst
  docs/types/reference-types.rst
  docs/types/value-types.rst
  docs/units-and-global-variables.rst
  docs/yul.rst
Labels: documentation :book:

#13982 Cleanup base images and CI config
  .circleci/config.yml
  .github/workflows/buildpack-deps.yml
  scripts/ci/buildpack-deps_test_ubuntu.clang.ossfuzz.sh
  scripts/docker/buildpack-deps/Dockerfile.clang.ossfuzz
  scripts/docker/buildpack-deps/Dockerfile.ubuntu2004
  scripts/docker/buildpack-deps/Dockerfile.ubuntu2204
  scripts/docker/buildpack-deps/README.md
  test/tools/ossfuzz/README.md
Labels: build system :building_construction:

#14145 Trivial refactors extracted from the JSON assembly import PR
  libevmasm/Assembly.cpp
  libevmasm/AssemblyItem.cpp
  libsolidity/interface/CompilerStack.cpp
  libsolidity/interface/CompilerStack.h
  libsolutil/Exceptions.h
  scripts/ASTImportTest.sh
  solc/CommandLineInterface.cpp
  solc/CommandLineInterface.h
  solc/CommandLineParser.cpp
  solc/CommandLineParser.h
Labels: refactor

#14143 Remove the inaccurate `Type::categoryName()`
  libsolidity/analysis/TypeChecker.cpp
  libsolidity/ast/Types.cpp
  libsolidity/ast/Types.h
  libsolutil/StringUtils.h
  test/libsolidity/syntaxTests/functionCalls/enum_value_not_callable.sol
  test/libsolidity/syntaxTests/functionCalls/int_not_callable.sol
  test/libsolidity/syntaxTests/functionCalls/magic_not_callable.sol
  test/libsolidity/syntaxTests/functionCalls/mapping_not_callable.sol
  test/libsolidity/syntaxTests/functionCalls/modifier_not_callable.sol
  test/libsolidity/syntaxTests/functionCalls/module_not_callable.sol
  test/libsolidity/syntaxTests/functionCalls/this_not_callable.sol
  test/libsolidity/syntaxTests/nameAndTypeResolution/462_callable_crash.sol
  test/libsolidity/syntaxTests/nameAndTypeResolution/492_do_not_crash_on_not_lvalue.sol
  test/libsolidity/syntaxTests/scoping/state_variable_function_conflict_former_crash.sol
  test/libsolidity/syntaxTests/tupleAssignments/double_storage_crash.sol
  test/libsolidity/syntaxTests/types/function_call_fail.sol
Labels: refactor

#13974 [SMTChecker] Use path condition in CHC engine
  Changelog.md
  libsolidity/formal/CHC.cpp
  test/cmdlineTests/standard_model_checker_solvers_smtlib2/output.json
  test/libsolidity/smtCheckerTests/operators/conditional_assignment_statevar_1.sol
  test/libsolidity/smtCheckerTests/operators/ternary_operator_1.sol
  test/libsolidity/smtCheckerTests/operators/ternary_operator_2.sol
  test/libsolidity/smtCheckerTests/operators/ternary_operator_3.sol
  test/libsolidity/smtCheckerTests/operators/ternary_operator_double_function_call.sol
  test/libsolidity/smtCheckerTests/operators/ternary_operator_external_code_1.sol
  test/libsolidity/smtCheckerTests/operators/ternary_operator_nested_1.sol
  test/libsolidity/smtCheckerTests/operators/ternary_operator_nested_2.sol
  test/libsolidity/smtCheckerTests/operators/ternary_operator_nested_3.sol
  test/libsolidity/smtCheckerTests/operators/ternary_operator_nested_4.sol
  test/libsolidity/smtCheckerTests/types/array_mapping_aliasing_2.sol
Labels: smt

#14156 Fix Remix links by adding `#` before URL params
  docs/ext/remix_code_links.py
Labels: external contribution :star:

#14122 docs: change the remix button from icon to text
  docs/_static/css/custom.css
  docs/_static/css/dark.css
  docs/analysing-compilation-output.rst
  docs/ext/remix_code_links.py
  docs/natspec-format.rst
  docs/smtchecker.rst
Labels: external contribution :star:

#14170 Fix throw of ExternalTestNotFound in external_tests.py
  test/external_tests.py
Labels: testing :hammer:
