Repository argotorg/solidity, pull requests merged in 2023-12, with the labels that each got.

#14575 Function dependency graph
  libsolidity/CMakeLists.txt
  libsolidity/experimental/analysis/Analysis.cpp
  libsolidity/experimental/analysis/FunctionDependencyAnalysis.cpp
  libsolidity/experimental/analysis/FunctionDependencyAnalysis.h
  libsolidity/experimental/ast/FunctionCallGraph.h
  libsolidity/interface/CompilerStack.cpp
  libsolidity/interface/CompilerStack.h
  test/CMakeLists.txt
  test/InteractiveTests.h
  test/libsolidity/FunctionDependencyGraphTest.cpp
  test/libsolidity/FunctionDependencyGraphTest.h
  test/libsolidity/functionDependencyGraphTests/callgraph.sol
  test/libsolidity/functionDependencyGraphTests/callgraph_no_leaves.sol
  test/libsolidity/syntaxTests/experimental/inference/invalid_type_referenced.sol
  test/tools/CMakeLists.txt
Labels: experimental

#14679 Release checklist update: publishing solc-js tarball from CI
  ReleaseChecklist.md
Labels: documentation :book:, has dependencies

#14718 Update PRB-Math external test installation process
  .circleci/config.yml
  scripts/externalTests/runners/foundry.py
  test/externalTests/prb-math.py
Labels: testing :hammer:

#14724 Fix argument expansion in command_available
  scripts/common.sh
Labels: testing :hammer:

#14727 Exclude experimental error codes from error_codes.py
  scripts/error_codes.py
Labels: experimental

#14726 Remove unimplemented assert for fetching linked object
  libsolidity/interface/CompilerStack.cpp
Labels: experimental

#14601 docs: fix incomplete member of address in cheatsheet.rst
  docs/cheatsheet.rst
Labels: documentation :book:, external contribution :star:

#14731 Fix `prepare_report.py` ignoring compiler exit code
  scripts/bytecodecompare/prepare_report.py
  scripts/common/cmdline_helpers.py
  test/scripts/test_bytecodecompare_prepare_report.py
Labels: testing :hammer:
