Repository argotorg/solidity, pull requests merged in 2023-08, with the labels that each got.

#14473 Refactor syntax test setup
  test/libsolidity/AnalysisFramework.cpp
  test/libsolidity/AnalysisFramework.h
  test/libsolidity/SMTCheckerTest.cpp
  test/libsolidity/SMTCheckerTest.h
  test/libsolidity/SyntaxTest.cpp
  test/libsolidity/SyntaxTest.h
Labels: testing :hammer:, smt

#14474 Sane error filtering in `AnalysisFramework`
  test/libsolidity/AnalysisFramework.cpp
  test/libsolidity/AnalysisFramework.h
  test/libsolidity/GasTest.cpp
  test/libsolidity/MemoryGuardTest.cpp
  test/libsolidity/SolidityCompiler.cpp
  test/libsolidity/SyntaxTest.cpp
Labels: testing :hammer:

#14478 Set CPUs for `soltest.sh` based on the number of available cores
  .circleci/config.yml
  .circleci/soltest.sh
Labels: testing :hammer:

#14482 Fix error IDs in `AnalysisFramework::formatErrors()`
  liblangutil/SourceReferenceFormatter.h
  libsolidity/codegen/ir/IRGenerator.cpp
  libsolidity/interface/CompilerStack.cpp
  libsolidity/interface/StandardCompiler.cpp
  solc/CommandLineInterface.cpp
  test/libsolidity/AnalysisFramework.cpp
  test/libsolidity/AnalysisFramework.h
  test/libsolidity/GasTest.cpp
  test/libsolidity/InlineAssembly.cpp
  test/libyul/Common.cpp
  test/libyul/ControlFlowGraphTest.cpp
  test/tools/ossfuzz/SolidityEvmoneInterface.cpp
  test/tools/ossfuzz/yulProto_diff_ossfuzz.cpp
  tools/yulPhaser/Program.cpp
Labels: testing :hammer:, refactor

#14496 Remove obsolete main function yul optimiser step.
  libyul/CMakeLists.txt
  libyul/optimiser/MainFunction.cpp
  libyul/optimiser/MainFunction.h
  test/libyul/YulOptimizerTestCommon.cpp
  test/libyul/yulOptimizerTests/mainFunction/empty_block.yul
  test/libyul/yulOptimizerTests/mainFunction/multi_fun_mixed.yul
  test/libyul/yulOptimizerTests/mainFunction/nested_fun.yul
  test/libyul/yulOptimizerTests/mainFunction/single_fun.yul
  test/libyul/yulOptimizerTests/mainFunction/smoke.yul
Labels: optimizer, wasm

#14480 Unify preamble injection in `AnalysisFramework`
  test/CMakeLists.txt
  test/libsolidity/AnalysisFramework.cpp
  test/libsolidity/GasTest.cpp
  test/libsolidity/SolidityExecutionFramework.cpp
  test/libsolidity/SolidityExecutionFramework.h
  test/libsolidity/SyntaxTest.cpp
  test/libsolidity/SyntaxTest.h
  test/libsolidity/util/Common.cpp
  test/libsolidity/util/Common.h
  test/solc/CommandLineInterface.cpp
  test/solc/Common.cpp
  test/solc/Common.h
  test/tools/CMakeLists.txt
Labels: testing :hammer:

#14499 Purge using namespace std from libsolutil
  libsolutil/CommonData.cpp
  libsolutil/CommonIO.cpp
  libsolutil/Exceptions.cpp
  libsolutil/IndentedWriter.cpp
  libsolutil/IpfsHash.cpp
  libsolutil/JSON.cpp
  libsolutil/Keccak256.cpp
  libsolutil/StringUtils.cpp
  libsolutil/SwarmHash.cpp
  libsolutil/TemporaryDirectory.cpp
  libsolutil/Whiskers.cpp
  scripts/check_style.sh
Labels: refactor

#14500 Fix infinite isoltest expectation update loop on values not taking full slots
  test/libsolidity/util/BytesUtils.cpp
Labels: testing :hammer:

#14309 AST Property tests
  libsolutil/JSON.cpp
  libsolutil/JSON.h
  test/CMakeLists.txt
  test/InteractiveTests.h
  test/libsolidity/ASTPropertyTest.cpp
  test/libsolidity/ASTPropertyTest.h
  test/libsolidity/astPropertyTests/blank_test_case.sol
  test/libsolidity/astPropertyTests/multiple_nested_properties_per_node.sol
  test/libsolidity/astPropertyTests/multiple_properties_per_node.sol
  test/libsolidity/astPropertyTests/nested_properties.sol
  test/libsolidity/astPropertyTests/property_expectation_with_colon.sol
  test/libsolidity/astPropertyTests/simple_properties.sol
  test/tools/CMakeLists.txt
Labels: testing :hammer:, takeover

#14479 Remove parser error recovery mode
  Changelog.md
  liblangutil/ParserBase.cpp
  liblangutil/ParserBase.h
  libsolidity/analysis/SyntaxChecker.cpp
  libsolidity/interface/CompilerStack.cpp
  libsolidity/interface/CompilerStack.h
  libsolidity/interface/StandardCompiler.cpp
  libsolidity/interface/StandardCompiler.h
  libsolidity/parsing/Parser.cpp
  libsolidity/parsing/Parser.h
  scripts/error_codes.py
  solc/CommandLineInterface.cpp
  solc/CommandLineParser.cpp
  solc/CommandLineParser.h
  test/InteractiveTests.h
  test/cmdlineTests/recovery_ast_constructor/args
  test/cmdlineTests/recovery_ast_constructor/err
  test/cmdlineTests/recovery_ast_constructor/exit
  test/cmdlineTests/recovery_ast_constructor/input.sol
  test/cmdlineTests/recovery_ast_empty_contract/args
  test/cmdlineTests/recovery_ast_empty_contract/err
  test/cmdlineTests/recovery_ast_empty_contract/exit
  test/cmdlineTests/recovery_ast_empty_contract/input.sol
  test/cmdlineTests/recovery_standard_json/input.json
  test/cmdlineTests/recovery_standard_json/output.json
  test/libsolidity/AnalysisFramework.cpp
  test/libsolidity/AnalysisFramework.h
  test/libsolidity/SolidityParser.cpp
  test/libsolidity/StandardCompiler.cpp
  test/libsolidity/SyntaxTest.cpp
  test/libsolidity/SyntaxTest.h
  test/libsolidity/errorRecoveryTests/constructor_recovers.sol
  test/libsolidity/errorRecoveryTests/contract_recovery.sol
  test/libsolidity/errorRecoveryTests/do_not_delete_at_error.sol
  test/libsolidity/errorRecoveryTests/error_to_eos.sol
  test/libsolidity/errorRecoveryTests/missing_rhs.sol
  test/libsolidity/errorRecoveryTests/multiple_errors.sol
  test/libsolidity/errorRecoveryTests/recovery_failed_eos.sol
  test/libsolidity/errorRecoveryTests/wrong_compiler_recovers_1.sol
  test/libsolidity/errorRecoveryTests/wrong_compiler_recovers_2.sol
  test/libsolidity/errorRecoveryTests/wrong_compiler_recovers_3.sol
  test/libsolidity/errorRecoveryTests/wrong_compiler_recovers_4.sol
  test/libyul/SyntaxTest.h
  test/solc/CommandLineParser.cpp
Labels: has dependencies

#14504 fixed a typo in `KnownState.h`
  libevmasm/KnownState.h
Labels: external contribution :star:

#14507 Refactor CircleCI config to define proper commands for reused fragments
  .circleci/config.yml
Labels: refactor

#14514 Purge using namespace std from solc
  scripts/check_style.sh
  solc/CommandLineInterface.cpp
  solc/CommandLineParser.cpp
  solc/main.cpp
Labels: external contribution :star:, refactor

#14511 Semantic tests via IR
  test/libsolidity/SemanticTest.cpp
  test/libsolidity/SemanticTest.h
  test/libsolidity/SolidityEndToEndTest.cpp
  test/libsolidity/SolidityExecutionFramework.cpp
  test/libsolidity/semanticTests/abiEncoderV2/abi_encode_v2_in_function_inherited_in_v1_contract.sol
  test/libsolidity/semanticTests/abiEncoderV2/calldata_overlapped_dynamic_arrays.sol
  test/libsolidity/semanticTests/array/array_storage_index_boundary_test.sol
  test/libsolidity/semanticTests/array/byte_array_transitional_2.sol
  test/libsolidity/semanticTests/array/copying/array_copy_different_packing.sol
  test/libsolidity/semanticTests/array/copying/array_copy_nested_array.sol
  test/libsolidity/semanticTests/array/copying/array_copy_storage_to_memory_nested.sol
  test/libsolidity/semanticTests/array/copying/array_nested_memory_to_storage.sol
  test/libsolidity/semanticTests/array/copying/array_of_structs_containing_arrays_memory_to_storage.sol
  test/libsolidity/semanticTests/array/copying/array_to_mapping.sol
  test/libsolidity/semanticTests/array/copying/bytes_storage_to_storage.sol
  test/libsolidity/semanticTests/array/copying/copy_byte_array_in_struct_to_storage.sol
  test/libsolidity/semanticTests/array/copying/copy_function_internal_storage_array.sol
  test/libsolidity/semanticTests/array/copying/elements_of_nested_array_of_structs_calldata_to_storage.sol
  test/libsolidity/semanticTests/array/copying/elements_of_nested_array_of_structs_memory_to_storage.sol
  test/libsolidity/semanticTests/array/copying/function_type_array_to_storage.sol
  test/libsolidity/semanticTests/array/copying/memory_dyn_2d_bytes_to_storage.sol
  test/libsolidity/semanticTests/array/copying/nested_array_of_structs_calldata_to_storage.sol
  test/libsolidity/semanticTests/array/copying/nested_array_of_structs_memory_to_storage.sol
  test/libsolidity/semanticTests/array/copying/nested_array_of_structs_storage_to_storage.sol
  test/libsolidity/semanticTests/array/copying/storage_memory_nested_bytes.sol
  test/libsolidity/semanticTests/array/delete/bytes_delete_element.sol
  test/libsolidity/semanticTests/array/function_array_cross_calls.sol
  test/libsolidity/semanticTests/array/pop/array_pop_uint16_transition.sol
  test/libsolidity/semanticTests/array/pop/byte_array_pop_long_storage_empty.sol
  test/libsolidity/semanticTests/array/pop/byte_array_pop_masking_long.sol
  test/libsolidity/semanticTests/array/push/byte_array_push_transition.sol
  test/libsolidity/semanticTests/array/push/push_no_args_bytes.sol
  test/libsolidity/semanticTests/byte_array_to_storage_cleanup.sol
  test/libsolidity/semanticTests/constructor/arrays_in_constructors.sol
  test/libsolidity/semanticTests/constructor/bytes_in_constructors_packer.sol
  test/libsolidity/semanticTests/constructor/constructor_static_array_argument.sol
  test/libsolidity/semanticTests/externalContracts/prbmath_unsigned.sol
  test/libsolidity/semanticTests/externalContracts/ramanujan_pi.sol
  test/libsolidity/semanticTests/externalContracts/strings.sol
  test/libsolidity/semanticTests/functionCall/call_options_overload.sol
  test/libsolidity/semanticTests/immutable/multi_creation.sol
  test/libsolidity/semanticTests/libraries/internal_types_in_library.sol
  test/libsolidity/semanticTests/storage/empty_nonempty_empty.sol
  test/libsolidity/semanticTests/structs/copy_substructures_from_mapping.sol
  test/libsolidity/semanticTests/structs/copy_substructures_to_mapping.sol
  test/libsolidity/semanticTests/structs/copy_to_mapping.sol
  test/libsolidity/semanticTests/various/destructuring_assignment.sol
Labels: testing :hammer:

#14505 Make `SyntaxTest` easier to extend with custom expectations
  liblangutil/Exceptions.h
  test/CommonSyntaxTest.cpp
  test/CommonSyntaxTest.h
  test/TestCaseReader.cpp
  test/libsolidity/SyntaxTest.cpp
  test/libsolidity/SyntaxTest.h
Labels: testing :hammer:

#14513 Purge using namespace std from libyul/backends
  libyul/backends/evm/AsmCodeGen.cpp
  libyul/backends/evm/ConstantOptimiser.cpp
  libyul/backends/evm/ControlFlowGraphBuilder.cpp
  libyul/backends/evm/EVMCodeTransform.cpp
  libyul/backends/evm/EVMDialect.cpp
  libyul/backends/evm/EVMMetrics.cpp
  libyul/backends/evm/EVMObjectCompiler.cpp
  libyul/backends/evm/EthAssemblyAdapter.cpp
  libyul/backends/evm/NoOutputAssembly.cpp
  libyul/backends/evm/OptimizedEVMCodeTransform.cpp
  libyul/backends/evm/StackLayoutGenerator.cpp
  scripts/check_style.sh
Labels: external contribution :star:

#14512 Purge using namespace std from libyul/optimiser
  libyul/optimiser/ASTCopier.cpp
  libyul/optimiser/ASTWalker.cpp
  libyul/optimiser/BlockFlattener.cpp
  libyul/optimiser/BlockHasher.cpp
  libyul/optimiser/CallGraphGenerator.cpp
  libyul/optimiser/CircularReferencesPruner.cpp
  libyul/optimiser/CommonSubexpressionEliminator.cpp
  libyul/optimiser/ConditionalSimplifier.cpp
  libyul/optimiser/ConditionalUnsimplifier.cpp
  libyul/optimiser/ControlFlowSimplifier.cpp
  libyul/optimiser/DataFlowAnalyzer.cpp
  libyul/optimiser/DeadCodeEliminator.cpp
  libyul/optimiser/Disambiguator.cpp
  libyul/optimiser/EqualStoreEliminator.cpp
  libyul/optimiser/EquivalentFunctionCombiner.cpp
  libyul/optimiser/EquivalentFunctionDetector.cpp
  libyul/optimiser/ExpressionInliner.cpp
  libyul/optimiser/ExpressionJoiner.cpp
  libyul/optimiser/ExpressionSimplifier.cpp
  libyul/optimiser/ExpressionSplitter.cpp
  libyul/optimiser/ForLoopConditionIntoBody.cpp
  libyul/optimiser/ForLoopConditionOutOfBody.cpp
  libyul/optimiser/ForLoopInitRewriter.cpp
  libyul/optimiser/FullInliner.cpp
  libyul/optimiser/FunctionCallFinder.cpp
  libyul/optimiser/FunctionGrouper.cpp
  libyul/optimiser/FunctionHoister.cpp
  libyul/optimiser/FunctionSpecializer.cpp
  libyul/optimiser/InlinableExpressionFunctionFinder.cpp
  libyul/optimiser/KnowledgeBase.cpp
  libyul/optimiser/LoadResolver.cpp
  libyul/optimiser/LoopInvariantCodeMotion.cpp
  libyul/optimiser/Metrics.cpp
  libyul/optimiser/NameCollector.cpp
  libyul/optimiser/NameDispenser.cpp
  libyul/optimiser/NameDisplacer.cpp
  libyul/optimiser/NameSimplifier.cpp
  libyul/optimiser/OptimizerUtilities.cpp
  libyul/optimiser/Rematerialiser.cpp
  libyul/optimiser/SSAReverser.cpp
  libyul/optimiser/SSATransform.cpp
  libyul/optimiser/SSAValueTracker.cpp
  libyul/optimiser/Semantics.cpp
  libyul/optimiser/SimplificationRules.cpp
  libyul/optimiser/StackCompressor.cpp
  libyul/optimiser/StackLimitEvader.cpp
  libyul/optimiser/StackToMemoryMover.cpp
  libyul/optimiser/StructuralSimplifier.cpp
  libyul/optimiser/Substitution.cpp
  libyul/optimiser/Suite.cpp
  libyul/optimiser/SyntacticalEquality.cpp
  libyul/optimiser/TypeInfo.cpp
  libyul/optimiser/UnusedAssignEliminator.cpp
  libyul/optimiser/UnusedFunctionParameterPruner.cpp
  libyul/optimiser/UnusedPruner.cpp
  libyul/optimiser/UnusedStoreBase.cpp
  libyul/optimiser/UnusedStoreEliminator.cpp
  libyul/optimiser/VarDeclInitializer.cpp
  libyul/optimiser/VarNameCleaner.cpp
  scripts/check_style.sh
Labels: external contribution :star:

#14515 Bump fmtlib to 9.1.0
  cmake/fmtlib.cmake
  libsolidity/lsp/SemanticTokensBuilder.cpp
Labels: external contribution :star:

#14522 Purge using namespace std in libyul
  libyul/AsmAnalysis.cpp
  libyul/AsmJsonConverter.cpp
  libyul/AsmJsonImporter.cpp
  libyul/AsmParser.cpp
  libyul/AsmPrinter.cpp
  libyul/CompilabilityChecker.cpp
  libyul/ControlFlowSideEffectsCollector.cpp
  libyul/Dialect.cpp
  libyul/FunctionReferenceResolver.cpp
  libyul/Object.cpp
  libyul/ObjectParser.cpp
  libyul/Scope.cpp
  libyul/ScopeFiller.cpp
  libyul/Utilities.cpp
  libyul/YulStack.cpp
  scripts/check_style.sh
Labels: external contribution :star:
