Repository argotorg/solidity, pull requests merged in 2023-10, with the labels that each got.

#14574 Fix variable clearing in DataFlowAnalyzer being affected by variable names
  Changelog.md
  libyul/optimiser/DataFlowAnalyzer.cpp
  test/cmdlineTests/~name_dependent_cse_bug/cse_bug.yul
  test/cmdlineTests/~name_dependent_cse_bug/test.sh
  test/libsolidity/semanticTests/externalContracts/prbmath_unsigned.sol
  test/libsolidity/semanticTests/externalContracts/ramanujan_pi.sol
  test/libsolidity/semanticTests/externalContracts/strings.sol
  test/libyul/yulOptimizerTests/fullSuite/name_dependent_cse_bug_part_1.yul
  test/libyul/yulOptimizerTests/fullSuite/name_dependent_cse_bug_part_1_pre_shanghai.yul
  test/libyul/yulOptimizerTests/fullSuite/name_dependent_cse_bug_part_2.yul
  test/libyul/yulOptimizerTests/fullSuite/name_dependent_cse_bug_part_2_pre_shanghai.yul
Labels: optimizer

#14600 Fix brink external test
  test/externalTests/brink.sh
Labels: testing :hammer:

#14563 Small docs corrections related to events
  docs/contracts/events.rst
  docs/contracts/inheritance.rst
  docs/style-guide.rst
Labels: documentation :book:, style guide

#14605 Make Yul proto mutator mutations deterministic.
  test/tools/ossfuzz/protomutators/YulProtoMutator.cpp
  test/tools/ossfuzz/protomutators/YulProtoMutator.h
Labels: testing :hammer:

#14517 Generalize helpers for indenting and prefixing
  libsolutil/CMakeLists.txt
  libsolutil/IndentedWriter.cpp
  libsolutil/IndentedWriter.h
  libsolutil/StringUtils.cpp
  libsolutil/StringUtils.h
  libyul/Object.cpp
  test/CMakeLists.txt
  test/CommonSyntaxTest.cpp
  test/TestCase.cpp
  test/TestCase.h
  test/libsolidity/ASTJSONTest.cpp
  test/libsolidity/GasTest.cpp
  test/libsolidity/GasTest.h
  test/libsolidity/NatspecJSONTest.cpp
  test/libsolidity/SemanticTest.cpp
  test/libsolutil/IndentedWriter.cpp
  test/libyul/YulOptimizerTest.cpp
Labels: refactor

#14599 Introduce ``compileViaYul`` syntax test option
  test/libsolidity/SyntaxTest.cpp
  test/libsolidity/SyntaxTest.h
  test/libsolidity/syntaxTests/experimental/parsing_stdlib_import_1.sol
  test/libsolidity/syntaxTests/experimental/parsing_stdlib_import_2.sol
  test/libsolidity/syntaxTests/experimental/parsing_stdlib_import_3.sol
  test/libsolidity/syntaxTests/experimental/parsing_stdlib_import_4.sol
Labels: testing :hammer:

#14590 Consistent severity and color for CLI error messages
  Changelog.md
  liblangutil/SourceReferenceFormatter.cpp
  liblangutil/SourceReferenceFormatter.h
  solc/CommandLineInterface.cpp
  solc/CommandLineInterface.h
  solc/CommandLineParser.cpp
  test/cmdlineTests.sh
  test/cmdlineTests/ast_json_import_wrong_evmVersion/err
  test/cmdlineTests/debug_info_in_yul_and_evm_asm_print_all_and_none/err
  test/cmdlineTests/debug_info_in_yul_and_evm_asm_print_snippet_only/err
  test/cmdlineTests/linker_mode_invalid_option_no_optimize_yul/err
  test/cmdlineTests/linker_mode_invalid_option_optimize/err
  test/cmdlineTests/linker_mode_invalid_option_optimize_runs/err
  test/cmdlineTests/linker_mode_invalid_option_optimize_yul/err
  test/cmdlineTests/linker_mode_invalid_option_yul_optimizations/err
  test/cmdlineTests/linker_mode_output_selection_invalid/err
  test/cmdlineTests/linking_strict_assembly_duplicate_library_name/err
  test/cmdlineTests/model_checker_bmc_loop_iterations_invalid_arg/err
  test/cmdlineTests/model_checker_bmc_loop_iterations_no_argument/err
  test/cmdlineTests/model_checker_contracts_contract_missing/err
  test/cmdlineTests/model_checker_contracts_empty_contract/err
  test/cmdlineTests/model_checker_contracts_empty_source/err
  test/cmdlineTests/model_checker_contracts_one_contract_missing/err
  test/cmdlineTests/model_checker_contracts_source_missing/err
  test/cmdlineTests/model_checker_ext_calls_empty_arg/err
  test/cmdlineTests/model_checker_ext_calls_wrong_arg/err
  test/cmdlineTests/model_checker_invariants_wrong/err
  test/cmdlineTests/model_checker_print_query_no_smtlib2_solver_bmc/err
  test/cmdlineTests/model_checker_print_query_no_smtlib2_solver_chc/err
  test/cmdlineTests/model_checker_print_query_superflous_solver/err
  test/cmdlineTests/model_checker_solvers_wrong/err
  test/cmdlineTests/model_checker_solvers_wrong2/err
  test/cmdlineTests/model_checker_targets_error/err
  test/cmdlineTests/no_cbor_metadata_with_metadata_hash/err
  test/cmdlineTests/optimizer_enabled_invalid_yul_optimizer_enabled_and_disabled/err
  test/cmdlineTests/standard_cli_output_selection_invalid/err
  test/cmdlineTests/standard_file_not_found/err
  test/cmdlineTests/standard_invalid_option_no_optimize_yul/err
  test/cmdlineTests/standard_invalid_option_optimize/err
  test/cmdlineTests/standard_invalid_option_optimize_runs/err
  test/cmdlineTests/standard_invalid_option_optimize_yul/err
  test/cmdlineTests/standard_invalid_option_yul_optimizations/err
  test/cmdlineTests/stop_after_parsing_abi/err
  test/cmdlineTests/strict_asm_debug_info_print_snippet_only/err
  test/cmdlineTests/strict_asm_invalid_option_output_dir/err
  test/cmdlineTests/strict_asm_optimizer_invalid_yul_optimizer_enabled_and_disabled/err
  test/cmdlineTests/strict_asm_options_in_non_asm_mode/err
  test/cmdlineTests/strict_asm_output_selection_invalid/err
  test/cmdlineTests/yul_optimizer_steps_disabled/err
  test/cmdlineTests/yul_optimizer_steps_invalid_abbreviation/err
  test/cmdlineTests/yul_optimizer_steps_nesting_too_deep/err
  test/cmdlineTests/yul_optimizer_steps_unbalanced_closing_bracket/err
  test/cmdlineTests/yul_optimizer_steps_unbalanced_opening_bracket/err
  test/cmdlineTests/~unknown_options/test.sh
  test/solc/CommandLineInterface.cpp
Labels: refactor

#14610 Introduce `--no-import-callback` CLI option
  Changelog.md
  docs/path-resolution.rst
  libsolidity/interface/UniversalCallback.h
  solc/CommandLineInterface.cpp
  solc/CommandLineInterface.h
  solc/CommandLineParser.cpp
  solc/CommandLineParser.h
  test/cmdlineTests/no_import_callback/args
  test/cmdlineTests/no_import_callback/contract_1.sol
  test/cmdlineTests/no_import_callback/contract_2.sol
  test/cmdlineTests/no_import_callback/err
  test/cmdlineTests/no_import_callback/exit
  test/cmdlineTests/standard_no_import_callback/B.sol
  test/cmdlineTests/standard_no_import_callback/args
  test/cmdlineTests/standard_no_import_callback/input.json
  test/cmdlineTests/standard_no_import_callback/output.json
  test/solc/CommandLineInterface.cpp
  test/solc/CommandLineParser.cpp
Labels: feature

#14580 Fix coloring of info messages in isoltest
  liblangutil/Exceptions.cpp
  liblangutil/Exceptions.h
  liblangutil/SourceReferenceFormatter.cpp
  liblangutil/SourceReferenceFormatter.h
  libsolutil/AnsiColorized.h
  test/CommonSyntaxTest.cpp
  test/CommonSyntaxTest.h
  test/libsolidity/SyntaxTest.cpp
  test/libyul/SyntaxTest.cpp
Labels: testing :hammer:

#14597 Add required steps to fullSimplify and loadResolver steps.
  test/libyul/YulOptimizerTestCommon.cpp
  test/libyul/yulOptimizerTests/fullSimplify/scoped_var_ref_in_function_call.yul
  test/libyul/yulOptimizerTests/loadResolver/scoped_var_ref_in_keccak.yul
Labels: testing :hammer:

#14651 Fix wrong file path in standard json tests
  test/cmdlineTests/standard_optimizer_yulDetails_optimiserSteps_with_empty_cleanup_sequence/input.json
  test/cmdlineTests/standard_optimizer_yulDetails_optimiserSteps_with_empty_optimisation_sequence/input.json
  test/cmdlineTests/standard_optimizer_yulDetails_optimiserSteps_with_empty_sequence/input.json
Labels: testing :hammer:

#14238 Update abi-spec.rst
  docs/abi-spec.rst
Labels: documentation :book:, external contribution :star:

#14644 Release checklist: warning about publishing the release too early
  ReleaseChecklist.md
Labels: documentation :book:
