Repository argotorg/solidity, pull requests merged in 2023-09, with the labels that each got.

#14525 deprecate using namespace std
  scripts/check_style.sh
  test/contracts/AuctionRegistrar.cpp
  test/contracts/Wallet.cpp
  test/libevmasm/Assembler.cpp
  test/libevmasm/Optimiser.cpp
  test/liblangutil/CharStream.cpp
  test/liblangutil/Scanner.cpp
  test/libsolidity/ABIDecoderTests.cpp
  test/libsolidity/ABIEncoderTests.cpp
  test/libsolidity/ABIJsonTest.cpp
  test/libsolidity/ABITestsCommon.h
  test/libsolidity/ASTJSONTest.cpp
  test/libsolidity/ASTPropertyTest.cpp
  test/libsolidity/AnalysisFramework.cpp
  test/libsolidity/Assembly.cpp
  test/libsolidity/ErrorCheck.cpp
  test/libsolidity/GasCosts.cpp
  test/libsolidity/GasMeter.cpp
  test/libsolidity/GasTest.cpp
  test/libsolidity/Imports.cpp
  test/libsolidity/InlineAssembly.cpp
  test/libsolidity/LibSolc.cpp
  test/libsolidity/MemoryGuardTest.cpp
  test/libsolidity/Metadata.cpp
  test/libsolidity/SMTCheckerTest.cpp
  test/libsolidity/SemVerMatcher.cpp
  test/libsolidity/SemanticTest.cpp
  test/libsolidity/SolidityCompiler.cpp
  test/libsolidity/SolidityEndToEndTest.cpp
  test/libsolidity/SolidityExecutionFramework.cpp
  test/libsolidity/SolidityExpressionCompiler.cpp
  test/libsolidity/SolidityNameAndTypeResolution.cpp
  test/libsolidity/SolidityOptimizer.cpp
  test/libsolidity/ViewPureChecker.cpp
  test/libsolidity/analysis/FunctionCallGraph.cpp
  test/libsolidity/interface/FileReader.cpp
  test/libsolutil/Checksum.cpp
  test/libsolutil/CommonData.cpp
  test/libsolutil/CommonIO.cpp
  test/libsolutil/FixedHash.cpp
  test/libsolutil/FunctionSelector.cpp
  test/libsolutil/IndentedWriter.cpp
  test/libsolutil/IpfsHash.cpp
  test/libsolutil/IterateReplacing.cpp
  test/libsolutil/JSON.cpp
  test/libsolutil/Keccak256.cpp
  test/libsolutil/LEB128.cpp
  test/libsolutil/StringUtils.cpp
  test/libsolutil/SwarmHash.cpp
  test/libsolutil/TemporaryDirectoryTest.cpp
  test/libsolutil/UTF8.cpp
  test/libsolutil/Whiskers.cpp
Labels: external contribution :star:

#14530 Fix failing OZ test
  test/externalTests/zeppelin.sh
Labels: testing :hammer:

#14524 Move around tests
  libsolidity/experimental/analysis/TypeInference.h
  libsolidity/interface/CompilerStack.h
  scripts/ASTImportTest.sh
  test/libsolidity/SyntaxTest.cpp
  test/libsolidity/semanticTests/experimental/stub.sol
  test/libsolidity/syntaxTests/experimental/import/experimental_solidity.sol
  test/libsolidity/syntaxTests/experimental/import/experimental_solidity_multisource_not_all_enable.sol
  test/libsolidity/syntaxTests/experimental/import/experimental_solidity_out_of_order_1.sol
  test/libsolidity/syntaxTests/experimental/import/experimental_solidity_out_of_order_2.sol
  test/libsolidity/syntaxTests/experimental/import/experimental_solidity_wrong_evm_version.sol
  test/libsolidity/syntaxTests/experimental/import/parsing_stdlib_import_1.sol
  test/libsolidity/syntaxTests/experimental/import/parsing_stdlib_import_2.sol
  test/libsolidity/syntaxTests/experimental/import/parsing_stdlib_import_3.sol
  test/libsolidity/syntaxTests/experimental/import/parsing_stdlib_import_4.sol
  test/libsolidity/syntaxTests/experimental/import/parsing_stdlib_import_without_pragma_1.sol
  test/libsolidity/syntaxTests/experimental/import/parsing_stdlib_import_without_pragma_2.sol
  test/libsolidity/syntaxTests/experimental/inference/experimental_keywords.sol
  test/libsolidity/syntaxTests/experimental/inference/import_and_call_stdlib_function.sol
  test/stopAfterParseTests.sh
Labels: experimental

#14561 update opcode values
  libevmasm/Instruction.h
Labels: external contribution :star:

#14551 docs: add clarification about post-execution modifier behavior
  docs/contracts/function-modifiers.rst
Labels: documentation :book:, external contribution :star:

#14558 Separate type class registration pass in experimental analysis
  libsolidity/CMakeLists.txt
  libsolidity/experimental/analysis/Analysis.cpp
  libsolidity/experimental/analysis/TypeClassRegistration.cpp
  libsolidity/experimental/analysis/TypeClassRegistration.h
  libsolidity/experimental/analysis/TypeInference.cpp
  libsolidity/experimental/analysis/TypeInference.h
  libsolidity/experimental/ast/TypeSystem.h
  libsolidity/experimental/codegen/IRGeneratorForStatements.cpp
  test/libsolidity/semanticTests/experimental/type_class.sol
Labels: experimental

#14518 `AnalysisFramework` refactor
  test/libsolidity/AnalysisFramework.cpp
  test/libsolidity/AnalysisFramework.h
  test/libsolidity/GasTest.cpp
  test/libsolidity/GasTest.h
  test/libsolidity/MemoryGuardTest.cpp
  test/libsolidity/MemoryGuardTest.h
  test/libsolidity/SMTCheckerTest.cpp
  test/libsolidity/SMTCheckerTest.h
  test/libsolidity/SolidityCompiler.cpp
  test/libsolidity/SolidityNameAndTypeResolution.cpp
  test/libsolidity/SyntaxTest.cpp
  test/libsolidity/SyntaxTest.h
Labels: testing :hammer:

#14566 Defining built-ins in experimental analysis
  liblangutil/Token.h
  libsolidity/ast/AST.h
  libsolidity/ast/ASTForward.h
  libsolidity/ast/ASTVisitor.h
  libsolidity/ast/AST_accept.h
  libsolidity/experimental/analysis/TypeInference.cpp
  libsolidity/experimental/analysis/TypeInference.h
  libsolidity/experimental/analysis/TypeRegistration.cpp
  libsolidity/experimental/analysis/TypeRegistration.h
  libsolidity/experimental/ast/TypeSystemHelper.cpp
  libsolidity/experimental/ast/TypeSystemHelper.h
  libsolidity/parsing/Parser.cpp
  test/libsolidity/semanticTests/experimental/stub.sol
  test/libsolidity/semanticTests/experimental/type_class.sol
  test/libsolidity/syntaxTests/experimental/builtin/builtin_type_definition.sol
  test/libsolidity/syntaxTests/experimental/builtin/builtin_type_definition_duplicate.sol
  test/libsolidity/syntaxTests/experimental/builtin/builtin_type_definition_unknown.sol
Labels: experimental

#14565 Add test for via-ir codegen import bug
  scripts/common/cmdline_helpers.py
  scripts/common/git_helpers.py
  scripts/splitSources.py
  test/cmdlineTests/~bytecode_equivalence_independent_of_import_discovery_order/inputs.sol
  test/cmdlineTests/~bytecode_equivalence_independent_of_import_discovery_order/test.py
Labels: testing :hammer:
