Repository argotorg/solidity, pull requests merged in 2024-04, with the labels that each got.

#14962 Install eldarica on ubuntu base images and osx machines
  .circleci/osx_install_dependencies.sh
  .github/workflows/buildpack-deps.yml
  scripts/docker/buildpack-deps/Dockerfile.ubuntu2004
  scripts/docker/buildpack-deps/Dockerfile.ubuntu2204
Labels: build system :building_construction:

#14964 Bump Ubuntu docker images to support eldarica
  .circleci/config.yml
Labels: build system :building_construction:, has dependencies

#14965 SMTChecker: Add command-line test for Eldarica
  test/cmdlineTests/model_checker_solvers_eld/args
  test/cmdlineTests/model_checker_solvers_eld/err
  test/cmdlineTests/model_checker_solvers_eld/input.sol
Labels: testing :hammer:, has dependencies, smt

#14958 Make KnowledgeBase object constructors explicit
  libyul/optimiser/KnowledgeBase.h
Labels: external contribution :star:

#14973 docs: Replace outdated Scaffold-ETH link to Scaffold-ETH-2
  docs/resources.rst
Labels: external contribution :star:

#14949 Update reference-types.rst
  docs/types/reference-types.rst
Labels: external contribution :star:

#14901 Optimize the magicVariableToID function.
  libsolidity/analysis/GlobalContext.cpp
Labels: external contribution :star:

#14950 Update precompiled contract address range
  docs/introduction-to-smart-contracts.rst
Labels: documentation :book:, external contribution :star:

#14860 [buildsystem] Improve solidity embeddability.
  CMakeLists.txt
  libsolutil/JSON.cpp
  libstdlib/CMakeLists.txt
Labels: build system :building_construction:

#14976 Install Eldarica on Ubuntu Clang images
  scripts/docker/buildpack-deps/Dockerfile.ubuntu.clang.ossfuzz
  scripts/docker/buildpack-deps/Dockerfile.ubuntu2204.clang
Labels: build system :building_construction:

#14978 Remove signature removal from macos universal binaries.
  .circleci/config.yml
Labels: build system :building_construction:

#14998 Fix error msg for hex number combined with unit denomination
  libsolidity/analysis/TypeChecker.cpp
  test/libsolidity/syntaxTests/denominations/combining_hex_and_denomination.sol
  test/libsolidity/syntaxTests/denominations/invalid_denomination_address.sol
Labels: external contribution :star:

#15021 `gas_diff_stats`: base branch option
  scripts/gas_diff_stats.py
Labels: testing :hammer:

#15028 Update Changelog.md
  Changelog.md
  docs/bugs_by_version.json
Labels: external contribution :star:

#15023 Timing info in external test JSON reports
  scripts/common.sh
  scripts/externalTests/common.sh
Labels: testing :hammer:

#15022 Timing benchmark tweaks and fixes
  test/benchmarks/run.sh
Labels: testing :hammer:

#15005 chore: fix typo in comment
  libsolc/libsolc.h
  libsolutil/Keccak256.cpp
  test/libsolidity/AnalysisFramework.h
Labels: external contribution :star:

#14992 chore: remove repetitive words
  libsolidity/interface/FileReader.cpp
  test/libyul/yulOptimizerTests/unusedAssignEliminator/for_continue.yul
Labels: external contribution :star:

#14968 Bytecode difference caused by SSA transform
  Changelog.md
  libsolutil/CommonData.h
  libyul/optimiser/SSATransform.cpp
  scripts/common/cmdline_helpers.py
  test/cmdlineTests/~bytecode_equivalence_with_unused_contracts/inputs.sol
  test/cmdlineTests/~bytecode_equivalence_with_unused_contracts/test.py
  test/libyul/yulOptimizerTests/ssaTransform/function.yul
Labels: bug :bug:, optimizer

#15025 Fix internal error when using an empty tuple with a ternary operator
  Changelog.md
  libsmtutil/Z3Interface.cpp
  test/libsolidity/smtCheckerTests/operators/ternary_operator_with_functions.sol
  test/libsolidity/smtCheckerTests/operators/ternary_operator_with_tuple.sol
Labels: bug :bug:, smt

#15049 Better error message when consecutive underscores
  libsolidity/analysis/SyntaxChecker.cpp
  test/libsolidity/syntaxTests/parsing/lexer_numbers_with_underscores_decimal_fail.sol
  test/libsolidity/syntaxTests/parsing/lexer_numbers_with_underscores_fixed_fail.sol
  test/libsolidity/syntaxTests/parsing/lexer_numbers_with_underscores_hex_fail.sol
Labels: external contribution :star:

#14944 Reduce default font weight for readability
  docs/_static/css/toggle.css
Labels: documentation :book:, external contribution :star:

#15059 Install python dependencies on buildpack-deps images
  scripts/docker/buildpack-deps/Dockerfile.emscripten
  scripts/docker/buildpack-deps/Dockerfile.ubuntu.clang.ossfuzz
  scripts/docker/buildpack-deps/Dockerfile.ubuntu2004
  scripts/docker/buildpack-deps/Dockerfile.ubuntu2204
  scripts/docker/buildpack-deps/Dockerfile.ubuntu2204.clang
Labels: build system :building_construction:

#15060 Move python dependencies to docker images
  .circleci/config.yml
  scripts/build_emscripten.sh
Labels: build system :building_construction:

#15067 Replace yarn by pnpm and drop perpetual-pools external test
  .circleci/config.yml
  test/externalTests/brink.sh
  test/externalTests/ens.sh
  test/externalTests/perpetual-pools.sh
  test/externalTests/uniswap.sh
Labels: testing :hammer:

#15032 SMTChecker: Parse invariants from SMT-LIB response
  libsmtutil/CHCSmtLib2Interface.cpp
  libsmtutil/CHCSmtLib2Interface.h
  libsmtutil/CMakeLists.txt
  libsmtutil/SMTLib2Interface.cpp
  libsmtutil/SMTLib2Interface.h
  libsmtutil/SMTLib2Parser.cpp
  libsmtutil/SMTLib2Parser.h
  libsolidity/interface/CompilerStack.cpp
  libsolidity/interface/SMTSolverCommand.cpp
  libsolidity/interface/SMTSolverCommand.h
  test/cmdlineTests/model_checker_invariants_contract_eld/args
  test/cmdlineTests/model_checker_invariants_contract_eld/err
  test/cmdlineTests/model_checker_invariants_contract_eld/input.sol
Labels: smt
