Repository argotorg/solidity, pull requests merged in 2024-12, with the labels that each got.

#15558 SMTChecker + CI: Update versions of solvers and test expectations
  .circleci/config.yml
  .circleci/osx_install_dependencies.sh
  CMakeLists.txt
  scripts/build_emscripten.sh
  scripts/pylintrc
  test/libsolidity/smtCheckerTests/types/fixed_bytes_access_3.sol
  test/libsolidity/smtCheckerTests/types/tuple_assignment_array_empty.sol
Labels: :yellow_circle:

#15599 eof: Hide rjumps in yul
  libyul/backends/evm/EVMDialect.cpp
  test/libyul/yulSyntaxTests/eof/rjump_rjumpi.yul
Labels: external contribution :star:, EOF

#15551 Docker: Update Z3 and cvc5 versions in docker images
  scripts/ci/build_emscripten.sh
  scripts/ci/build_ossfuzz.sh
  scripts/ci/docker_upgrade.sh
  scripts/docker/buildpack-deps/Dockerfile.emscripten
  scripts/docker/buildpack-deps/Dockerfile.ubuntu2004
  scripts/docker/buildpack-deps/Dockerfile.ubuntu2404
  scripts/docker/buildpack-deps/Dockerfile.ubuntu2404.clang
Labels: :yellow_circle:

#15607 Fix Yul SSA CFG exporter to use optimized IR
  libsolidity/interface/CompilerStack.cpp
  test/cmdlineTests/standard_yul_cfg_json_export/output.json
  test/cmdlineTests/yul_cfg_json_export/output
Labels: :yellow_circle:

#15560 Yul AST contains dialect
  libsolidity/ast/ASTJsonImporter.cpp
  libsolidity/codegen/CompilerContext.cpp
  libsolidity/codegen/CompilerContext.h
  libsolidity/codegen/ContractCompiler.cpp
  libyul/AST.h
  libyul/AsmAnalysis.cpp
  libyul/AsmAnalysis.h
  libyul/AsmJsonImporter.cpp
  libyul/AsmJsonImporter.h
  libyul/AsmParser.cpp
  libyul/AsmPrinter.cpp
  libyul/AsmPrinter.h
  libyul/CompilabilityChecker.cpp
  libyul/CompilabilityChecker.h
  libyul/Object.cpp
  libyul/Object.h
  libyul/ObjectOptimizer.cpp
  libyul/ObjectParser.cpp
  libyul/YulStack.cpp
  libyul/optimiser/Semantics.cpp
  libyul/optimiser/Semantics.h
  libyul/optimiser/StackCompressor.cpp
  libyul/optimiser/StackCompressor.h
  libyul/optimiser/StackLimitEvader.cpp
  libyul/optimiser/Suite.cpp
  libyul/optimiser/Suite.h
  test/libyul/Common.cpp
  test/libyul/CompilabilityChecker.cpp
  test/libyul/ControlFlowSideEffectsTest.cpp
  test/libyul/FunctionSideEffects.cpp
  test/libyul/KnowledgeBaseTest.cpp
  test/libyul/SSAControlFlowGraphTest.cpp
  test/libyul/YulOptimizerTest.cpp
  test/libyul/YulOptimizerTestCommon.cpp
  test/tools/ossfuzz/StackReuseCodegenFuzzer.cpp
  test/tools/yulopti.cpp
  tools/yulPhaser/Program.cpp
Labels: refactor, :yellow_circle:

#15608 Export liveness information of Yul SSA CFG
  libyul/YulControlFlowGraphExporter.cpp
  libyul/YulControlFlowGraphExporter.h
  libyul/YulStack.cpp
  test/cmdlineTests/standard_yul_cfg_json_export/output.json
  test/cmdlineTests/strict_asm_yul_cfg_json_export/output
  test/cmdlineTests/yul_cfg_json_export/output
Labels: :yellow_circle:

#15616 Remove request about deleting issue template notes
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation :book:, external contribution :star:

#15555 eof: Implement stack height calculation
  libevmasm/Assembly.cpp
  test/cmdlineTests/strict_asm_eof_container_prague/output
  test/cmdlineTests/strict_asm_eof_dataloadn_prague/output
  test/libyul/objectCompiler/eof/256_subcontainers.yul
  test/libyul/objectCompiler/eof/creation_with_immutables.yul
  test/libyul/objectCompiler/eof/dataloadn.yul
  test/libyul/objectCompiler/eof/functions.yul
  test/libyul/objectCompiler/eof/prune_unreferenced_container.yul
  test/libyul/objectCompiler/eof/rjumps.yul
Labels: external contribution :star:, EOF, :yellow_circle:

#15620 eof: Fix legacy `staticcall` error for EOF
  libyul/AsmAnalysis.cpp
  test/libyul/yulSyntaxTests/eof/legacy_calls_in_eof.yul
Labels: external contribution :star:, EOF

#15617 Yul: Change Dialect definition into a class.
  libsolidity/ast/AST.h
  libsolidity/ast/ASTAnnotations.h
  libyul/AST.h
  libyul/AsmJsonConverter.h
  libyul/AsmJsonImporter.h
  libyul/AsmPrinter.h
  libyul/ControlFlowSideEffectsCollector.h
  libyul/Dialect.h
  libyul/Object.h
  libyul/Utilities.h
  libyul/backends/evm/ConstantOptimiser.h
  libyul/optimiser/CommonSubexpressionEliminator.h
  libyul/optimiser/ControlFlowSimplifier.h
  libyul/optimiser/DataFlowAnalyzer.h
  libyul/optimiser/DeadCodeEliminator.h
  libyul/optimiser/Disambiguator.h
  libyul/optimiser/ExpressionInliner.h
  libyul/optimiser/ExpressionSimplifier.h
  libyul/optimiser/ExpressionSplitter.h
  libyul/optimiser/FunctionCallFinder.h
  libyul/optimiser/KnowledgeBase.h
  libyul/optimiser/Metrics.h
  libyul/optimiser/NameDispenser.h
  libyul/optimiser/NameDisplacer.h
  libyul/optimiser/NameSimplifier.h
  libyul/optimiser/OptimiserStep.h
  libyul/optimiser/Semantics.h
  libyul/optimiser/SimplificationRules.h
  libyul/optimiser/StackCompressor.h
  libyul/optimiser/Suite.h
  libyul/optimiser/UnusedAssignEliminator.h
  libyul/optimiser/UnusedPruner.h
  libyul/optimiser/UnusedStoreBase.h
  libyul/optimiser/UnusedStoreEliminator.h
  libyul/optimiser/VarNameCleaner.h
  test/libyul/Common.h
  test/libyul/ControlFlowGraphTest.h
  test/libyul/SSAControlFlowGraphTest.h
  test/libyul/StackLayoutGeneratorTest.h
  test/libyul/YulOptimizerTest.h
  test/libyul/YulOptimizerTestCommon.h
  test/tools/yulInterpreter/Interpreter.h
  tools/yulPhaser/Program.h
Labels: refactor

#15618 Add test::CommonOptions::evmDialect method
  test/Common.cpp
  test/Common.h
  test/libsolidity/MemoryGuardTest.cpp
  test/libyul/ControlFlowSideEffectsTest.cpp
  test/libyul/EVMCodeTransformTest.cpp
  test/libyul/FunctionSideEffects.cpp
  test/libyul/StackShufflingTest.cpp
  test/libyul/YulInterpreterTest.cpp
Labels: refactor

#15633 eof: Temporarily disable assert verifying backward jumps in topologically-sorted code
  libevmasm/Assembly.cpp
Labels: external contribution :star:, EOF

#15638 eof: Disallow `gas` option for external function call.
  libsolidity/analysis/TypeChecker.cpp
  libsolidity/analysis/TypeChecker.h
  libsolidity/interface/CompilerStack.cpp
  test/libsolidity/Assembly.cpp
  test/libsolidity/SolidityExpressionCompiler.cpp
  test/libsolidity/syntaxTests/functionCalls/eof/external_call_with_gas_option.sol
Labels: external contribution :star:, EOF

#15631 Fix tests with byzantium and homestead
  libyul/YulStack.cpp
  libyul/backends/evm/ConstantOptimiser.cpp
  libyul/backends/evm/EVMObjectCompiler.cpp
  libyul/backends/evm/EVMObjectCompiler.h
  test/libyul/EVMCodeTransformTest.cpp
Labels: testing :hammer:

#15635 eof: Add new `EOFCREATE` message kind to EVMHost and enable EOF validation
  test/EVMHost.cpp
  test/ExecutionFramework.cpp
  test/ExecutionFramework.h
  test/contracts/AuctionRegistrar.cpp
  test/contracts/Wallet.cpp
  test/libsolidity/GasMeter.cpp
  test/libsolidity/SolidityEndToEndTest.cpp
  test/libsolidity/SolidityExecutionFramework.h
Labels: external contribution :star:, EOF

#15628 eof: Fix immutables
  libsolidity/codegen/ir/IRGenerationContext.cpp
  libsolidity/codegen/ir/IRGenerationContext.h
  libsolidity/codegen/ir/IRGenerator.cpp
  test/libsolidity/semanticTests/immutable/stub.sol
  test/libyul/yulSyntaxTests/eof/callf_jumpf_retf.yul
Labels: external contribution :star:, EOF

#15634 eof: Update subassembly link references in parent container
  libevmasm/Assembly.cpp
  test/libsolidity/semanticTests/libraries/library_address.sol
Labels: external contribution :star:, EOF

#15611 Unify Yul parsing across test suites
  libyul/YulStack.cpp
  libyul/YulStack.h
  test/libsolidity/MemoryGuardTest.cpp
  test/libyul/Common.cpp
  test/libyul/Common.h
  test/libyul/CompilabilityChecker.cpp
  test/libyul/ControlFlowGraphTest.cpp
  test/libyul/ControlFlowGraphTest.h
  test/libyul/ControlFlowSideEffectsTest.cpp
  test/libyul/EVMCodeTransformTest.cpp
  test/libyul/FunctionSideEffects.cpp
  test/libyul/FunctionSideEffects.h
  test/libyul/KnowledgeBaseTest.cpp
  test/libyul/Metrics.cpp
  test/libyul/ObjectCompilerTest.cpp
  test/libyul/ObjectCompilerTest.h
  test/libyul/ObjectParser.cpp
  test/libyul/SSAControlFlowGraphTest.cpp
  test/libyul/SSAControlFlowGraphTest.h
  test/libyul/StackLayoutGeneratorTest.cpp
  test/libyul/StackLayoutGeneratorTest.h
  test/libyul/SyntaxTest.cpp
  test/libyul/SyntaxTest.h
  test/libyul/YulInterpreterTest.cpp
  test/libyul/YulInterpreterTest.h
  test/libyul/YulOptimizerTest.cpp
  test/libyul/YulOptimizerTest.h
  test/libyul/YulOptimizerTestCommon.cpp
  test/libyul/YulOptimizerTestCommon.h
  test/tools/ossfuzz/yulProtoFuzzer.cpp
  test/tools/ossfuzz/yulProto_diff_ossfuzz.cpp
Labels: testing :hammer:, refactor

#15592 Prune unreferenced functions from CFG
  libyul/backends/evm/ControlFlowGraphBuilder.cpp
  test/libyul/evmCodeTransform/stackReuse/function_argument_reuse.yul
  test/libyul/evmCodeTransform/stackReuse/function_argument_reuse_without_retparams.yul
  test/libyul/evmCodeTransform/stackReuse/function_many_arguments.yul
  test/libyul/evmCodeTransform/stackReuse/function_params.yul
  test/libyul/evmCodeTransform/stackReuse/function_params_and_retparams.yul
  test/libyul/evmCodeTransform/stackReuse/function_params_and_retparams_partly_used.yul
  test/libyul/evmCodeTransform/stackReuse/function_retparam.yul
  test/libyul/evmCodeTransform/stackReuse/function_retparam_block.yul
  test/libyul/evmCodeTransform/stackReuse/function_retparam_declaration.yul
  test/libyul/evmCodeTransform/stackReuse/function_retparam_for.yul
  test/libyul/evmCodeTransform/stackReuse/function_retparam_if.yul
  test/libyul/evmCodeTransform/stackReuse/function_retparam_leave.yul
  test/libyul/evmCodeTransform/stackReuse/function_retparam_read.yul
  test/libyul/evmCodeTransform/stackReuse/function_retparam_unassigned.yul
  test/libyul/evmCodeTransform/stackReuse/function_retparam_unassigned_multiple.yul
  test/libyul/evmCodeTransform/stackReuse/function_trivial.yul
  test/libyul/evmCodeTransform/stackReuse/function_with_body_embedded.yul
  test/libyul/evmCodeTransform/unassigned_return_variable.yul
  test/libyul/objectCompiler/eof/prune_unreachable_function_non_returning.yul
  test/libyul/objectCompiler/eof/prune_unreachable_function_recursion.yul
  test/libyul/objectCompiler/eof/prune_unreferenced_function.yul
  test/libyul/objectCompiler/leading_and_trailing_dots.yul
  test/libyul/objectCompiler/prune_unreachable_function_non_returning.yul
  test/libyul/objectCompiler/prune_unreachable_function_recursion.yul
  test/libyul/objectCompiler/prune_unreferenced_function.yul
  test/libyul/yulControlFlowGraph/function.yul
  test/libyul/yulStackLayout/function.yul
Labels: external contribution :star:

#15654 eof: Update function side effect tests
  .circleci/soltest.sh
  test/libyul/FunctionSideEffects.cpp
  test/libyul/FunctionSideEffects.h
  test/libyul/functionSideEffects/otherImmovables.yul
  test/libyul/functionSideEffects/state.yul
  test/libyul/functionSideEffects/storage.yul
Labels: external contribution :star:, EOF

#15637 eof: Fix constructor argument copying for EOF
  libsolidity/codegen/ABIFunctions.h
  libsolidity/codegen/Compiler.h
  libsolidity/codegen/CompilerContext.h
  libsolidity/codegen/YulUtilFunctions.cpp
  libsolidity/codegen/YulUtilFunctions.h
  libsolidity/codegen/ir/IRGenerationContext.cpp
  libsolidity/codegen/ir/IRGenerator.cpp
  libsolidity/codegen/ir/IRGenerator.h
  libsolidity/codegen/ir/IRGeneratorForStatements.cpp
  libsolidity/interface/CompilerStack.cpp
  test/cmdlineTests/standard_debug_info_in_yul_location/output.json
  test/libsolidity/Assembly.cpp
  test/libsolidity/SolidityExpressionCompiler.cpp
  test/libsolidity/semanticTests/constructor/arrays_in_constructors.sol
  test/libsolidity/semanticTests/constructor/base_constructor_arguments.sol
  test/libsolidity/semanticTests/constructor/bytes_in_constructors_packer.sol
  test/libsolidity/semanticTests/constructor/bytes_in_constructors_unpacker.sol
  test/libsolidity/semanticTests/constructor/constructor_arguments_external.sol
  test/libsolidity/semanticTests/constructor/constructor_arguments_internal.sol
  test/libsolidity/semanticTests/constructor/constructor_function_argument.sol
  test/libsolidity/semanticTests/constructor/constructor_function_complex.sol
  test/libsolidity/semanticTests/constructor/constructor_static_array_argument.sol
  test/libsolidity/semanticTests/constructor/evm_exceptions_in_constructor_call_fail.sol
  test/libsolidity/semanticTests/constructor/function_usage_in_constructor_arguments.sol
  test/libsolidity/semanticTests/constructor/functions_called_by_constructor.sol
  test/libsolidity/semanticTests/constructor/functions_called_by_constructor_through_dispatch.sol
  test/libsolidity/semanticTests/constructor/inline_member_init_inheritence_without_constructor.sol
  test/libsolidity/semanticTests/constructor/order_of_evaluation.sol
  test/libsolidity/semanticTests/constructor/payable_constructor.sol
  test/libsolidity/semanticTests/constructor/store_function_in_constructor.sol
  test/libsolidity/semanticTests/constructor/store_function_in_constructor_packed.sol
  test/libsolidity/semanticTests/constructor/store_internal_unused_function_in_constructor.sol
  test/libsolidity/semanticTests/constructor/store_internal_unused_library_function_in_constructor.sol
  test/libsolidity/semanticTests/constructor/transient_state_variable_initialization.sol
Labels: external contribution :star:, EOF

#15636 eof: Fix stack height calculation for non-returning function.
  libevmasm/Assembly.cpp
  libevmasm/Assembly.h
  libevmasm/AssemblyItem.cpp
  libevmasm/AssemblyItem.h
  libyul/backends/evm/AbstractAssembly.h
  libyul/backends/evm/EthAssemblyAdapter.cpp
  libyul/backends/evm/EthAssemblyAdapter.h
  libyul/backends/evm/NoOutputAssembly.cpp
  libyul/backends/evm/NoOutputAssembly.h
  libyul/backends/evm/OptimizedEVMCodeTransform.cpp
  test/libsolidity/semanticTests/inlineAssembly/inline_assembly_in_modifiers.sol
Labels: external contribution :star:, EOF

#15653 eof: Disable `gasTests` for EOF
  .circleci/soltest.sh
  test/libsolidity/GasTest.cpp
  test/libsolidity/GasTest.h
  test/libsolidity/gasTests/abiv2.sol
  test/libsolidity/gasTests/abiv2_optimised.sol
  test/libsolidity/gasTests/data_storage.sol
  test/libsolidity/gasTests/dispatch_large.sol
  test/libsolidity/gasTests/dispatch_large_optimised.sol
  test/libsolidity/gasTests/dispatch_medium.sol
  test/libsolidity/gasTests/dispatch_medium_optimised.sol
  test/libsolidity/gasTests/dispatch_small.sol
  test/libsolidity/gasTests/dispatch_small_optimised.sol
  test/libsolidity/gasTests/exp.sol
  test/libsolidity/gasTests/exp_optimized.sol
  test/libsolidity/gasTests/storage_costs.sol
Labels: external contribution :star:, EOF

#15664 Remove unused expression annotation
  libsolidity/analysis/TypeChecker.cpp
  libsolidity/analysis/TypeChecker.h
  libsolidity/ast/ASTAnnotations.h
Labels: external contribution :star:

#15667 Fix EOF data section size validation
  libevmasm/Assembly.cpp
  test/libyul/yulInterpreterTests/long_object_name.yul
  test/libyul/yulSyntaxTests/eof/call_instruction_in_eof.yul
Labels: EOF

#15612 Testing code generation errors
  libevmasm/Assembly.cpp
  test/libyul/SyntaxTest.cpp
  test/libyul/yulSyntaxTests/eof/auxdataloadn_in_eof_offset_too_high.yul
  test/libyul/yulSyntaxTests/eof/too_large_code_section.yul
  test/libyul/yulSyntaxTests/loadimmutable_without_setimmutable.yul
Labels: testing :hammer:, has dependencies

#15659 eof: Disable `smtCheckerTests` when compiling to EOF
  test/libsolidity/SMTCheckerTest.cpp
Labels: external contribution :star:, testing :hammer:, smt, EOF

#15657 eof: Disable legacy-specific C++ tests and need to be rewritten for EOF later
  .circleci/soltest.sh
  test/Common.cpp
  test/Common.h
  test/libevmasm/Assembler.cpp
  test/libevmasm/Optimiser.cpp
  test/libsolidity/InlineAssembly.cpp
  test/libsolidity/SolidityCompiler.cpp
  test/libsolidity/ViewPureChecker.cpp
Labels: external contribution :star:, testing :hammer:, EOF
