Repository argotorg/solidity, pull requests merged in 2024-07, with the labels that each got.

#15225 SMTChecker: Simplify CHC predicate representation
  libsmtutil/Z3CHCInterface.cpp
  libsolidity/formal/CHC.cpp
  libsolidity/formal/CHC.h
  libsolidity/formal/Predicate.cpp
  libsolidity/formal/Predicate.h
  test/cmdlineTests/model_checker_invariants_reentrancy/err
  test/cmdlineTests/model_checker_print_query_all/err
  test/cmdlineTests/model_checker_print_query_chc/err
  test/cmdlineTests/standard_model_checker_invariants_reentrancy/output.json
  test/cmdlineTests/standard_model_checker_print_query_all/output.json
  test/cmdlineTests/standard_model_checker_print_query_chc/output.json
  test/cmdlineTests/standard_model_checker_solvers_smtlib2/output.json
  test/libsolidity/smtCheckerTests/deployment/deploy_trusted_flow.sol
  test/libsolidity/smtCheckerTests/external_calls/external_hash_known_code_state_reentrancy_unsafe_trusted.sol
  test/libsolidity/smtCheckerTests/external_calls/underflow_only_in_external_call.sol
  test/libsolidity/smtCheckerTests/operators/index_access_for_bytesNN.sol
  test/libsolidity/smtCheckerTests/operators/index_access_side_effect.sol
  test/libsolidity/smtCheckerTests/operators/slice_access.sol
  test/libsolidity/smtCheckerTests/operators/userDefined/user_defined_operator_matches_equivalent_function_call.sol
  test/libsolidity/smtCheckerTests/out_of_bounds/array_1.sol
  test/libsolidity/smtCheckerTests/types/array_branch_3d.sol
  test/libsolidity/smtCheckerTests/types/array_branches_3d.sol
  test/libsolidity/smtCheckerTests/types/array_branches_3d_show_unproved.sol
  test/libsolidity/smtCheckerTests/types/struct_array_branches_2d.sol
Labels: smt

#15241 SMTChecker: Move formatting methods out of Predicate
  libsolidity/formal/ExpressionFormatter.cpp
  libsolidity/formal/ExpressionFormatter.h
  libsolidity/formal/Predicate.cpp
  libsolidity/formal/Predicate.h
Labels: smt

#15253 Yul: Add const version of FunctionCallFinder
  libyul/backends/evm/EVMObjectCompiler.cpp
  libyul/optimiser/FullInliner.cpp
  libyul/optimiser/FunctionCallFinder.cpp
  libyul/optimiser/FunctionCallFinder.h
  libyul/optimiser/StackLimitEvader.cpp
  test/libsolidity/MemoryGuardTest.cpp
Labels: refactor

#15261 Yul object node names are std string instead of YulString
  libsolidity/interface/StandardCompiler.cpp
  libyul/AsmAnalysis.cpp
  libyul/AsmAnalysis.h
  libyul/Object.cpp
  libyul/Object.h
  libyul/ObjectParser.cpp
  libyul/ObjectParser.h
  libyul/YulStack.cpp
  libyul/backends/evm/EVMDialect.cpp
  libyul/backends/evm/EVMDialect.h
  libyul/backends/evm/EVMObjectCompiler.cpp
  test/libsolidity/MemoryGuardTest.cpp
  tools/yulPhaser/Program.cpp
Labels: refactor

#15256 SMTChecker: Further test simplifications
  test/libsolidity/smtCheckerTests/deployment/deploy_trusted_flow.sol
  test/libsolidity/smtCheckerTests/external_calls/external_hash_known_code_state_reentrancy_indirect_trusted.sol
  test/libsolidity/smtCheckerTests/external_calls/external_inc.sol
  test/libsolidity/smtCheckerTests/external_calls/external_safe.sol
  test/libsolidity/smtCheckerTests/types/array_branches_3d.sol
  test/libsolidity/smtCheckerTests/types/array_branches_3d_show_unproved.sol
  test/libsolidity/smtCheckerTests/types/array_static_mapping_aliasing_1.sol
  test/libsolidity/smtCheckerTests/types/array_static_mapping_aliasing_2.sol
Labels: testing :hammer:, smt

#15275 Downgrade nodejs in base_node_small image to fix CI
  .circleci/config.yml
Labels: testing :hammer:

#15269 Fix isoltest crash when formatting call arguments in a contract whose ABI includes unnamed functions
  test/libsolidity/util/ContractABIUtils.cpp
Labels: testing :hammer:

#15285 Fix docs on outputSelection
  docs/using-the-compiler.rst
Labels: external contribution :star:

#15284 Use latest node cimg
  .circleci/config.yml
Labels: testing :hammer:

#15290 docs/yul: pc is dissalowed in solc yul
  docs/yul.rst
Labels: external contribution :star:

#15301 Add notes about the library ABI differences in the ABI page
  docs/abi-spec.rst
  docs/contracts/libraries.rst
  docs/using-the-compiler.rst
Labels: external contribution :star:

#15288 Docs: Add note about the library placeholder format change in v0.5.0
  docs/contracts/libraries.rst
  docs/using-the-compiler.rst
Labels: external contribution :star:

#15239 SMTChecker: Proper context for SMT-LIB interface
  libsmtutil/BMCSolverInterface.h
  libsmtutil/CHCSmtLib2Interface.cpp
  libsmtutil/CHCSmtLib2Interface.h
  libsmtutil/CHCSolverInterface.h
  libsmtutil/CMakeLists.txt
  libsmtutil/SMTLib2Context.cpp
  libsmtutil/SMTLib2Context.h
  libsmtutil/SMTLib2Interface.cpp
  libsmtutil/SMTLib2Interface.h
  libsmtutil/SMTPortfolio.cpp
  libsmtutil/SMTPortfolio.h
  libsmtutil/SolverInterface.h
  libsmtutil/Z3Interface.cpp
  libsmtutil/Z3Interface.h
  libsolidity/formal/BMC.cpp
  libsolidity/formal/BMC.h
  libsolidity/formal/CHC.cpp
  libsolidity/formal/EldaricaCHCSmtLib2Interface.cpp
  libsolidity/formal/EldaricaCHCSmtLib2Interface.h
  test/cmdlineTests/model_checker_print_query_all/err
  test/cmdlineTests/model_checker_print_query_bmc/err
  test/cmdlineTests/model_checker_print_query_chc/err
  test/cmdlineTests/standard_model_checker_print_query_all/output.json
  test/cmdlineTests/standard_model_checker_print_query_bmc/output.json
  test/cmdlineTests/standard_model_checker_print_query_chc/output.json
  test/cmdlineTests/standard_model_checker_solvers_smtlib2/output.json
  test/libsolidity/smtCheckerTests/invariants/array_access.sol
  test/libsolidity/smtCheckerTests/invariants/struct_access.sol
Labels: smt

#14612 Add --asm-json output in assembler mode
  Changelog.md
  libevmasm/Assembly.cpp
  libsolidity/interface/StandardCompiler.cpp
  libyul/Object.cpp
  libyul/Object.h
  libyul/YulStack.cpp
  libyul/YulStack.h
  solc/CommandLineInterface.cpp
  solc/CommandLineParser.cpp
  test/cmdlineTests/asm_json_import_sourcelist_with_null_elements/args
  test/cmdlineTests/asm_json_import_sourcelist_with_null_elements/err
  test/cmdlineTests/asm_json_import_sourcelist_with_null_elements/exit
  test/cmdlineTests/asm_json_import_sourcelist_with_null_elements/stdin
  test/cmdlineTests/asm_json_yul_export_evm_asm_import/args
  test/cmdlineTests/asm_json_yul_export_evm_asm_import/output
  test/cmdlineTests/asm_json_yul_export_evm_asm_import/stdin
  test/cmdlineTests/strict_asm_asm_json_arbitrary_source_index/args
  test/cmdlineTests/strict_asm_asm_json_arbitrary_source_index/err
  test/cmdlineTests/strict_asm_asm_json_arbitrary_source_index/exit
  test/cmdlineTests/strict_asm_asm_json_arbitrary_source_index/stdin
  test/cmdlineTests/strict_asm_asm_json_subobjects_with_debug/args
  test/cmdlineTests/strict_asm_asm_json_subobjects_with_debug/output
  test/cmdlineTests/strict_asm_asm_json_subobjects_with_debug/stdin
  test/cmdlineTests/strict_asm_asm_json_with_debug_info_annotations/args
  test/cmdlineTests/strict_asm_asm_json_with_debug_info_annotations/output
  test/cmdlineTests/strict_asm_asm_json_with_debug_info_annotations/stdin
  test/cmdlineTests/strict_asm_asm_json_without_debug_info_annotations/args
  test/cmdlineTests/strict_asm_asm_json_without_debug_info_annotations/output
  test/cmdlineTests/strict_asm_asm_json_without_debug_info_annotations/stdin
  test/cmdlineTests/strict_asm_asm_json_yul_verbatim/args
  test/cmdlineTests/strict_asm_asm_json_yul_verbatim/output
  test/cmdlineTests/strict_asm_asm_json_yul_verbatim/stdin
  test/cmdlineTests/strict_asm_output_selection_invalid/err
  test/libyul/ObjectCompilerTest.cpp
  test/libyul/objectCompiler/sourceLocations.yul
  test/solc/CommandLineParser.cpp
Labels: feature
