Repository argotorg/solidity, pull requests merged in 2024-05, with the labels that each got.

#15064 Update cheatsheet.rst
  docs/cheatsheet.rst
Labels: external contribution :star:

#15081 Mark embedding options as advanced.
  CMakeLists.txt
Labels: build system :building_construction:

#15050 SMTChecker: Fix equality of array literals
  Changelog.md
  libsolidity/formal/SMTEncoder.cpp
  test/cmdlineTests/model_checker_invariants_all/err
  test/cmdlineTests/model_checker_invariants_contract_reentrancy/err
  test/libsolidity/smtCheckerTests/abi/abi_encode_packed_string_literal.sol
  test/libsolidity/smtCheckerTests/abi/abi_encode_packed_string_literal_no_unproved.sol
  test/libsolidity/smtCheckerTests/abi/abi_encode_string_literal.sol
  test/libsolidity/smtCheckerTests/abi/abi_encode_with_selector_string_literal.sol
  test/libsolidity/smtCheckerTests/abi/abi_encode_with_sig_array_slice.sol
  test/libsolidity/smtCheckerTests/abi/abi_encode_with_sig_array_slice_2.sol
  test/libsolidity/smtCheckerTests/abi/abi_encode_with_sig_string_literal.sol
  test/libsolidity/smtCheckerTests/crypto/crypto_functions_same_array.sol
  test/libsolidity/smtCheckerTests/crypto/crypto_functions_same_string_literal.sol
  test/libsolidity/smtCheckerTests/external_calls/call_mutex_unsafe.sol
  test/libsolidity/smtCheckerTests/types/array_literal_3.sol
Labels: smt

#15053 Style corrections in Yul Optimizer docs
  docs/internals/optimizer.rst
Labels: documentation :book:

#15090 Fix python version for Windows builds
  .circleci/config.yml
Labels: testing :hammer:

#15089 Fix breakage in Arch Linux build due to a `std::optional` bug in GCC 13+ by disabling one of the yul-phaser's tests
  test/yulPhaser/AlgorithmRunner.cpp
Labels: testing :hammer:

#14854 Remove superfluous initial iteration of repeating parts of optimizer sequence
  Changelog.md
  libyul/optimiser/Suite.cpp
  test/cmdlineTests/optimizer_user_yul/output
  test/libsolidity/semanticTests/array/copying/array_elements_to_mapping.sol
  test/libsolidity/semanticTests/array/copying/array_to_mapping.sol
  test/libsolidity/semanticTests/array/copying/calldata_array_to_mapping.sol
  test/libsolidity/semanticTests/array/copying/elements_of_nested_array_of_structs_calldata_to_storage.sol
  test/libsolidity/semanticTests/array/copying/elements_of_nested_array_of_structs_memory_to_storage.sol
  test/libsolidity/semanticTests/array/copying/nested_array_of_structs_calldata_to_storage.sol
  test/libsolidity/semanticTests/array/copying/nested_array_of_structs_memory_to_storage.sol
  test/libsolidity/semanticTests/array/copying/storage_memory_packed_dyn.sol
  test/libsolidity/semanticTests/externalContracts/deposit_contract.sol
  test/libsolidity/semanticTests/externalContracts/snark.sol
  test/libsolidity/semanticTests/functionCall/gas_and_value_basic.sol
  test/libsolidity/semanticTests/functionCall/gas_and_value_brace_syntax.sol
  test/libsolidity/semanticTests/libraries/internal_types_in_library.sol
  test/libsolidity/semanticTests/structs/copy_substructures_from_mapping.sol
  test/libsolidity/semanticTests/structs/copy_substructures_to_mapping.sol
  test/libsolidity/semanticTests/structs/copy_to_mapping.sol
  test/libsolidity/semanticTests/types/mapping/copy_from_mapping_to_mapping.sol
  test/libsolidity/semanticTests/userDefinedValueType/calldata.sol
  test/libsolidity/semanticTests/various/skip_dynamic_types_for_structs.sol
  test/libyul/yulOptimizerTests/fullSuite/unusedFunctionParameterPruner_loop.yul
Labels: performance :racehorse:, optimizer

#15100 Update bytecode size test for byzantium.
  test/libsolidity/syntaxTests/sizeLimits/bytecode_too_large_byzantium.sol
Labels: testing :hammer:

#15098 Remove bzzr entries from static binary section in the docs
  docs/installing-solidity.rst
Labels: documentation :book:, has dependencies

#15103 Add the missing changelog entry for the new default optimizer sequence
  Changelog.md
Labels: documentation :book:

#15107 Update PPA release script.
  scripts/deps-ppa/static_z3.sh
  scripts/release_ppa.sh
Labels: build system :building_construction:

#15110 Remove `using namespace std` from testing tools, ossfuzz and yulPhaser
  scripts/check_style.sh
  test/tools/afl_fuzzer.cpp
  test/tools/fuzzer_common.cpp
  test/tools/isoltest.cpp
  test/tools/ossfuzz/AbiV2IsabelleFuzzer.cpp
  test/tools/ossfuzz/SolidityCustomMutatorInterface.cpp
  test/tools/ossfuzz/SolidityEvmoneInterface.cpp
  test/tools/ossfuzz/SolidityGenerator.cpp
  test/tools/ossfuzz/StackReuseCodegenFuzzer.cpp
  test/tools/ossfuzz/abiV2ProtoFuzzer.cpp
  test/tools/ossfuzz/const_opt_ossfuzz.cpp
  test/tools/ossfuzz/protoToAbiV2.cpp
  test/tools/ossfuzz/protoToSol.cpp
  test/tools/ossfuzz/protoToYul.cpp
  test/tools/ossfuzz/protomutators/YulProtoMutator.cpp
  test/tools/ossfuzz/solProtoFuzzer.cpp
  test/tools/ossfuzz/solc_ossfuzz.cpp
  test/tools/ossfuzz/strictasm_assembly_ossfuzz.cpp
  test/tools/ossfuzz/strictasm_diff_ossfuzz.cpp
  test/tools/ossfuzz/strictasm_opt_ossfuzz.cpp
  test/tools/ossfuzz/yulFuzzerCommon.cpp
  test/tools/ossfuzz/yulProtoFuzzer.cpp
  test/tools/ossfuzz/yulProto_diff_ossfuzz.cpp
  test/tools/yulopti.cpp
  test/tools/yulrun.cpp
  tools/yulPhaser/AlgorithmRunner.cpp
  tools/yulPhaser/Chromosome.cpp
  tools/yulPhaser/Common.cpp
  tools/yulPhaser/FitnessMetrics.cpp
  tools/yulPhaser/GeneticAlgorithms.cpp
  tools/yulPhaser/Mutations.cpp
  tools/yulPhaser/PairSelections.cpp
  tools/yulPhaser/Phaser.cpp
  tools/yulPhaser/Population.cpp
  tools/yulPhaser/Program.cpp
  tools/yulPhaser/ProgramCache.cpp
  tools/yulPhaser/Selections.cpp
  tools/yulPhaser/SimulationRNG.cpp
Labels: external contribution :star:, refactor

#15109 Update license template.
  cmake/templates/license.h.in
Labels: documentation :book:

#15115 Remove included directories check for using std
  scripts/check_style.sh
Labels: testing :hammer:

#15121 Add `stopAfter` setting to syntax tests
  test/libsolidity/SyntaxTest.cpp
  test/libsolidity/SyntaxTest.h
  test/libsolidity/syntaxTests/stopAfterAnalysisError.sol
  test/libsolidity/syntaxTests/stopAfterParsingAnalysisErrorNotShowing.sol
  test/libsolidity/syntaxTests/stopAfterParsingError.sol
Labels: testing :hammer:

#15130 Add exclusion for code that compiles only via IR to `docs_version_pragma_check` script
  scripts/docs_version_pragma_check.sh
Labels: testing :hammer:

#15119 Update ossfuzz's README.md
  test/tools/ossfuzz/README.md
Labels: external contribution :star:

#15146 SMTChecker: Add SMTShowProvedSafe option for use in SMT checker tests
  scripts/error_codes.py
  test/libsolidity/SMTCheckerTest.cpp
  test/libsolidity/SMTCheckerTest.h
  test/libsolidity/smtCheckerTests/operators/compound_add.sol
Labels: low impact, smt

#15135 SMTChecker: Add CHC engine check for underflow and overflow in unary minus operation
  Changelog.md
  libsolidity/formal/CHC.cpp
  test/libsolidity/smtCheckerTests/control_flow/branches_with_return/constructor_state_variable_init.sol
  test/libsolidity/smtCheckerTests/inheritance/constructor_state_variable_init_asserts.sol
  test/libsolidity/smtCheckerTests/inheritance/constructor_state_variable_init_chain_tree.sol
  test/libsolidity/smtCheckerTests/operators/mod.sol
  test/libsolidity/smtCheckerTests/operators/mod_signed.sol
  test/libsolidity/smtCheckerTests/operators/unary_minus_bmc.sol
  test/libsolidity/smtCheckerTests/operators/unary_minus_chc.sol
  test/libsolidity/smtCheckerTests/operators/userDefined/user_defined_operations_on_constants.sol
  test/libsolidity/smtCheckerTests/operators/userDefined/user_defined_operations_on_constants_fail.sol
  test/libsolidity/smtCheckerTests/operators/userDefined/user_defined_operator_matches_equivalent_function_call.sol
  test/libsolidity/smtCheckerTests/unchecked/flipping_sign_tests.sol
Labels: smt

#15140 Release checklist update after 0.8.26
  ReleaseChecklist.md
Labels: documentation :book:

#15148 Move type() helper function from TypeChecker to ASTUtils
  libsolidity/analysis/TypeChecker.cpp
  libsolidity/analysis/TypeChecker.h
  libsolidity/ast/ASTUtils.cpp
  libsolidity/ast/ASTUtils.h
Labels: refactor

#15131 test for unlimited string literal in IR via yul
  test/libyul/yulOptimizerTests/commonSubexpressionEliminator/long_literals_as_builtin_args.yul
Labels: testing :hammer:

#15149 Prevent NameSimplifier and VarNameCleaner from producing Yul identifiers with leading and trailing dots
  Changelog.md
  libyul/optimiser/OptimizerUtilities.cpp
  test/libyul/objectCompiler/leading_and_trailing_dots.yul
Labels: optimizer

#15159 Update style-guide.rst
  docs/style-guide.rst
Labels: external contribution :star:

#15151 Add authentication header to circleci api
  .circleci/config.yml
  scripts/common/rest_api_helpers.py
  scripts/externalTests/download_benchmarks.py
  test/scripts/test_externalTests_benchmark_downloader.py
Labels: testing :hammer:

#15161 Assembly is used for libraries or gas optimization
  docs/assembly.rst
Labels: documentation :book:, external contribution :star:
