Repository argotorg/solidity, pull requests merged in 2024-03, with the labels that each got.

#14904 [test] Fix python snippet causing "SyntaxWarning" in Scanner.
  test/cmdlineTests.sh
Labels: testing :hammer:

#14908 Remove duplicate word from a comment in `yulInterpreterTests/mcopy.yul`
  test/libyul/yulInterpreterTests/mcopy.yul
Labels: external contribution :star:

#14916 Convert disabled external tests to compile-only
  .circleci/config.yml
  test/externalTests/bleeps.sh
  test/externalTests/gp2.sh
Labels: testing :hammer:

#14920 Reorder `assertThrow` statements and add one to the `MCOPY` case in `SemanticInformation`
  libevmasm/SemanticInformation.cpp
Labels: external contribution :star:

#14831 Separate nightly-ossfuzz workflow from nightly workflow
  .circleci/config.yml
Labels: build system :building_construction:

#14710 Move deprecated evm versions to nightly CI workflow
  .circleci/config.yml
  .circleci/soltest_all.sh
Labels: build system :building_construction:

#14923 Fix typos in comments
  libevmasm/GasMeter.h
  libevmasm/Inliner.cpp
  libsolidity/parsing/Parser.h
Labels: external contribution :star:

#14922 [solutil] Add missing include guard.
  libsolutil/cxx20.h
Labels: refactor

#14927 Fix typos
  docs/smtchecker.rst
  test/compilationTests/corion/ico.sol
Labels: documentation :book:, external contribution :star:

#14932 Add hardhat networks settings external tests
  .circleci/config.yml
  scripts/externalTests/common.sh
  test/externalTests/brink.sh
  test/externalTests/elementfi.sh
  test/externalTests/gnosis.sh
  test/externalTests/pool-together.sh
Labels: testing :hammer:

#14935 Add missing test about transient storage warning
  test/libsolidity/syntaxTests/inlineAssembly/tstore_warning_only_once_multiple_sources.sol
Labels: testing :hammer:

#14936 Use move ctor instead of copy ctor in stringOrDefault
  libsolutil/Assertions.h
Labels: external contribution :star:

#14938 Use specific hardhat version on openzeppelin and gp2 external tests
  .circleci/config.yml
  test/externalTests/gp2.sh
  test/externalTests/zeppelin.sh
Labels: testing :hammer:

#14947 Drop Ubuntu Lunar Lobster from distribution list in PPA scripts
  scripts/deps-ppa/static_z3.sh
  scripts/release_ppa.sh
Labels: build system :building_construction:

#14952 Remove redundant word
  libsolidity/codegen/ir/Common.h
Labels: external contribution :star:
