Repository argotorg/solidity, pull requests merged in 2024-02, with the labels that each got.

#14788 solidity grammar: add a new rule `usingAliases` for `usingDirective`
  docs/grammar/SolidityParser.g4
Labels: external contribution :star:

#14835 Remove dynamic byte arrays from value types section
  docs/types/value-types.rst
Labels: documentation :book:

#14846 Remove sha from foundry release tag
  .circleci/config.yml
Labels: testing :hammer:

#14844 Allow enforcing gas expectations with non-standard settings
  test/Common.cpp
  test/soltest.cpp
  test/tools/isoltest.cpp
Labels: testing :hammer:

#14862 [test] Add /usr/local/lib to search paths on macOS.
  test/Common.cpp
Labels: testing :hammer:

#14867 Use ethers version 6.11.0 on openzeppelin external tests
  test/externalTests/zeppelin.sh
Labels: testing :hammer:

#14772 Clean up and document gas tiers
  libevmasm/Assembly.cpp
  libevmasm/GasMeter.cpp
  libevmasm/GasMeter.h
  libevmasm/Instruction.cpp
  libevmasm/Instruction.h
  libsolidity/interface/CompilerStack.cpp
  solc/CommandLineInterface.cpp
Labels: refactor

#14778 Purge using namespace std from test
  scripts/check_style.sh
  test/Common.cpp
  test/CommonSyntaxTest.cpp
  test/EVMHost.cpp
  test/ExecutionFramework.cpp
  test/FilesystemUtils.cpp
  test/Metadata.cpp
  test/TestCase.cpp
  test/TestCaseReader.cpp
  test/soltest.cpp
Labels: refactor

#14864 Convert tagPos to a size for address size computation
  Changelog.md
  libevmasm/Assembly.cpp
  test/cmdlineTests/function_debug_info/output
  test/cmdlineTests/linking_standard_solidity_unresolved_references/output.json
  test/libsolidity/GasCosts.cpp
  test/libsolidity/semanticTests/arithmetics/check_var_init.sol
  test/libsolidity/semanticTests/array/constant_var_as_array_length.sol
  test/libsolidity/semanticTests/array/copying/cleanup_during_multi_element_per_slot_copy.sol
  test/libsolidity/semanticTests/array/fixed_arrays_in_constructors.sol
  test/libsolidity/semanticTests/array/reusing_memory.sol
  test/libsolidity/semanticTests/byte_array_to_storage_cleanup.sol
  test/libsolidity/semanticTests/constructor/arrays_in_constructors.sol
  test/libsolidity/semanticTests/constructor/bytes_in_constructors_packer.sol
  test/libsolidity/semanticTests/constructor/bytes_in_constructors_unpacker.sol
  test/libsolidity/semanticTests/constructor/constructor_arguments_external.sol
  test/libsolidity/semanticTests/constructor/constructor_static_array_argument.sol
  test/libsolidity/semanticTests/constructor_inheritance_init_order.sol
  test/libsolidity/semanticTests/constructor_inheritance_init_order_2.sol
  test/libsolidity/semanticTests/constructor_with_params.sol
  test/libsolidity/semanticTests/constructor_with_params_diamond_inheritance.sol
  test/libsolidity/semanticTests/constructor_with_params_inheritance.sol
  test/libsolidity/semanticTests/events/event_emit_from_other_contract.sol
  test/libsolidity/semanticTests/externalContracts/FixedFeeRegistrar.sol
  test/libsolidity/semanticTests/externalContracts/base64.sol
  test/libsolidity/semanticTests/externalContracts/deposit_contract.sol
  test/libsolidity/semanticTests/externalContracts/prbmath_signed.sol
  test/libsolidity/semanticTests/externalContracts/prbmath_unsigned.sol
  test/libsolidity/semanticTests/externalContracts/ramanujan_pi.sol
  test/libsolidity/semanticTests/externalContracts/strings.sol
  test/libsolidity/semanticTests/functionCall/creation_function_call_with_args.sol
  test/libsolidity/semanticTests/functionCall/creation_function_call_with_salt.sol
  test/libsolidity/semanticTests/functionCall/gas_and_value_basic.sol
  test/libsolidity/semanticTests/functionCall/gas_and_value_brace_syntax.sol
  test/libsolidity/semanticTests/functionCall/send_zero_ether.sol
  test/libsolidity/semanticTests/immutable/use_scratch.sol
  test/libsolidity/semanticTests/inheritance/member_notation_ctor.sol
  test/libsolidity/semanticTests/inheritance/value_for_constructor.sol
  test/libsolidity/semanticTests/isoltestTesting/balance_other_contract.sol
  test/libsolidity/semanticTests/salted_create/prediction_example.sol
  test/libsolidity/semanticTests/salted_create/salted_create_with_value.sol
  test/libsolidity/semanticTests/smoke/constructor.sol
  test/libsolidity/semanticTests/state/blockhash_basic.sol
  test/libsolidity/semanticTests/userDefinedValueType/erc20.sol
  test/libsolidity/semanticTests/various/code_length.sol
  test/libsolidity/semanticTests/various/erc20.sol
  test/libsolidity/semanticTests/various/negative_stack_height.sol
  test/libsolidity/semanticTests/various/selfdestruct_pre_cancun_multiple_beneficiaries.sol
  test/libsolidity/semanticTests/various/selfdestruct_pre_cancun_redeploy.sol
  test/libsolidity/semanticTests/various/senders_balance.sol
  test/libsolidity/semanticTests/various/value_complex.sol
  test/libsolidity/semanticTests/various/value_insane.sol
  test/libsolidity/syntaxTests/sizeLimits/combined_too_large_shanghai.sol
  test/libsolidity/syntaxTests/sizeLimits/initcode_too_large_shanghai.sol
Labels: external contribution :star:

#14873 Force install python3.12 for Window bytecode compare job
  .circleci/config.yml
Labels: build system :building_construction:

#14875 Build hardhat from latest release in t_ems_ext_hardhat
  .circleci/config.yml
Labels: testing :hammer:

#14842 More robust error handling and improved formatting in `gas_diff_stats.py`
  .circleci/config.yml
  scripts/gas_diff_stats.py
  test/scripts/test_gas_diff_stats.py
Labels: testing :hammer:

#14880 Use latest release instead of main branch on external tests
  scripts/externalTests/common.sh
  scripts/externalTests/runners/base.py
  scripts/externalTests/test_helpers.py
  test/externalTests/bleeps.sh
  test/externalTests/brink.sh
  test/externalTests/chainlink.sh
  test/externalTests/colony.sh
  test/externalTests/elementfi.sh
  test/externalTests/ens.sh
  test/externalTests/euler.sh
  test/externalTests/gnosis.sh
  test/externalTests/gp2.sh
  test/externalTests/perpetual-pools.sh
  test/externalTests/pool-together.sh
  test/externalTests/prb-math.py
  test/externalTests/trident.sh
  test/externalTests/uniswap.sh
  test/externalTests/yield-liquidator.sh
  test/externalTests/zeppelin.sh
Labels: testing :hammer:

#14882 Use CircleCI rust+node convenience image for t_ems_ext_hardhat job
  .circleci/config.yml
Labels: testing :hammer:

#14881 Fix `detect_hardhat_artifact_dir` in externalTests scripts
  scripts/externalTests/common.sh
  test/externalTests/ens.sh
Labels: testing :hammer:

#14806 Yul fuzzer: Support blobhash(uint) global function
  test/tools/ossfuzz/protoToYul.cpp
  test/tools/ossfuzz/yulProto.proto
Labels: testing :hammer:, stale

#14668 `forall` quantifier and mandatory declarations for type variables in new analysis
  liblangutil/Token.h
  libsolidity/analysis/NameAndTypeResolver.cpp
  libsolidity/ast/AST.h
  libsolidity/ast/ASTAnnotations.h
  libsolidity/ast/ASTForward.h
  libsolidity/ast/ASTVisitor.h
  libsolidity/ast/AST_accept.h
  libsolidity/experimental/analysis/TypeInference.cpp
  libsolidity/experimental/analysis/TypeInference.h
  libsolidity/parsing/Parser.cpp
  libsolidity/parsing/Parser.h
  test/libsolidity/syntaxTests/experimental/forall/undeclared_type_variable_in_function.sol
  test/libsolidity/syntaxTests/experimental/forall/undeclared_type_variable_in_quantified_function.sol
  test/libsolidity/syntaxTests/experimental/forall/undeclared_type_variable_in_type_class.sol
  test/libsolidity/syntaxTests/experimental/inference/polymorphic_function_call.sol
  test/libsolidity/syntaxTests/experimental/inference/polymorphic_type.sol
  test/libsolidity/syntaxTests/experimental/inference/type_variable_multi_use_function_parameter_and_return.sol
  test/libsolidity/syntaxTests/experimental/inference/type_variable_multi_use_function_parameters.sol
  test/libsolidity/syntaxTests/experimental/parsing/forall_free_function.sol
  test/libsolidity/syntaxTests/experimental/parsing/forall_free_function_no_type_var.sol
  test/libsolidity/syntaxTests/experimental/parsing/forall_free_function_with_sorts.sol
  test/libsolidity/syntaxTests/experimental/parsing/forall_type_class.sol
  test/libsolidity/syntaxTests/experimental/parsing/forall_type_class_instantiation.sol
Labels: experimental

#14888 Sort results by average change in `gas_diff_stats.py`
  scripts/gas_diff_stats.py
Labels: testing :hammer:

#14890 SMTCommand: Remember to flush query before calling solver
  Changelog.md
  libsolidity/interface/SMTSolverCommand.cpp
Labels: smt

#14884 Fix typos
  docs/introduction-to-smart-contracts.rst
Labels: external contribution :star:

#14147 docs: Replace references to "mining" with "attestation"
  docs/introduction-to-smart-contracts.rst
Labels: documentation :book:, external contribution :star:, takeover

#14876 Fix typos in variable names and comment
  libyul/optimiser/StackCompressor.cpp
  test/compilationTests/corion/ico.sol
  test/libsolidity/smtCheckerTests/imports/import_base.sol
Labels: external contribution :star:

#14267 Update natspec-format.rst : Added structs and enums to Tags
  docs/natspec-format.rst
Labels: documentation :book:, external contribution :star:, takeover
