Repository argotorg/solidity, pull requests merged in 2024-08, with the labels that each got.

#15322 Fix SMT logic error when assigning to an array of contracts or functions
  Changelog.md
  libsolidity/formal/SymbolicTypes.cpp
  test/libsolidity/smtCheckerTests/types/array_of_contracts.sol
  test/libsolidity/smtCheckerTests/types/array_of_functions.sol
Labels: bug :bug:, smt

#15328 fix typo in micropayment.rst
  docs/examples/micropayment.rst
Labels: external contribution :star:

#15246 OptimizedEVMCodeTransform: tag source location in stack too deep errors in yul
  libyul/backends/evm/OptimizedEVMCodeTransform.cpp
Labels: external contribution :star:

#14981 Pass vector of SMT expressions to SymbolicFunctionVariable function operator by const ref instead of by value.
  libsolidity/formal/SymbolicVariables.cpp
  libsolidity/formal/SymbolicVariables.h
Labels: external contribution :star:

#15335 Typo in ContractCompiler.cpp
  libsolidity/codegen/ContractCompiler.cpp
Labels: external contribution :star:

#15345 SMTChecker: Translate bitvector constants properly
  libsmtutil/CHCSmtLib2Interface.cpp
Labels: :yellow_circle:

#15357 Change `toBigEndian` interface to support rvalue ref.
  libsolutil/Numeric.h
Labels: external contribution :star:

#15360 Fix typo in function name in `semanticTests/array/array_storage_index_zeroed_test.sol`
  test/libsolidity/semanticTests/array/array_storage_index_zeroed_test.sol
Labels: external contribution :star:, testing :hammer:

#15348 SMTChecker: Introduce first draft of Z3CHCSmtlib2Interface
  libsmtutil/CHCSmtLib2Interface.cpp
  libsolidity/formal/Z3CHCSmtLib2Interface.cpp
  libsolidity/formal/Z3CHCSmtLib2Interface.h
Labels: :yellow_circle:

#15304 Docs: Fix showProvedSafe flag and JSON key name
  docs/smtchecker.rst
  docs/using-the-compiler.rst
Labels: documentation :book:, external contribution :star:

#15180 [experimental] Export yul cfg to json
  libsolidity/interface/CompilerStack.cpp
  libsolidity/interface/CompilerStack.h
  libsolidity/interface/StandardCompiler.cpp
  libyul/CMakeLists.txt
  libyul/YulControlFlowGraphExporter.cpp
  libyul/YulControlFlowGraphExporter.h
  libyul/YulStack.cpp
  libyul/YulStack.h
  solc/CommandLineInterface.cpp
  solc/CommandLineInterface.h
  solc/CommandLineParser.cpp
  solc/CommandLineParser.h
  test/solc/CommandLineParser.cpp
Labels: has dependencies, epic, :yellow_circle:

#14849 [DOCS] Updating copyright year to 2024
  docs/conf.py
Labels: documentation :book:, external contribution :star:

#15375 Propagate `AssemblyException` message
  libsolidity/interface/CompilerStack.cpp
Labels: :yellow_circle:

#15376 Bump min Boost dependency to 1.67
  cmake/EthDependencies.cmake
  docs/installing-solidity.rst
Labels: build system :building_construction:, :yellow_circle:
