Repository argotorg/solidity, pull requests merged in 2024-06, with the labels that each got.

#15145 Fix segfault in nested tuple to tuple assignments
  Changelog.md
  libsolidity/analysis/StaticAnalyzer.cpp
  libsolidity/analysis/StaticAnalyzer.h
  libsolidity/analysis/TypeChecker.cpp
  libsolidity/analysis/TypeChecker.h
  test/libsolidity/syntaxTests/tupleAssignments/nested_tuple_to_tuple_assignment.sol
Labels: bug :bug:, refactor

#15175 Fix a typo in the `--ast-compact-json` command line flag on the list of breaking changes
  docs/080-breaking-changes.rst
Labels: documentation :book:, external contribution :star:

#15184 Fix several typos in code comments
  libsolidity/formal/BMC.cpp
  libsolutil/CommonData.h
  libyul/AsmParser.h
Labels: external contribution :star:, refactor

#15102 Install cvc5 in buildpack-deps
  .circleci/osx_install_dependencies.sh
  scripts/docker/buildpack-deps/Dockerfile.emscripten
  scripts/docker/buildpack-deps/Dockerfile.ubuntu.clang.ossfuzz
  scripts/docker/buildpack-deps/Dockerfile.ubuntu2004
  scripts/docker/buildpack-deps/Dockerfile.ubuntu2204
  scripts/docker/buildpack-deps/Dockerfile.ubuntu2204.clang
Labels: build system :building_construction:

#15185 Replace unnecessary validations with assertions
  libsolidity/analysis/NameAndTypeResolver.cpp
  libsolidity/codegen/ExpressionCompiler.cpp
  libsolidity/codegen/LValue.cpp
  libsolidity/interface/CompilerStack.cpp
  libsolidity/interface/FileReader.cpp
  libsolidity/interface/SMTSolverCommand.cpp
  libsolidity/interface/StandardCompiler.cpp
  libsolidity/parsing/Parser.cpp
  libyul/AsmAnalysis.cpp
  libyul/AsmParser.cpp
  libyul/ObjectParser.cpp
  test/libyul/yulSyntaxTests/more_than_256_analysis_errors.yul
Labels: refactor

#15186 Remove overly specific handlers for unexpected exceptions
  libsolidity/interface/CompilerStack.cpp
  libsolidity/interface/FileReader.cpp
  libsolidity/interface/SMTSolverCommand.cpp
  libsolidity/interface/StandardCompiler.cpp
  libsolidity/lsp/FileRepository.cpp
  solc/CommandLineInterface.cpp
  test/libsolidity/InlineAssembly.cpp
  test/libsolidity/SolidityExpressionCompiler.cpp
  test/libyul/ObjectParser.cpp
  test/libyul/Parser.cpp
  test/soltest.cpp
  test/tools/fuzzer_common.cpp
  test/tools/isoltest.cpp
Labels: refactor

#15204 SMTChecker: Bring back assertions in "external_calls" SMTChecker tests
  docs/contributing.rst
  docs/installing-solidity.rst
  libsolidity/interface/SMTSolverCommand.cpp
  libsolidity/interface/SMTSolverCommand.h
  libsolidity/interface/UniversalCallback.h
  test/libsolidity/SMTCheckerTest.cpp
  test/libsolidity/SMTCheckerTest.h
  test/libsolidity/smtCheckerTests/external_calls/call_with_value_3.sol
  test/libsolidity/smtCheckerTests/external_calls/external_call_with_value_1.sol
  test/libsolidity/smtCheckerTests/external_calls/external_hash_known_code_state_reentrancy.sol
  test/libsolidity/smtCheckerTests/external_calls/external_reentrancy_3.sol
  test/libsolidity/smtCheckerTests/external_calls/mutex_f_no_guard.sol
Labels: smt
