Repository argotorg/solidity, pull requests merged in 2024-10, with the labels that each got.

#15409 Documentation for transient storage
  docs/assembly.rst
  docs/contracts.rst
  docs/contracts/constant-state-variables.rst
  docs/contracts/functions.rst
  docs/contracts/transient-storage.rst
  docs/internals/layout_in_storage.rst
  docs/introduction-to-smart-contracts.rst
  docs/structure-of-a-contract.rst
  docs/types/reference-types.rst
  docs/types/value-types.rst
Labels: documentation :book:

#15433 Per-contract output selection in `CompilerStack`
  Changelog.md
  libsolidity/interface/CompilerStack.cpp
  libsolidity/interface/CompilerStack.h
  libsolidity/interface/StandardCompiler.cpp
  solc/CommandLineInterface.cpp
  test/libsolidity/SolidityExecutionFramework.cpp
Labels: performance :racehorse:, :yellow_circle:

#15467 eof: Pass `eofVersion` flag to `EVMDialect`
  liblangutil/EVMVersion.cpp
  liblangutil/EVMVersion.h
  libsolidity/ast/ASTJsonExporter.cpp
  libsolidity/ast/ASTJsonImporter.cpp
  libsolidity/ast/ASTJsonImporter.h
  libsolidity/codegen/CompilerContext.cpp
  libsolidity/codegen/ContractCompiler.cpp
  libsolidity/interface/CompilerStack.cpp
  libsolidity/parsing/Parser.cpp
  libsolidity/parsing/Parser.h
  libyul/AsmAnalysis.cpp
  libyul/ObjectOptimizer.cpp
  libyul/ObjectOptimizer.h
  libyul/YulStack.cpp
  libyul/backends/evm/AsmCodeGen.cpp
  libyul/backends/evm/AsmCodeGen.h
  libyul/backends/evm/EVMDialect.cpp
  libyul/backends/evm/EVMDialect.h
  libyul/backends/evm/NoOutputAssembly.cpp
  test/libsolidity/Assembly.cpp
  test/libsolidity/MemoryGuardTest.cpp
  test/libsolidity/SolidityExpressionCompiler.cpp
  test/libsolidity/SolidityParser.cpp
  test/libyul/Common.cpp
  test/libyul/Common.h
  test/libyul/CompilabilityChecker.cpp
  test/libyul/ControlFlowGraphTest.cpp
  test/libyul/ControlFlowSideEffectsTest.cpp
  test/libyul/EVMCodeTransformTest.cpp
  test/libyul/FunctionSideEffects.cpp
  test/libyul/KnowledgeBaseTest.cpp
  test/libyul/ObjectParser.cpp
  test/libyul/Parser.cpp
  test/libyul/SSAControlFlowGraphTest.cpp
  test/libyul/StackLayoutGeneratorTest.cpp
  test/libyul/SyntaxTest.cpp
  test/libyul/YulInterpreterTest.cpp
  test/libyul/YulOptimizerTest.cpp
  test/tools/ossfuzz/StackReuseCodegenFuzzer.cpp
  test/tools/ossfuzz/strictasm_diff_ossfuzz.cpp
  test/tools/ossfuzz/yulProtoFuzzer.cpp
  test/tools/ossfuzz/yulProto_diff_ossfuzz.cpp
  test/tools/yulopti.cpp
  test/tools/yulrun.cpp
  tools/yulPhaser/Program.cpp
Labels: external contribution :star:, EOF

#15461 Replace Hardhat with EDR in CI
  .circleci/config.yml
Labels: external contribution :star:, testing :hammer:

#15475 Re-enable cxx20 job
  .circleci/config.yml
Labels: build system :building_construction:

#15484 Disable legacy presets in zeppelin external test
  test/externalTests/zeppelin.sh
Labels: testing :hammer:

#15485 Fix broken flyout layout due to RTD addons upgrade
  docs/_static/js/initialize.js
  docs/conf.py
Labels: documentation :book:

#15487 Adjust transient storage changelog entry
  Changelog.md
Labels: documentation :book:

#15443 docs: fix broken links and typo
  docs/contributing.rst
Labels: documentation :book:, external contribution :star:

#15488 docs Update functions.rst
  docs/contracts/functions.rst
Labels: external contribution :star:

#15489 CI: Remove nightly codecov job
  .circleci/config.yml
  codecov.yml
Labels: testing :hammer:

#15471 eof: Support EOF asm analysis.
  libyul/AsmAnalysis.cpp
  libyul/AsmAnalysis.h
  test/Common.cpp
  test/TestCase.cpp
  test/TestCase.h
  test/libyul/yulSyntaxTests/eof/call_intruction_in_eof.yul
Labels: external contribution :star:, EOF

#14793 Update documentation about `codehash` behaviour according to EIP-1052 and EIP-161
  docs/types/value-types.rst
Labels: documentation :book:, external contribution :star:

#15187 Update Natspec format to correct devdoc return parameters
  docs/natspec-format.rst
Labels: documentation :book:, external contribution :star:

#15503 test: Pass `evmVersion` and `eofVersion` to `YulStack` in `ObjectCompilerTest`
  test/libyul/ControlFlowSideEffectsTest.cpp
  test/libyul/EVMCodeTransformTest.cpp
  test/libyul/FunctionSideEffects.cpp
  test/libyul/KnowledgeBaseTest.cpp
  test/libyul/ObjectCompilerTest.cpp
  test/libyul/ObjectCompilerTest.h
  test/libyul/ObjectParser.cpp
  test/libyul/Parser.cpp
  test/libyul/YulInterpreterTest.cpp
  test/libyul/objectCompiler/datacopy.yul
  test/libyul/objectCompiler/dataoffset_code.yul
  test/libyul/objectCompiler/dataoffset_data.yul
  test/libyul/objectCompiler/dataoffset_self.yul
  test/libyul/objectCompiler/datasize_code.yul
  test/libyul/objectCompiler/datasize_data.yul
  test/libyul/objectCompiler/datasize_self.yul
  test/libyul/objectCompiler/function_series.yul
  test/libyul/objectCompiler/identical_subobjects_full_debug_info.yul
  test/libyul/objectCompiler/identical_subobjects_no_debug_info.yul
  test/libyul/objectCompiler/identical_subobjects_partial_debug_info.yul
  test/libyul/objectCompiler/identical_subobjects_partial_debug_info_no_use_src.yul
  test/libyul/objectCompiler/identical_subobjects_with_subject_references.yul
  test/libyul/objectCompiler/immutable_long_name_does_not_end_up_in_bytecode.yul
  test/libyul/objectCompiler/leading_and_trailing_dots.yul
  test/libyul/objectCompiler/linkersymbol.yul
  test/libyul/objectCompiler/long_object_name.yul
  test/libyul/objectCompiler/manySubObjects.yul
  test/libyul/objectCompiler/metadata.yul
  test/libyul/objectCompiler/namedObjectCode.yul
  test/libyul/objectCompiler/nested_optimizer.yul
  test/libyul/objectCompiler/simple.yul
  test/libyul/objectCompiler/simple_optimizer.yul
  test/libyul/objectCompiler/sourceLocations.yul
  test/libyul/objectCompiler/subObjectAccess.yul
  test/libyul/objectCompiler/verbatim_bug.yul
Labels: external contribution :star:, EOF

#15500 Re-enable euler external test
  .circleci/config.yml
Labels: testing :hammer:

#15510 Use boost's predefined cpp integer types
  libsolutil/Numeric.h
  test/tools/yulInterpreter/EVMInstructionInterpreter.cpp
Labels: external contribution :star:, :yellow_circle:

#15456 eof: Support `DATALOADN` (EIP-7480)
  libevmasm/Assembly.cpp
  libevmasm/Assembly.h
  libevmasm/AssemblyItem.cpp
  libevmasm/AssemblyItem.h
  libevmasm/Instruction.cpp
  libevmasm/Instruction.h
  liblangutil/EVMVersion.cpp
  libyul/AsmAnalysis.cpp
  libyul/backends/evm/AbstractAssembly.h
  libyul/backends/evm/EVMDialect.cpp
  libyul/backends/evm/EthAssemblyAdapter.cpp
  libyul/backends/evm/EthAssemblyAdapter.h
  libyul/backends/evm/NoOutputAssembly.cpp
  libyul/backends/evm/NoOutputAssembly.h
  test/cmdlineTests/strict_asm_eof_dataloadn_prague/args
  test/cmdlineTests/strict_asm_eof_dataloadn_prague/input.yul
  test/cmdlineTests/strict_asm_eof_dataloadn_prague/output
  test/libyul/objectCompiler/dataloadn.yul
  test/libyul/yulSyntaxTests/eof/auxdataloadn_in_eof.yul
  test/libyul/yulSyntaxTests/eof/auxdataloadn_in_eof_invalid_literal_type.yul
  test/libyul/yulSyntaxTests/eof/auxdataloadn_in_eof_invalid_value.yul
  test/libyul/yulSyntaxTests/eof/auxdataloadn_in_legacy.yul
  test/tools/yulInterpreter/EVMInstructionInterpreter.cpp
Labels: external contribution :star:, EOF

#15516 Restrict object compiler tests to exclude deprecated EVM versions
  test/libyul/objectCompiler/data.yul
  test/libyul/objectCompiler/namedObject.yul
  test/libyul/objectCompiler/smoke.yul
  test/libyul/objectCompiler/subObject.yul
  test/libyul/objectCompiler/subSubObject.yul
Labels: testing :hammer:

#15506 Generalize optimizer step profiler
  libsolutil/CMakeLists.txt
  libsolutil/Profiler.cpp
  libsolutil/Profiler.h
  libyul/optimiser/Suite.cpp
  libyul/optimiser/Suite.h
Labels: performance :racehorse:, testing :hammer:, optimizer

#15505 Compiler stack: Protect loadGeneratedIR from contracts that cannot be deployed
  Changelog.md
  libsolidity/interface/CompilerStack.cpp
  libsolidity/interface/CompilerStack.h
  libsolidity/interface/StandardCompiler.cpp
  solc/CommandLineInterface.cpp
  test/cmdlineTests/standard_undeployable_contract_all_outputs/in.sol
  test/cmdlineTests/standard_undeployable_contract_all_outputs/input.json
  test/cmdlineTests/standard_undeployable_contract_all_outputs/output.json
  test/cmdlineTests/undeployable_contract_empty_outputs/args
  test/cmdlineTests/undeployable_contract_empty_outputs/input.sol
  test/cmdlineTests/undeployable_contract_empty_outputs/output
  test/libsolidity/MemoryGuardTest.cpp
Labels: :yellow_circle:

#15518 Profiler probes for non-sequence steps
  libyul/optimiser/Suite.cpp
Labels: performance :racehorse:, testing :hammer:, optimizer

#15527 Correct Yul test file extensions
  mcopy.yul
  mcopy_non_zero_size.yul
  mcopy_redundant_overwritten.yul
  mcopy_redundant_same_area.yul
  mcopy_redundant_zero_size.yul
  mcopy_zero_size.yul
  simple.yul
  unicode_comment_direction_override.yul
Labels: external contribution :star:

#15523 Yul optimizer suite: Call name simplifier only once
  libyul/optimiser/Suite.cpp
Labels: performance :racehorse:, optimizer

#15530 Move Yul tests from root to test dir
  test/libyul/yulOptimizerTests/expressionSimplifier/mcopy_non_zero_size.yul
  test/libyul/yulOptimizerTests/expressionSimplifier/mcopy_zero_size.yul
  test/libyul/yulOptimizerTests/fullInlinerWithoutSplitter/simple.yul
  test/libyul/yulOptimizerTests/fullSuite/mcopy.yul
  test/libyul/yulOptimizerTests/fullSuite/mcopy_redundant_overwritten.yul
  test/libyul/yulOptimizerTests/fullSuite/mcopy_redundant_same_area.yul
  test/libyul/yulOptimizerTests/fullSuite/mcopy_redundant_zero_size.yul
  test/libyul/yulSyntaxTests/invalid/unicode_comment_direction_override.yul
Labels: testing :hammer:

#15529 eof: Add `auxdataloadn` to reserved identifiers. Move test to `eof` dir
  libyul/backends/evm/EVMDialect.cpp
  test/libyul/objectCompiler/eof/dataloadn.yul
Labels: external contribution :star:, EOF

#15252 SMTChecker: Use Z3 through the SMT-LIB interface
  CMakeLists.txt
  Changelog.md
  docs/contributing.rst
  docs/smtchecker.rst
  libsmtutil/CHCSmtLib2Interface.cpp
  libsmtutil/CMakeLists.txt
  libsmtutil/Exceptions.h
  libsmtutil/SMTLib2Interface.cpp
  libsmtutil/SMTLib2Interface.h
  libsolidity/CMakeLists.txt
  libsolidity/formal/BMC.cpp
  libsolidity/formal/CHC.cpp
  libsolidity/formal/ExpressionFormatter.cpp
  libsolidity/formal/ModelChecker.cpp
  libsolidity/formal/SymbolicTypes.cpp
  libsolidity/formal/Z3CHCSmtLib2Interface.cpp
  libsolidity/formal/Z3SMTLib2Interface.cpp
  libsolidity/formal/Z3SMTLib2Interface.h
  test/cmdlineTests/model_checker_divModSlacks_false_all/err
  test/cmdlineTests/model_checker_divModSlacks_false_chc/err
  test/cmdlineTests/model_checker_invariants_all/err
  test/cmdlineTests/model_checker_invariants_all/input.sol
  test/cmdlineTests/model_checker_invariants_contract/err
  test/cmdlineTests/model_checker_invariants_contract/input.sol
  test/cmdlineTests/model_checker_invariants_contract_reentrancy/err
  test/cmdlineTests/model_checker_invariants_contract_reentrancy/input.sol
  test/cmdlineTests/model_checker_invariants_reentrancy/err
  test/cmdlineTests/model_checker_invariants_reentrancy/input.sol
  test/cmdlineTests/standard_model_checker_divModSlacks_false_all/output.json
  test/cmdlineTests/standard_model_checker_divModSlacks_false_chc/output.json
  test/cmdlineTests/standard_model_checker_invariants_contract/output.json
  test/cmdlineTests/standard_model_checker_invariants_contract_reentrancy/input.json
  test/cmdlineTests/standard_model_checker_invariants_contract_reentrancy/output.json
  test/cmdlineTests/standard_model_checker_invariants_reentrancy/input.json
  test/cmdlineTests/standard_model_checker_invariants_reentrancy/output.json
  test/libsolidity/smtCheckerTests/abi/abi_encode_with_selector_array_slice.sol
  test/libsolidity/smtCheckerTests/abi/abi_encode_with_selector_array_slice_2.sol
  test/libsolidity/smtCheckerTests/abi/abi_encode_with_selector_vs_sig.sol
  test/libsolidity/smtCheckerTests/abi/abi_encode_with_sig_array_slice.sol
  test/libsolidity/smtCheckerTests/abi/abi_encode_with_sig_array_slice_2.sol
  test/libsolidity/smtCheckerTests/external_calls/call_with_value_1.sol
  test/libsolidity/smtCheckerTests/external_calls/call_with_value_2.sol
  test/libsolidity/smtCheckerTests/external_calls/external.sol
  test/libsolidity/smtCheckerTests/external_calls/external_call_indirect_1.sol
  test/libsolidity/smtCheckerTests/external_calls/external_call_indirect_2.sol
  test/libsolidity/smtCheckerTests/external_calls/external_call_indirect_3.sol
  test/libsolidity/smtCheckerTests/external_calls/external_call_with_value_2.sol
  test/libsolidity/smtCheckerTests/external_calls/external_call_with_value_3.sol
  test/libsolidity/smtCheckerTests/external_calls/external_hash_known_code_state_reentrancy_3.sol
  test/libsolidity/smtCheckerTests/external_calls/external_hash_known_code_state_reentrancy_trusted.sol
  test/libsolidity/smtCheckerTests/external_calls/external_safe.sol
  test/libsolidity/smtCheckerTests/operators/index_access_for_bytesNN.sol
  test/libsolidity/smtCheckerTests/operators/index_access_side_effect.sol
  test/libsolidity/smtCheckerTests/operators/userDefined/user_defined_operator_matches_equivalent_function_call.sol
  test/libsolidity/smtCheckerTests/out_of_bounds/array_2d_4.sol
  test/libsolidity/smtCheckerTests/types/array_mapping_aliasing_2.sol
  test/libsolidity/smtCheckerTests/types/struct_array_branches_2d.sol
Labels: smt

#15538 Mark prague as experimental in a few places where it was not so
  docs/using-the-compiler.rst
  liblangutil/EVMVersion.h
  solc/CommandLineParser.cpp
  test/tools/fuzzer_common.cpp
Labels: documentation :book:, refactor, :yellow_circle:

#15537 Remove remaining artifacts of dynamically loading Z3.
  .circleci/build_win.ps1
  .circleci/config.yml
  cmake/EthCompilerSettings.cmake
  cmake/FindZ3.cmake
  cmake/toolchains/libfuzzer.cmake
  docs/installing-solidity.rst
  libsmtutil/Z3CHCInterface.cpp
  libsmtutil/Z3CHCInterface.h
  libsmtutil/Z3Interface.cpp
  libsmtutil/Z3Interface.h
  libsmtutil/Z3Loader.cpp
  libsmtutil/Z3Loader.h
  libsmtutil/genz3wrapper.py
  libsolidity/formal/BMC.cpp
  libsolidity/formal/ModelChecker.cpp
Labels: :yellow_circle:

#15535 Add `ControlFlowSideEffects` parameter to `createFunction` in EVMDialect
  libyul/ControlFlowSideEffects.h
  libyul/backends/evm/EVMDialect.cpp
Labels: external contribution :star:, refactor, EOF

#15544 More informative output for failed CLI tests in CI
  .circleci/parallel_cli_tests.py
  test/cmdlineTests.sh
Labels: testing :hammer:

#15545 eof: Change convention for printing immediate arguments in assembly
  libevmasm/AssemblyItem.cpp
  test/cmdlineTests/strict_asm_eof_dataloadn_prague/output
Labels: external contribution :star:, EOF

#15546 Yulopti: Fix error during parsing stage
  test/tools/yulopti.cpp
Labels: testing :hammer:

#15548 Fix link to the homebrew formula on the release checklist
  ReleaseChecklist.md
Labels: documentation :book:, external contribution :star:

#15549 eof: Update `dataloadn` test with new immediate arguments formating
  test/libyul/objectCompiler/eof/dataloadn.yul
Labels: external contribution :star:, testing :hammer:, EOF

#15513 Adjust Yul CFG export output
  libyul/YulControlFlowGraphExporter.cpp
  scripts/common_cmdline.sh
  solc/CommandLineInterface.cpp
  test/cmdlineTests/standard_yul_cfg_json_export/in.sol
  test/cmdlineTests/standard_yul_cfg_json_export/input.json
  test/cmdlineTests/standard_yul_cfg_json_export/output.json
  test/cmdlineTests/strict_asm_yul_cfg_json_export/args
  test/cmdlineTests/strict_asm_yul_cfg_json_export/input.yul
  test/cmdlineTests/strict_asm_yul_cfg_json_export/output
  test/cmdlineTests/yul_cfg_json_export/args
  test/cmdlineTests/yul_cfg_json_export/input.sol
  test/cmdlineTests/yul_cfg_json_export/output
Labels: has dependencies, :yellow_circle:

#15552 soltest pass for EOF
  .circleci/config.yml
  .circleci/soltest.sh
  .circleci/soltest_all.sh
  test/cmdlineTests/~via_ir_equivalence/test.sh
Labels: testing :hammer:, EOF

#15536 Pass object name to `AsmAnalyzer`
  libyul/AsmAnalysis.cpp
  libyul/AsmAnalysis.h
  libyul/CompilabilityChecker.cpp
  libyul/Object.cpp
  libyul/Object.h
  libyul/YulStack.cpp
  libyul/optimiser/StackCompressor.cpp
  libyul/optimiser/StackLimitEvader.cpp
  test/libyul/Common.cpp
  test/libyul/yulSyntaxTests/eof/object_name_in_eof.yul
Labels: external contribution :star:, refactor, EOF

#15512 eof: new contract creation
  libevmasm/Assembly.cpp
  libevmasm/Assembly.h
  libevmasm/AssemblyItem.cpp
  libevmasm/AssemblyItem.h
  libevmasm/Instruction.cpp
  libevmasm/Instruction.h
  libevmasm/SemanticInformation.cpp
  liblangutil/EVMVersion.cpp
  libsolidity/codegen/ir/IRGenerationContext.cpp
  libsolidity/codegen/ir/IRGenerationContext.h
  libsolidity/codegen/ir/IRGenerator.cpp
  libsolidity/codegen/ir/IRGenerator.h
  libsolidity/codegen/ir/IRGeneratorForStatements.cpp
  libsolidity/experimental/codegen/IRGenerator.cpp
  libyul/AsmAnalysis.cpp
  libyul/backends/evm/AbstractAssembly.h
  libyul/backends/evm/EVMDialect.cpp
  libyul/backends/evm/EthAssemblyAdapter.cpp
  libyul/backends/evm/EthAssemblyAdapter.h
  libyul/backends/evm/NoOutputAssembly.cpp
  libyul/backends/evm/NoOutputAssembly.h
  test/cmdlineTests/debug_info_in_yul_snippet_escaping/output
  test/cmdlineTests/standard_viair_requested/output.json
  test/cmdlineTests/strict_asm_eof_container_prague/input.yul
  test/cmdlineTests/strict_asm_eof_container_prague/output
  test/libyul/objectCompiler/eof/creation_with_immutables.yul
  test/libyul/yulSyntaxTests/eof/eofcreate.yul
  test/libyul/yulSyntaxTests/eof/eofcreate_invalid_object.yul
  test/libyul/yulSyntaxTests/eof/eofcreate_invalid_object_name_data.yul
  test/libyul/yulSyntaxTests/eof/eofcreate_invalid_object_name_path.yul
  test/libyul/yulSyntaxTests/eof/returncontract.yul
  test/libyul/yulSyntaxTests/eof/returncontract_invalid_object.yul
  test/tools/yulInterpreter/EVMInstructionInterpreter.cpp
Labels: external contribution :star:, EOF

#15493 Avoid multiple lookups during body-copying while inlining.
  libyul/optimiser/FullInliner.cpp
Labels: performance :racehorse:, optimizer, :yellow_circle:

#15337 Remove special yul strings from UnusedStoreEliminator
  libyul/optimiser/UnusedAssignEliminator.h
  libyul/optimiser/UnusedStoreBase.cpp
  libyul/optimiser/UnusedStoreBase.h
  libyul/optimiser/UnusedStoreEliminator.cpp
  libyul/optimiser/UnusedStoreEliminator.h
Labels: optimizer, refactor, :yellow_circle:

#15534 Yul: Object contains dialect
  libsolidity/ast/ASTJsonExporter.cpp
  libsolidity/codegen/CompilerContext.cpp
  libsolidity/codegen/ContractCompiler.cpp
  libsolidity/codegen/ir/IRGeneratorForStatements.cpp
  libsolidity/experimental/codegen/IRGeneratorForStatements.cpp
  libsolidity/interface/CompilerStack.cpp
  libyul/AsmJsonConverter.h
  libyul/AsmPrinter.h
  libyul/Object.cpp
  libyul/Object.h
  libyul/ObjectOptimizer.cpp
  libyul/ObjectParser.cpp
  libyul/backends/evm/EVMDialect.h
  libyul/backends/evm/EVMObjectCompiler.h
  libyul/optimiser/StackCompressor.h
  libyul/optimiser/StackLimitEvader.h
  libyul/optimiser/Suite.cpp
  libyul/optimiser/Suite.h
  test/libyul/Common.cpp
  test/libyul/Common.h
  test/libyul/CompilabilityChecker.cpp
  test/libyul/ControlFlowSideEffectsTest.cpp
  test/libyul/FunctionSideEffects.cpp
  test/libyul/YulOptimizerTest.cpp
  test/libyul/YulOptimizerTest.h
  test/libyul/YulOptimizerTestCommon.h
  test/tools/yulopti.cpp
  tools/yulPhaser/Program.cpp
Labels: refactor, :yellow_circle:
