Repository argotorg/solidity, pull requests merged in 2024-11, with the labels that each got.

#15561 External benchmarks for older solc versions
  test/benchmarks/external-setup.sh
  test/benchmarks/external.sh
Labels: testing :hammer:

#15533 Calldata doc
  docs/types/reference-types.rst
Labels: external contribution :star:

#15556 Set correct `movableApartFromEffects` flag for `datacopy()`
  libyul/backends/evm/EVMDialect.cpp
Labels: optimizer

#15574 Yul: Avoid expensive operations in functions called very often
  libyul/AsmParser.cpp
  libyul/optimiser/SyntacticalEquality.cpp
Labels: performance :racehorse:

#15581 Update package list before installing Python 2
  .circleci/config.yml
Labels: testing :hammer:

#15579 AST: More efficient way to collect referenced source units
  libsolidity/ast/AST.cpp
  libsolidity/ast/AST.h
Labels: performance :racehorse:

#15578 More precise documentation of optimizer settings and their defaults
  docs/using-the-compiler.rst
  libsolidity/interface/OptimiserSettings.h
Labels: documentation :book:, optimizer

#15547 eof: Support relative jumps
  libevmasm/Assembly.cpp
  libevmasm/Assembly.h
  libevmasm/AssemblyItem.cpp
  libevmasm/AssemblyItem.h
  libevmasm/BlockDeduplicator.cpp
  libevmasm/GasMeter.cpp
  libevmasm/GasMeter.h
  libevmasm/Instruction.cpp
  libevmasm/Instruction.h
  libevmasm/JumpdestRemover.cpp
  libevmasm/PeepholeOptimiser.cpp
  libevmasm/SemanticInformation.cpp
  liblangutil/EVMVersion.cpp
  libyul/backends/evm/EthAssemblyAdapter.cpp
  test/libyul/objectCompiler/eof/rjumps.yul
  test/tools/yulInterpreter/EVMInstructionInterpreter.cpp
Labels: external contribution :star:, EOF

#15542 Fix verbatim control flow side effects
  docs/yul.rst
  libyul/ControlFlowSideEffects.h
  libyul/backends/evm/EVMDialect.cpp
  test/libyul/yulOptimizerTests/unusedStoreEliminator/store_before_terminating_verbatim_revert.yul
Labels: external contribution :star:

#15502 docs: fix several spelling and grammar issues
  docs/types/value-types.rst
  test/externalTests/README.md
Labels: documentation :book:, external contribution :star:

#15589 Update python in CI to get latest codespell
  .circleci/config.yml
  .codespellrc
  CODE_OF_CONDUCT.md
  docs/bugs.json
  docs/internals/optimizer.rst
  docs/yul.rst
  scripts/codespell_ignored_lines.txt
  scripts/codespell_whitelist.txt
  test/libsolidity/semanticTests/abiencodedecode/abi_encode_with_signature.sol
  test/libsolidity/semanticTests/abiencodedecode/abi_encode_with_signaturev2.sol
  test/libyul/evmCodeTransform/stackReuse/function_params_and_retparams.yul
  test/libyul/yulOptimizerTests/commonSubexpressionEliminator/unassigned_return.yul
Labels: testing :hammer:, :yellow_circle:

#15076 Update the "Resources" section in the docs
  docs/resources.rst
Labels: documentation :book:

#15586 Document memory alignment
  docs/assembly.rst
Labels: documentation :book:, external contribution :star:

#15596 Replace `InvalidDeposit` and `InvalidOpcode` exceptions with asserts
  libevmasm/Assembly.cpp
  libevmasm/Assembly.h
  libevmasm/Exceptions.h
  libevmasm/Instruction.h
  libevmasm/KnownState.cpp
  libsolidity/interface/StandardCompiler.cpp
  test/cmdlineTests/standard_import_asm_json_invalid_opcode/output.json
Labels: refactor

#15595 eof: Contract creation fix and tests.
  libevmasm/Assembly.cpp
  libevmasm/Assembly.h
  libyul/AsmAnalysis.cpp
  test/libyul/objectCompiler/eof/256_subcontainers.yul
  test/libyul/objectCompiler/eof/prune_unreferenced_container.yul
  test/libyul/yulSyntaxTests/eof/too_many_subcontainers.yul
Labels: external contribution :star:, EOF

#15566 refine specification to add rules about calldata in constructor
  docs/types/reference-types.rst
Labels: documentation :book:, external contribution :star:

#15550 eof: Support functions (`CALLF`, `RETF`, `JUMPF`)
  libevmasm/Assembly.cpp
  libevmasm/Assembly.h
  libevmasm/AssemblyItem.cpp
  libevmasm/AssemblyItem.h
  libevmasm/GasMeter.cpp
  libevmasm/Instruction.cpp
  libevmasm/Instruction.h
  libevmasm/SemanticInformation.cpp
  libevmasm/SemanticInformation.h
  liblangutil/EVMVersion.cpp
  libyul/AsmAnalysis.cpp
  libyul/backends/evm/AbstractAssembly.h
  libyul/backends/evm/ControlFlowGraphBuilder.cpp
  libyul/backends/evm/ControlFlowGraphBuilder.h
  libyul/backends/evm/EVMDialect.cpp
  libyul/backends/evm/EVMDialect.h
  libyul/backends/evm/EthAssemblyAdapter.cpp
  libyul/backends/evm/EthAssemblyAdapter.h
  libyul/backends/evm/NoOutputAssembly.cpp
  libyul/backends/evm/NoOutputAssembly.h
  libyul/backends/evm/OptimizedEVMCodeTransform.cpp
  libyul/backends/evm/OptimizedEVMCodeTransform.h
  libyul/backends/evm/StackLayoutGenerator.cpp
  libyul/backends/evm/StackLayoutGenerator.h
  libyul/optimiser/StackCompressor.cpp
  libyul/optimiser/StackLimitEvader.cpp
  test/libyul/ControlFlowGraphTest.cpp
  test/libyul/ControlFlowGraphTest.h
  test/libyul/StackLayoutGeneratorTest.cpp
  test/libyul/StackLayoutGeneratorTest.h
  test/libyul/objectCompiler/eof/256_subcontainers.yul
  test/libyul/objectCompiler/eof/functions.yul
  test/libyul/yulSyntaxTests/eof/callf_jumpf_retf.yul
  test/libyul/yulSyntaxTests/eof/too_many_functions_arguments_or_returns.yul
  test/libyul/yulSyntaxTests/eof/too_many_subcontainers.yul
  test/tools/yulInterpreter/EVMInstructionInterpreter.cpp
Labels: external contribution :star:, EOF
