Repository argotorg/solidity, pull requests merged in 2024-01, with the labels that each got.

#14768 Switch to building GMP from an unofficial git mirror (CI hash update)
  .circleci/config.yml
Labels: build system :building_construction:, has dependencies

#14743 Bump evmc and evmone to v11.0.0
  scripts/docker/buildpack-deps/Dockerfile.ubuntu.clang.ossfuzz
  scripts/docker/buildpack-deps/Dockerfile.ubuntu2004
  scripts/docker/buildpack-deps/Dockerfile.ubuntu2204
  scripts/docker/buildpack-deps/Dockerfile.ubuntu2204.clang
Labels: testing :hammer:

#14758 Bump evmc and evmone images to v11 in CI
  .circleci/config.yml
  .circleci/osx_install_dependencies.sh
  scripts/install_evmone.ps1
  test/Common.h
  test/evmc/README.md
  test/evmc/evmc.h
  test/evmc/evmc.hpp
  test/evmc/mocked_host.hpp
Labels: testing :hammer:

#14773 Fix chai to version 4.4.0 in Brink external test
  test/externalTests/brink.sh
Labels: testing :hammer:

#14629 Fix several minor typo
  docs/installing-solidity.rst
  docs/path-resolution.rst
Labels: documentation :book:, external contribution :star:

#14755 Introduce blobbasefee
  Changelog.md
  docs/cheatsheet.rst
  docs/grammar/SolidityLexer.g4
  docs/units-and-global-variables.rst
  docs/using-the-compiler.rst
  docs/yul.rst
  libevmasm/Instruction.cpp
  libevmasm/Instruction.h
  libevmasm/SemanticInformation.cpp
  libevmasm/SimplificationRule.h
  liblangutil/EVMVersion.cpp
  liblangutil/EVMVersion.h
  libsolidity/analysis/TypeChecker.cpp
  libsolidity/ast/Types.cpp
  libsolidity/codegen/ExpressionCompiler.cpp
  libsolidity/codegen/ir/IRGeneratorForStatements.cpp
  libyul/AsmAnalysis.cpp
  libyul/backends/evm/EVMDialect.cpp
  scripts/error_codes.py
  scripts/test_antlr_grammar.sh
  test/EVMHost.cpp
  test/libsolidity/ViewPureChecker.cpp
  test/libsolidity/semanticTests/inlineAssembly/blobbasefee_shanghai_function.sol
  test/libsolidity/semanticTests/state/block_blobbasefee.sol
  test/libsolidity/syntaxTests/inlineAssembly/blobbasefee_reserved_cancun.sol
  test/libsolidity/syntaxTests/types/magic_block_basefee_error.sol
  test/libsolidity/syntaxTests/types/magic_block_blobbasefee_cancun.sol
  test/libsolidity/syntaxTests/types/magic_block_blobbasefee_error.sol
  test/libsolidity/syntaxTests/viewPureChecker/blobbasefee_not_pure.sol
  test/libsolidity/syntaxTests/viewPureChecker/inline_assembly_instructions_allowed_view_cancun.sol
  test/libsolidity/syntaxTests/viewPureChecker/inline_assembly_instructions_disallowed_pure_cancun.sol
  test/libyul/yulInterpreterTests/blobbasefee.yul
  test/libyul/yulSyntaxTests/blobbasefee_identifier_pre_cancun.yul
  test/libyul/yulSyntaxTests/blobbasefee_reserved_identifier_post_cancun.yul
  test/tools/yulInterpreter/EVMInstructionInterpreter.cpp
  test/tools/yulInterpreter/Interpreter.h
Labels: feature

#14782 Yul fuzzer: Add Shanghai EVM version
  test/tools/ossfuzz/protoToYul.cpp
  test/tools/ossfuzz/yulProto.proto
Labels: testing :hammer:

#14771 Fix typos
  libsolidity/codegen/ArrayUtils.cpp
  libsolidity/codegen/ArrayUtils.h
  test/libsolidity/semanticTests/externalContracts/_prbmath/PRBMathCommon.sol
Labels: external contribution :star:

#14757 EIP 4844 - blobhash opcode (part 1)
  Changelog.md
  docs/grammar/SolidityLexer.g4
  docs/yul.rst
  libevmasm/Instruction.cpp
  libevmasm/Instruction.h
  libevmasm/SemanticInformation.cpp
  libevmasm/SimplificationRule.h
  liblangutil/EVMVersion.cpp
  liblangutil/EVMVersion.h
  libyul/AsmAnalysis.cpp
  libyul/backends/evm/EVMDialect.cpp
  scripts/test_antlr_grammar.sh
  test/EVMHost.cpp
  test/libsolidity/semanticTests/inlineAssembly/blobhash.sol
  test/libsolidity/semanticTests/inlineAssembly/blobhash_index_exceeding_blob_count.sol
  test/libsolidity/semanticTests/inlineAssembly/blobhash_pre_cancun.sol
  test/libsolidity/syntaxTests/inlineAssembly/blobhash.sol
  test/libsolidity/syntaxTests/inlineAssembly/blobhash_pre_cancun.sol
  test/libsolidity/syntaxTests/inlineAssembly/blobhash_reserved_cancun.sol
  test/libsolidity/syntaxTests/viewPureChecker/blobhash_not_pure.sol
  test/libsolidity/syntaxTests/viewPureChecker/inline_assembly_instructions_allowed_view_cancun.sol
  test/libsolidity/syntaxTests/viewPureChecker/inline_assembly_instructions_disallowed_pure_cancun.sol
  test/libyul/yulInterpreterTests/blobhash.yul
  test/libyul/yulSyntaxTests/blobhash.yul
  test/libyul/yulSyntaxTests/blobhash_pre_cancun.yul
  test/tools/yulInterpreter/EVMInstructionInterpreter.cpp
  test/tools/yulInterpreter/EVMInstructionInterpreter.h
  test/tools/yulInterpreter/Interpreter.h
Labels: feature

#14790 Testing enhancements for `MCOPY`
  test/Common.cpp
  test/Common.h
  test/libsolidity/FunctionDependencyGraphTest.cpp
  test/libsolidity/GasMeter.cpp
  test/libsolidity/GasTest.cpp
  test/libsolidity/MemoryGuardTest.cpp
  test/libsolidity/MemoryGuardTest.h
  test/tools/yulInterpreter/EVMInstructionInterpreter.cpp
  test/tools/yulInterpreter/EVMInstructionInterpreter.h
Labels: testing :hammer:

#14759 EIP 4844 (part 2)
  Changelog.md
  docs/cheatsheet.rst
  docs/units-and-global-variables.rst
  docs/using-the-compiler.rst
  libsolidity/analysis/GlobalContext.cpp
  libsolidity/analysis/GlobalContext.h
  libsolidity/ast/Types.cpp
  libsolidity/ast/Types.h
  libsolidity/codegen/ExpressionCompiler.cpp
  libsolidity/codegen/ir/IRGeneratorForStatements.cpp
  libsolidity/interface/CompilerStack.cpp
  scripts/test_antlr_grammar.sh
  test/libsolidity/Assembly.cpp
  test/libsolidity/SolidityExpressionCompiler.cpp
  test/libsolidity/ViewPureChecker.cpp
  test/libsolidity/semanticTests/builtinFunctions/blobhash.sol
  test/libsolidity/semanticTests/builtinFunctions/blobhash_shadow_resolution.sol
  test/libsolidity/semanticTests/state/blobhash.sol
  test/libsolidity/semanticTests/state/uncalled_blobhash.sol
  test/libsolidity/syntaxTests/globalFunctions/blobhash_function_pre_cancun.sol
  test/libsolidity/syntaxTests/globalFunctions/blobhash_function_shadow_warning.sol
  test/libsolidity/syntaxTests/globalFunctions/blobhash_no_call.sol
  test/libsolidity/syntaxTests/globalFunctions/blobhash_not_declared_pre_cancun.sol
  test/libsolidity/syntaxTests/globalFunctions/blobhash_var_pre_cancun.sol
  test/libsolidity/syntaxTests/globalFunctions/blobhash_var_shadow_warning.sol
  test/libsolidity/syntaxTests/inlineAssembly/blobhash_pre_cancun_not_declared.sol
  test/libsolidity/syntaxTests/inlineAssembly/blobhash_pre_cancun_not_reserved.sol
  test/libsolidity/syntaxTests/viewPureChecker/blobhash.sol
  test/libsolidity/syntaxTests/viewPureChecker/blobhash_not_pure.sol
  test/libsolidity/syntaxTests/viewPureChecker/builtin_blobhash_restrict_warning.sol
Labels: feature

#14685 Support bytes concat
  Changelog.md
  libsolidity/formal/CHC.cpp
  libsolidity/formal/CHC.h
  libsolidity/formal/Predicate.cpp
  libsolidity/formal/Predicate.h
  libsolidity/formal/PredicateInstance.cpp
  libsolidity/formal/PredicateInstance.h
  libsolidity/formal/PredicateSort.cpp
  libsolidity/formal/PredicateSort.h
  libsolidity/formal/SMTEncoder.cpp
  libsolidity/formal/SMTEncoder.h
  libsolidity/formal/SymbolicState.cpp
  libsolidity/formal/SymbolicState.h
  test/libsolidity/smtCheckerTests/bytes_concat/equals.sol
  test/libsolidity/smtCheckerTests/bytes_concat/one_arg_call.sol
  test/libsolidity/smtCheckerTests/bytes_concat/simple.sol
  test/libsolidity/smtCheckerTests/deployment/deploy_trusted_flow.sol
  test/libsolidity/smtCheckerTests/operators/index_access_side_effect.sol
  test/libsolidity/smtCheckerTests/operators/userDefined/user_defined_operator_matches_equivalent_function_call.sol
  test/libsolidity/smtCheckerTests/typecast/function_type_to_function_type_internal.sol
  test/libsolidity/smtCheckerTests/types/array_mapping_aliasing_2.sol
Labels: smt

#14795 Fix macOS dependency cache.
  .circleci/config.yml
  .circleci/osx_install_dependencies.sh
Labels: build system :building_construction:

#14785 Update tests to account for EIP-6780
  libsolidity/analysis/TypeChecker.cpp
  libyul/AsmAnalysis.cpp
  test/EVMHost.cpp
  test/EVMHost.h
  test/libsolidity/semanticTests/various/selfdestruct.sol
  test/libsolidity/semanticTests/various/selfdestruct_post_cancun.sol
  test/libsolidity/semanticTests/various/selfdestruct_post_cancun_multiple_beneficiaries.sol
  test/libsolidity/semanticTests/various/selfdestruct_post_cancun_redeploy.sol
  test/libsolidity/semanticTests/various/selfdestruct_pre_cancun.sol
  test/libsolidity/semanticTests/various/selfdestruct_pre_cancun_multiple_beneficiaries.sol
  test/libsolidity/semanticTests/various/selfdestruct_pre_cancun_redeploy.sol
  test/libsolidity/syntaxTests/globalFunctions/selfdestruct_no_call.sol
  test/libsolidity/syntaxTests/nameAndTypeResolution/430_bare_selfdestruct.sol
  test/libsolidity/syntaxTests/types/address/address_nonpayable_selfdestruct.sol
  test/libsolidity/syntaxTests/types/address/address_payable_selfdestruct.sol
  test/libsolidity/syntaxTests/viewPureChecker/builtin_functions.sol
  test/libsolidity/syntaxTests/viewPureChecker/builtin_functions_view_fail.sol
  test/libsolidity/syntaxTests/viewPureChecker/inline_assembly_instructions_allowed.sol
  test/libsolidity/syntaxTests/viewPureChecker/inline_assembly_instructions_disallowed_pure.sol
  test/libsolidity/syntaxTests/viewPureChecker/inline_assembly_instructions_disallowed_view.sol
  test/libyul/yulSyntaxTests/selfdestruct.yul
Labels: testing :hammer:

#14725 Add support for apple silicon.
  .circleci/compare_bytecode_reports.sh
  .circleci/config.yml
  .circleci/osx_install_dependencies.sh
  .circleci/parallel_bytecode_report.sh
  cmake/jsoncpp.cmake
  scripts/bytecodecompare/prepare_report.py
  scripts/install_obsolete_jsoncpp_1_7_4.sh
  test/scripts/test_bytecodecompare_prepare_report.py
Labels: build system :building_construction:

#14815 Fix typos
  libevmasm/ConstantOptimiser.h
  libsolidity/codegen/YulUtilFunctions.cpp
  libsolidity/interface/StandardCompiler.h
  libsolidity/lsp/Transport.h
  test/evmc/evmc.h
  test/tools/ossfuzz/README.md
Labels: external contribution :star:, refactor

#14787 Yul proto fuzzer: Add mcopy builtin to generator.
  test/tools/ossfuzz/protoToYul.cpp
  test/tools/ossfuzz/protoToYul.h
  test/tools/ossfuzz/yulProto.proto
Labels: has dependencies

#14736 Remove unreachable errors from instantiation processing in `TypeInference`
  libsolidity/experimental/analysis/TypeInference.cpp
  scripts/error_codes.py
  test/libsolidity/syntaxTests/experimental/inference/instantiation_invalid_type_constructor.sol
  test/libsolidity/syntaxTests/experimental/inference/instantiation_not_for_class.sol
Labels: experimental

#14655 Fixed type variables for functions, type classes and types in new analysis
  libsolidity/experimental/analysis/TypeInference.cpp
  libsolidity/experimental/analysis/TypeInference.h
  libsolidity/experimental/ast/TypeSystem.cpp
  libsolidity/experimental/ast/TypeSystem.h
  libsolidity/experimental/ast/TypeSystemHelper.cpp
  libsolidity/experimental/ast/TypeSystemHelper.h
  test/libsolidity/syntaxTests/experimental/builtin/builtin_type_definition.sol
  test/libsolidity/syntaxTests/experimental/inference/instantiation_member_type_does_not_match_declaration.sol
  test/libsolidity/syntaxTests/experimental/inference/polymorphic_function_call.sol
  test/libsolidity/syntaxTests/experimental/inference/polymorphic_type.sol
  test/libsolidity/syntaxTests/experimental/inference/polymorphic_type_abs_and_rep.sol
  test/libsolidity/syntaxTests/experimental/inference/polymorphic_type_instantiation_and_operators.sol
Labels: experimental
