Repository argotorg/solidity, pull requests merged in 2024-09, with the labels that each got.

#15238 Relax the definition of memory safety in the documentation.
  docs/assembly.rst
Labels: documentation :book:

#15377 Tweak advanced CMake options
  CMakeLists.txt
  cmake/submodules.cmake
  libsolutil/JSON.cpp
Labels: build system :building_construction:, :yellow_circle:

#15356 eof: Pass `_eofVersion` down to `libevmasm/Assembly` class
  libevmasm/Assembly.cpp
  libevmasm/Assembly.h
  libsolidity/codegen/CompilerContext.h
  libsolidity/interface/CompilerStack.cpp
  libyul/YulStack.cpp
  libyul/backends/evm/EVMObjectCompiler.cpp
  libyul/backends/evm/EthAssemblyAdapter.cpp
  test/libevmasm/Assembler.cpp
  test/libevmasm/Optimiser.cpp
  test/libsolidity/Metadata.cpp
  test/libyul/EVMCodeTransformTest.cpp
  test/tools/fuzzer_common.cpp
Labels: external contribution :star:, EOF

#15394 Disable failing import tests introduced by boost upgrade
  test/libsolidity/interface/FileReader.cpp
  test/libsolidity/syntaxTests/imports/boost_filesystem_bug.sol
Labels: testing :hammer:

#15389 `b_alpine_docker` CI run
  .circleci/config.yml
  scripts/docker_deploy_manual.sh
  scripts/release_ppa.sh
Labels: testing :hammer:, :yellow_circle:

#15203 Replace empty check of error, warning and info list with check for errors only
  liblangutil/ErrorReporter.h
  liblangutil/Exceptions.h
  libsolidity/analysis/DeclarationTypeChecker.cpp
  libsolidity/codegen/CompilerContext.cpp
  libsolidity/interface/StandardCompiler.cpp
  libyul/YulStack.cpp
  test/libsolidity/InlineAssembly.cpp
  test/libyul/Common.cpp
  test/tools/yulopti.cpp
  test/tools/yulrun.cpp
  tools/yulPhaser/Program.cpp
Labels: bug :bug:, :yellow_circle:

#15371 SMTChecker: Prepare BMC engine for switching Z3 to SMT-LIB Interface.
  libsmtutil/SMTLib2Interface.cpp
  libsmtutil/SMTLib2Interface.h
  libsolidity/formal/Z3SMTLib2Interface.cpp
  libsolidity/formal/Z3SMTLib2Interface.h
Labels: smt, :yellow_circle:

#15418 Add ContiguousDisjointSet datastructure
  libsolutil/CMakeLists.txt
  libsolutil/DisjointSet.cpp
  libsolutil/DisjointSet.h
  test/CMakeLists.txt
  test/libsolutil/DisjointSet.cpp
Labels: :yellow_circle:

#15422 Add ubuntu 2404 images to CI config
  .circleci/config.yml
Labels: build system :building_construction:

#15421 Remove STRICT_NLOHMANN_JSON_VERSION_CHECK leftover.
  CMakeLists.txt
Labels: build system :building_construction:, refactor

#15431 Apostrophe added in README.md
  README.md
Labels: external contribution :star:

#15320 Update `evmc` to `12.0.0` and `evmone` to `0.12.0`
  .circleci/config.yml
  .circleci/osx_install_dependencies.sh
  scripts/install_evmone.ps1
  test/Common.h
  test/evmc/README.md
  test/evmc/bytes.hpp
  test/evmc/evmc.h
  test/evmc/evmc.hpp
  test/evmc/helpers.h
  test/evmc/hex.hpp
  test/evmc/mocked_host.hpp
Labels: build system :building_construction:, external contribution :star:, has dependencies, :yellow_circle:

#15419 Liveness loop nesting forest
  libyul/CMakeLists.txt
  libyul/backends/evm/SSACFGLoopNestingForest.cpp
  libyul/backends/evm/SSACFGLoopNestingForest.h
  libyul/backends/evm/SSACFGTopologicalSort.cpp
  libyul/backends/evm/SSACFGTopologicalSort.h
  test/libyul/yulSSAControlFlowGraph/nested_for.yul
Labels: :yellow_circle:

#15437 Bump all jobs to Ubuntu 24.04 Noble
  .circleci/README.md
  .circleci/config.yml
  .github/workflows/buildpack-deps.yml
  docs/docs.sh
  scripts/ci/buildpack-deps_test_ubuntu1804.sh
  scripts/ci/buildpack-deps_test_ubuntu2204.clang.sh
  scripts/ci/buildpack-deps_test_ubuntu2204.sh
  scripts/docker/buildpack-deps/Dockerfile.ubuntu2204
  scripts/docker/buildpack-deps/Dockerfile.ubuntu2204.clang
Labels: build system :building_construction:

#15367 eof: Introduce EOF container format support in `Assembly::assemble` (EIP-3540)
  libevmasm/Assembly.cpp
  libevmasm/Assembly.h
  libevmasm/ConstantOptimiser.cpp
  libevmasm/EVMAssemblyStack.cpp
  libevmasm/EVMAssemblyStack.h
  libsolidity/interface/CompilerStack.cpp
  libsolidity/interface/StandardCompiler.cpp
  libyul/YulStack.cpp
  solc/CommandLineInterface.cpp
  test/cmdlineTests/strict_asm_eof_container_prague/args
  test/cmdlineTests/strict_asm_eof_container_prague/input.yul
  test/cmdlineTests/strict_asm_eof_container_prague/output
  test/libevmasm/Assembler.cpp
  test/libevmasm/Optimiser.cpp
  test/libsolidity/Assembly.cpp
Labels: external contribution :star:, EOF

#15450 Benchmarking compiler's peak memory use
  scripts/common.sh
  test/benchmarks/external.sh
  test/benchmarks/local.sh
Labels: testing :hammer:

#15446 EOF: Refactor `assemble` functions in `evmasm::Assembly`
  libevmasm/Assembly.cpp
  libevmasm/Assembly.h
  libevmasm/LinkerObject.h
  libsolidity/interface/StandardCompiler.cpp
Labels: external contribution :star:, refactor, EOF

#15449 EOF: Support strict assembly output and source mapping for EOF
  libevmasm/Assembly.cpp
  libevmasm/AssemblyItem.cpp
  libyul/YulStack.cpp
  test/cmdlineTests/strict_asm_eof_container_prague/args
  test/cmdlineTests/strict_asm_eof_container_prague/output
Labels: external contribution :star:, EOF

#15454 Add missing ASAN runtime libraries
  scripts/docker/buildpack-deps/Dockerfile.ubuntu2404.clang
Labels: build system :building_construction:, :yellow_circle:

#15455 Bump ubuntu 24.04 clang image
  .circleci/config.yml
Labels: build system :building_construction:, has dependencies, :yellow_circle:

#15453 Do not treat all warnings as errors when building with sanitizers.
  .circleci/config.yml
Labels: build system :building_construction:, :yellow_circle:

#15457 Fix shift in Yul AST native src locations due to code snippets in debug info
  Changelog.md
  libsolidity/codegen/ir/IRGenerator.cpp
  libsolidity/experimental/codegen/IRGenerator.cpp
  libsolidity/experimental/codegen/IRGeneratorForStatements.cpp
  libsolidity/interface/CompilerStack.cpp
  libyul/YulStack.cpp
  libyul/YulStack.h
  test/cmdlineTests/ast_ir/output
  test/cmdlineTests/standard_irOptimized_ast_requested/output.json
Labels: :yellow_circle:

#15451 Do not store JSON Yul ASTs and Yul CFG in `CompilerStack`
  Changelog.md
  libsolidity/interface/CompilerStack.cpp
  libsolidity/interface/CompilerStack.h
Labels: performance :racehorse:, :yellow_circle:

#15465 Fix missing `std::` prefix for `PROFILE_OPTIMIZER_STEPS`
  libyul/optimiser/Suite.cpp
Labels: performance :racehorse:

#15460 Do not cache instances of `Compiler` in `CompilerStack`
  libsolidity/interface/CompilerStack.cpp
  libsolidity/interface/CompilerStack.h
Labels: performance :racehorse:

#15441 SSACFGBuilder: clean up tryRemoveTrivialPhi
  libyul/backends/evm/SSAControlFlowGraphBuilder.cpp
Labels: has dependencies
