Repository argotorg/solidity, pull requests merged in 2025-01, with the labels that each got.

#15685 Fix build with GCC 14
  test/yulPhaser/Chromosome.cpp
Labels: external contribution :star:

#15693 Update emscripten docker image version
  .circleci/config.yml
  scripts/build_emscripten.sh
Labels: has dependencies

#15689 Reduce some file system paths' lengths
  test/cmdlineTests/standard_model_checker_show_unsupported_false_all_engines/standard_model_checker_show_unsupported_false_all_enginesstandard_model_checker_show_unsupported_false_bmc/input.json
  test/cmdlineTests/standard_model_checker_show_unsupported_false_all_engines/standard_model_checker_show_unsupported_false_all_enginesstandard_model_checker_show_unsupported_false_bmc/output.json
Labels: external contribution :star:

#15687 Fix typographical errors
  docs/assembly.rst
  test/libsolidity/syntaxTests/bytecodeReferences/circular_reference_internal_function.sol
Labels: external contribution :star:

#15674 Replace `Boost_DIR` with `Boost_INCLUDE_DIR`
  docs/installing-solidity.rst
Labels: build system :building_construction:, external contribution :star:

#15675 Fix MSVC compilation error on `EVMVersion` comparison
  liblangutil/EVMVersion.cpp
Labels: external contribution :star:, EOF

#15701 SMTChecker: Fix error when initializing fixed-sized-bytes array
  Changelog.md
  libsolidity/formal/SMTEncoder.cpp
  test/libsolidity/smtCheckerTests/typecast/fixed_bytes_array_from_strig_inline_array.sol
Labels: smt, :yellow_circle:

#15717 chore: remove redundant word
  libyul/AST.h
Labels: external contribution :star:

#15720 Ask about pipeline and update framework examples in bug template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: documentation :book:

#15723 Fix typos in function and parameter names
  Changelog.md
  test/libsolidity/util/ContractABIUtils.h
Labels: external contribution :star:

#15726 Fix typo in libevmasm/Assembly.cpp
  libevmasm/Assembly.cpp
Labels: external contribution :star:, refactor, EOF

#15728 Fix function name enumerateOptmisationSteps
  test/yulPhaser/Chromosome.cpp
  test/yulPhaser/Population.cpp
  test/yulPhaser/TestHelpers.cpp
  test/yulPhaser/TestHelpers.h
  test/yulPhaser/TestHelpersTest.cpp
Labels: documentation :book:, external contribution :star:

#15729 Fix the name of `RETURNCONTRACT` instruction in EOF assembly output
  libevmasm/AssemblyItem.cpp
  test/cmdlineTests/strict_asm_eof_container_prague/output
  test/libyul/objectCompiler/eof/creation_with_immutables.yul
Labels: external contribution :star:, EOF

#15713 Workaround for Boost compilation error with Clang 18 and libc++ in ossfuzz buildpack-deps
  scripts/docker/buildpack-deps/Dockerfile.ubuntu.clang.ossfuzz
Labels: build system :building_construction:

#15718 Bump ossfuzz image
  .circleci/config.yml
Labels: build system :building_construction:, has dependencies

#15750 Fix spelling mistakes and silence false-positives newly reported by codespell
  scripts/codespell_ignored_lines.txt
  test/libsolidity/util/SoltestTypes.h
Labels: testing :hammer:

#15749 SMTChecker: Fix encoding of arguments of cryptographic functions
  Changelog.md
  libsolidity/formal/SMTEncoder.cpp
  test/libsolidity/smtCheckerTests/crypto/crypto_functions_same_string_literal.sol
Labels: smt

#15755 Fix typo in variable name in buildinfo.cmake
  cmake/scripts/buildinfo.cmake
Labels: build system :building_construction:, external contribution :star:

#15700 eof: Fix EOF builtin names unintentionally reserved outside of EOF
  libyul/AsmAnalysis.cpp
  libyul/backends/evm/EVMDialect.cpp
  test/libyul/yulSyntaxTests/eof/auxdataloadn_in_legacy.yul
  test/libyul/yulSyntaxTests/eof/eof_identifiers_in_legacy.yul
  test/libyul/yulSyntaxTests/eof/eof_identifiers_not_defined_in_legacy.yul
  test/libyul/yulSyntaxTests/eof/eof_identifiers_not_reserved_in_legacy.yul
  test/libyul/yulSyntaxTests/eof/eof_names_reserved_in_eof.yul
  test/libyul/yulSyntaxTests/eof/eof_opcodes_identifiers_reserved_in_eof.yul
  test/libyul/yulSyntaxTests/eof/extcalls_invalid_in_legacy.yul
Labels: external contribution :star:, EOF

#15754 add build jobs that run on ubuntu 2204
  .circleci/config.yml
Labels: build system :building_construction:

#15756 fix: typos in `libsolidity/analysis/`
  libsolidity/analysis/ControlFlowAnalyzer.cpp
  libsolidity/analysis/NameAndTypeResolver.cpp
Labels: external contribution :star:

#15763 fix typo in `distinguishingProperty` variable name
  libsolidity/analysis/OverrideChecker.cpp
  test/FilesystemUtils.cpp
Labels: external contribution :star:

#15767 fix typo in `ExpressionNestingLimitReached` enum value
  test/tools/ossfuzz/yulFuzzerCommon.cpp
  test/tools/ossfuzz/yulFuzzerCommon.h
Labels: external contribution :star:, testing :hammer:

#15772 fix typo in `StackCompressor` comments: `ina` -> `in a`
  libyul/optimiser/StackCompressor.cpp
  libyul/optimiser/StackCompressor.h
Labels: external contribution :star:

#15765 Move loose semantic and syntax tests to subdirs
  test/libsolidity/semanticTests/cleanup/byte_array_to_storage_cleanup.sol
  test/libsolidity/semanticTests/cleanup/dirty_calldata_bytes.sol
  test/libsolidity/semanticTests/cleanup/dirty_calldata_dynamic_array.sol
  test/libsolidity/semanticTests/constructor/state_variable_initialization.sol
  test/libsolidity/semanticTests/events/emit_three_identical_events.sol
  test/libsolidity/semanticTests/events/emit_two_identical_events.sol
  test/libsolidity/semanticTests/inheritance/constructor_inheritance_init_order.sol
  test/libsolidity/semanticTests/inheritance/constructor_inheritance_init_order_2.sol
  test/libsolidity/semanticTests/inheritance/constructor_inheritance_init_order_3_legacy.sol
  test/libsolidity/semanticTests/inheritance/constructor_inheritance_init_order_3_viaIR.sol
  test/libsolidity/semanticTests/inheritance/constructor_with_params.sol
  test/libsolidity/semanticTests/inheritance/constructor_with_params_diamond_inheritance.sol
  test/libsolidity/semanticTests/inheritance/constructor_with_params_inheritance.sol
  test/libsolidity/semanticTests/inheritance/constructor_with_params_inheritance_2.sol
  test/libsolidity/semanticTests/inheritance/interface_inheritance_conversions.sol
  test/libsolidity/semanticTests/inheritance/state_variables_init_order.sol
  test/libsolidity/semanticTests/inheritance/state_variables_init_order_2.sol
  test/libsolidity/semanticTests/inheritance/state_variables_init_order_3.sol
  test/libsolidity/semanticTests/inlineAssembly/for_loop_break.sol
  test/libsolidity/semanticTests/inlineAssembly/for_loop_continue.sol
  test/libsolidity/semanticTests/inlineAssembly/for_loop_nested.sol
  test/libsolidity/semanticTests/isoltestTesting/empty_contract.sol
  test/libsolidity/semanticTests/isoltestTesting/isoltestFormatting.sol
  test/libsolidity/semanticTests/optimizer/unused_store_storage_removal_bug.sol
  test/libsolidity/semanticTests/scoping/c99_scoping_activation.sol
  test/libsolidity/semanticTests/statements/empty_for_loop.sol
  test/libsolidity/syntaxTests/abiEncoder/tight_packing_literals.sol
  test/libsolidity/syntaxTests/abiEncoder/tight_packing_literals_fine.sol
  test/libsolidity/syntaxTests/comments/multiline_comments.sol
  test/libsolidity/syntaxTests/constructor/constructor_this.sol
  test/libsolidity/syntaxTests/globalFunctions/deprecated_functions.sol
  test/libsolidity/syntaxTests/iceRegressionTests/cycle_checker_function_type.sol
  test/libsolidity/syntaxTests/iceRegressionTests/missing_functions_duplicate_bug.sol
  test/libsolidity/syntaxTests/isoltestTesting/stopAfterAnalysisError.sol
  test/libsolidity/syntaxTests/isoltestTesting/stopAfterParsingAnalysisErrorNotShowing.sol
  test/libsolidity/syntaxTests/isoltestTesting/stopAfterParsingError.sol
  test/libsolidity/syntaxTests/literalOperations/literal_comparisons.sol
  test/libsolidity/syntaxTests/literals/upper_case_hex_literals.sol
  test/libsolidity/syntaxTests/operators/negation.sol
  test/libsolidity/syntaxTests/operators/signed_rational_modulus.sol
  test/libsolidity/syntaxTests/parsing/unexpected.sol
  test/libsolidity/syntaxTests/scoping/double_stateVariable_declaration.sol
  test/libsolidity/syntaxTests/scoping/double_variable_declaration.sol
  test/libsolidity/syntaxTests/scoping/duplicate_contract.sol
  test/libsolidity/syntaxTests/scoping/missing_state_variable.sol
  test/libsolidity/syntaxTests/sizeLimits/more_than_256_declarationerrors.sol
  test/libsolidity/syntaxTests/sizeLimits/more_than_256_importerrors.sol
  test/libsolidity/syntaxTests/sizeLimits/more_than_256_syntaxerrors.sol
  test/libsolidity/syntaxTests/smoke/smoke_test.sol
  test/libsolidity/syntaxTests/structs/empty_struct.sol
  test/libsolidity/syntaxTests/super/unimplemented_super_function.sol
  test/libsolidity/syntaxTests/super/unimplemented_super_function_derived.sol
  test/scripts/test_bytecodecompare_prepare_report.py
Labels: testing :hammer:, refactor

#15781 Fix missing in JSON
  docs/natspec-format.rst
Labels: external contribution :star:

#15785 eof: Assert against legacy identifiers/members availability in EOF context.
  libsolidity/codegen/ir/IRGeneratorForStatements.cpp
Labels: external contribution :star:, EOF

#15784 eof: Fix condition when generating custom error for builtins available in EOF but not in legacy
  libyul/AsmAnalysis.cpp
  test/libyul/yulSyntaxTests/eof/eof_identifiers_not_defined_in_legacy.yul
Labels: external contribution :star:, EOF

#15783 eof: Disallow EOF builtins in inline assembly.
  libyul/backends/evm/EVMDialect.cpp
  test/libsolidity/syntaxTests/inlineAssembly/invalid/eof/eof_builtins_disallowed.sol
  test/libsolidity/syntaxTests/inlineAssembly/invalid/eof/eof_builtins_disallowed_in_inline_assembly.sol
Labels: external contribution :star:, EOF

#15751 Switch from c++17 to c++20 and reactivate fully static builds
  .circleci/config.yml
  .github/workflows/buildpack-deps.yml
  Changelog.md
  ReleaseChecklist.md
  cmake/EthCompilerSettings.cmake
  cmake/EthToolchains.cmake
  docs/installing-solidity.rst
  libevmasm/ConstantOptimiser.cpp
  libevmasm/ConstantOptimiser.h
  libevmasm/PeepholeOptimiser.cpp
  libevmasm/PeepholeOptimiser.h
  libsolidity/ast/Types.cpp
  libsolidity/ast/Types.h
  libsolidity/experimental/ast/TypeSystem.cpp
  libsolidity/experimental/ast/TypeSystemHelper.cpp
  libsolidity/interface/GasEstimator.cpp
  libyul/optimiser/ExpressionSplitter.cpp
  libyul/optimiser/ExpressionSplitter.h
  libyul/optimiser/FunctionHoister.cpp
  libyul/optimiser/FunctionHoister.h
  scripts/deps-ppa/static_z3.sh
  scripts/docker/buildpack-deps/Dockerfile.ubuntu2004
  scripts/release_ppa.sh
  solc/CommandLineInterface.cpp
  solc/CommandLineParser.cpp
  test/EVMHost.cpp
  test/tools/ossfuzz/CMakeLists.txt
  test/tools/ossfuzz/StackReuseCodegenFuzzer.cpp
Labels: build system :building_construction:

#15791 Fix Foundry version for PRB-Math external test
  .circleci/config.yml
Labels: testing :hammer:

#15741 ParserBase: avoid copying around currentLiteral
  liblangutil/ParserBase.cpp
  liblangutil/ParserBase.h
  libsolutil/CommonData.h
  libyul/AsmParser.cpp
  libyul/AsmParser.h
  libyul/ObjectParser.cpp
Labels: refactor

#15793 Update versions flyout menu location.
  docs/index.rst
Labels: documentation :book:, external contribution :star:

#15663 eof: Test that EOF sets the `experimental` flag in metadata
  test/libsolidity/Metadata.cpp
Labels: external contribution :star:, testing :hammer:, EOF

#15797 Update nightly CI to work with c++20 and restrict some tests to >= constantinople
  .circleci/config.yml
  scripts/Dockerfile
  test/libsolidity/semanticTests/constructor/no_callvalue_check.sol
  test/libsolidity/semanticTests/functionCall/failed_create.sol
  test/libsolidity/semanticTests/immutable/multi_creation.sol
  test/libsolidity/semanticTests/inheritance/address_overload_resolution.sol
  test/libsolidity/semanticTests/inheritance/member_notation_ctor.sol
  test/libsolidity/semanticTests/operators/userDefined/operator_making_pure_external_call.sol
  test/libsolidity/semanticTests/operators/userDefined/operator_making_view_external_call.sol
  test/libsolidity/semanticTests/various/many_subassemblies.sol
Labels: build system :building_construction:, testing :hammer:

#15799 Fix wrong comment about blobhash behavior
  test/libsolidity/semanticTests/inlineAssembly/blobhash_index_exceeding_blob_count.sol
Labels: testing :hammer:

#15798 Bump resource class for t_ems_ext_edr from small to medium
  .circleci/config.yml
Labels: testing :hammer:

#15800 Remove cxx20 header containing reference implementation of erase_if
  libsolutil/CMakeLists.txt
  libsolutil/cxx20.h
  libyul/backends/evm/ControlFlowGraphBuilder.cpp
  libyul/backends/evm/OptimizedEVMCodeTransform.cpp
  libyul/backends/evm/SSAControlFlowGraphBuilder.cpp
  libyul/backends/evm/StackLayoutGenerator.cpp
  libyul/optimiser/DataFlowAnalyzer.cpp
Labels: refactor

#15632 style： SETTINGS_PRESETS is not declared using const.
  scripts/bytecodecompare/prepare_report.js
Labels: external contribution :star:, refactor

#15593 Fix typos and grammar in documentation files
  .circleci/README.md
  scripts/docker/buildpack-deps/README.md
  test/externalTests/README.md
Labels: documentation :book:, external contribution :star:

#15801 fix: correct code comments and references in ArrayUtils, CHC, EncodingContext, and LSP tests
  libsolidity/codegen/ArrayUtils.cpp
  libsolidity/formal/CHC.cpp
  libsolidity/formal/EncodingContext.h
  test/libsolidity/lsp/goto/goto_definition_imports.sol
Labels: external contribution :star:

#15803 Add `outputs` setting to `ObjectCompilerTest`
  test/libyul/ObjectCompilerTest.cpp
  test/libyul/ObjectCompilerTest.h
Labels: external contribution :star:, testing :hammer:, EOF

#15796 SMTChecker: Add support for block.blobbasefee and blobhash()
  Changelog.md
  docs/smtchecker.rst
  libsolidity/formal/BMC.cpp
  libsolidity/formal/CHC.cpp
  libsolidity/formal/Predicate.cpp
  libsolidity/formal/SMTEncoder.cpp
  libsolidity/formal/SMTEncoder.h
  libsolidity/formal/SymbolicState.cpp
  libsolidity/formal/SymbolicState.h
  libsolidity/formal/SymbolicTypes.cpp
  libsolidity/formal/SymbolicTypes.h
  scripts/error_codes.py
  test/cmdlineTests/model_checker_print_query_all/err
  test/cmdlineTests/model_checker_print_query_bmc/err
  test/cmdlineTests/model_checker_print_query_chc/err
  test/cmdlineTests/model_checker_show_unproved_default_all_engines/err
  test/cmdlineTests/model_checker_show_unproved_default_bmc/err
  test/cmdlineTests/model_checker_show_unproved_true_all_engines/err
  test/cmdlineTests/model_checker_show_unproved_true_bmc/err
  test/cmdlineTests/standard_model_checker_print_query_all/output.json
  test/cmdlineTests/standard_model_checker_print_query_bmc/output.json
  test/cmdlineTests/standard_model_checker_print_query_chc/output.json
  test/cmdlineTests/standard_model_checker_show_unproved_default_all_engines/output.json
  test/cmdlineTests/standard_model_checker_show_unproved_false_all_engines/output.json
  test/cmdlineTests/standard_model_checker_show_unproved_false_bmc/output.json
  test/cmdlineTests/standard_model_checker_show_unproved_true_all_engines/output.json
  test/cmdlineTests/standard_model_checker_show_unproved_true_bmc/output.json
  test/cmdlineTests/standard_model_checker_solvers_smtlib2/output.json
  test/libsolidity/smtCheckerTests/bmc_coverage/compound_bitwise_or_uint_3.sol
  test/libsolidity/smtCheckerTests/external_calls/external_safe.sol
  test/libsolidity/smtCheckerTests/operators/compound_bitwise_or_uint_3.sol
  test/libsolidity/smtCheckerTests/operators/userDefined/user_defined_operator_matches_equivalent_function_call.sol
  test/libsolidity/smtCheckerTests/special/blobhash_beyond_limit.sol
  test/libsolidity/smtCheckerTests/special/tx_data_immutable.sol
  test/libsolidity/smtCheckerTests/special/tx_data_immutable_fail.sol
  test/libsolidity/smtCheckerTests/types/fixed_bytes_access_3.sol
Labels: smt, :yellow_circle:

#15788 Fix trailing input in hardcoded precompile expectations
  test/EVMHost.cpp
  test/EVMHost.h
  test/libsolidity/semanticTests/ecrecover/failing_ecrecover_invalid_input.sol
  test/libsolidity/semanticTests/externalContracts/snark.sol
  test/libsolidity/semanticTests/functionCall/bare_call_no_returndatacopy.sol
  test/libsolidity/semanticTests/isoltestTesting/precompiles_ignoring_trailing_input.sol
  test/soltest.cpp
Labels: testing :hammer:
