Repository argotorg/solidity, pull requests merged in 2025-05, with the labels that each got.

#16021 Subassembly syntax for plain EVM assembly tests
  test/libevmasm/PlainAssemblyParser.cpp
  test/libevmasm/PlainAssemblyParser.h
  test/libevmasm/evmAssemblyTests/isoltestTesting/empty.asm
  test/libevmasm/evmAssemblyTests/isoltestTesting/pushsize.asm
  test/libevmasm/evmAssemblyTests/isoltestTesting/pushsubsize.asm
  test/libevmasm/evmAssemblyTests/isoltestTesting/subassemblies.asm
  test/libevmasm/evmAssemblyTests/isoltestTesting/subassemblies_empty.asm
  test/libevmasm/evmAssemblyTests/isoltestTesting/subassemblies_nested.asm
Labels: testing :hammer:

#16041 Add option to treat literal assignments as operations in SSACFGs
  libyul/YulControlFlowGraphExporter.cpp
  libyul/YulStack.cpp
  libyul/backends/evm/SSAControlFlowGraph.cpp
  libyul/backends/evm/SSAControlFlowGraph.h
  libyul/backends/evm/SSAControlFlowGraphBuilder.cpp
  libyul/backends/evm/SSAControlFlowGraphBuilder.h
  test/cmdlineTests/standard_yul_cfg_json_export/output.json
  test/cmdlineTests/yul_cfg_json_export/output
  test/libyul/SSAControlFlowGraphTest.cpp
  test/libyul/yulSSAControlFlowGraph/complex.yul
  test/libyul/yulSSAControlFlowGraph/complex2.yul
  test/libyul/yulSSAControlFlowGraph/function.yul
  test/libyul/yulSSAControlFlowGraph/nested_for.yul
  test/libyul/yulSSAControlFlowGraph/nested_function.yul
Labels: :yellow_circle:

#16052 Collect instruction location info for EOF assembly
  libevmasm/Assembly.cpp
Labels: EOF

#16059 Add nullptr checking for rename logging
  libsolidity/lsp/RenameSymbol.cpp
Labels: external contribution :star:
