Repository argotorg/solidity, pull requests merged in 2025-06, with the labels that each got.

#16062 Replace Reference StandardCompiler.cpp
  test/libsolidity/StandardCompiler.cpp
Labels: external contribution :star:, testing :hammer:

#16034 Fix typos in test file names and macro parameters
  test/libsolidity/util/TestFileParserTests.cpp
  test/tools/ossfuzz/protoToAbiV2.cpp
Labels: external contribution :star:, testing :hammer:

#16076 Fix typo in test filename: overriden -> overridden
  test/libsolidity/smtCheckerTests/inheritance/overridden_function_static_call_parent.sol
Labels: external contribution :star:, testing :hammer:

#16010 docs: remove consecutive duplicate words
  test/EVMHost.cpp
Labels: external contribution :star:

#15994 Support ethdebug source locations under EOF
  Changelog.md
  libevmasm/CMakeLists.txt
  libevmasm/Ethdebug.cpp
  libevmasm/Ethdebug.h
  libevmasm/EthdebugSchema.cpp
  libevmasm/EthdebugSchema.h
  libsolidity/interface/CompilerStack.cpp
  libyul/YulStack.cpp
  test/cmdlineTests/ethdebug_eof_container_osaka/args
  test/cmdlineTests/ethdebug_eof_container_osaka/err
  test/cmdlineTests/ethdebug_eof_container_osaka/exit
  test/cmdlineTests/ethdebug_eof_container_osaka/output
  test/cmdlineTests/ethdebug_on_abstract/args
  test/cmdlineTests/ethdebug_on_abstract/input.sol
  test/cmdlineTests/ethdebug_on_abstract/output
  test/cmdlineTests/ethdebug_on_interface/args
  test/cmdlineTests/ethdebug_on_interface/input.sol
  test/cmdlineTests/ethdebug_on_interface/output
  test/cmdlineTests/standard_output_debuginfo_ethdebug_with_interfaces_and_abstracts/input.json
  test/cmdlineTests/standard_output_debuginfo_ethdebug_with_interfaces_and_abstracts/output.json
  test/cmdlineTests/standard_yul_debug_info_ethdebug_compatible_output_eof/args
  test/cmdlineTests/standard_yul_debug_info_ethdebug_compatible_output_eof/in.yul
  test/cmdlineTests/standard_yul_debug_info_ethdebug_compatible_output_eof/input.json
  test/cmdlineTests/standard_yul_debug_info_ethdebug_compatible_output_eof/output.json
  test/cmdlineTests/standard_yul_debug_info_ethdebug_compatible_output_eof/strip-ethdebug
  test/cmdlineTests/standard_yul_ethdebug_eof/args
  test/cmdlineTests/standard_yul_ethdebug_eof/in.yul
  test/cmdlineTests/standard_yul_ethdebug_eof/input.json
  test/cmdlineTests/standard_yul_ethdebug_eof/output.json
  test/cmdlineTests/standard_yul_ethdebug_eof/strip-ethdebug
  test/libevmasm/Assembler.cpp
  test/libsolidity/StandardCompiler.cpp
Labels: ethdebug

#16060 Pass `count` into `re.sub()` as a named argument in `isolate_tests.py` to fix the deprecation warning
  scripts/wasm-rebuild/docker-scripts/isolate_tests.py
Labels: external contribution :star:
