Repository argotorg/solidity, pull requests merged in 2025-07, with the labels that each got.

#16103 Replace string comparisons with empty() method
  libsolidity/parsing/DocStringParser.cpp
  libsolidity/parsing/Parser.cpp
Labels: external contribution :star:, refactor

#15961 Better safeguard against incompatible builtin handles between dialects
  liblangutil/EVMVersion.h
  libyul/CMakeLists.txt
  libyul/backends/evm/EVMBuiltins.cpp
  libyul/backends/evm/EVMBuiltins.h
  libyul/backends/evm/EVMDialect.cpp
  libyul/backends/evm/EVMDialect.h
  libyul/backends/evm/NoOutputAssembly.cpp
  libyul/backends/evm/NoOutputAssembly.h
  solc/CommandLineParser.cpp
  test/CMakeLists.txt
  test/libyul/EVMDialectCompatibility.cpp
  test/tools/fuzzer_common.cpp
Labels: refactor

#16130 Update solidity public calls url from ethereum.org to solidity.org
  docs/contributing.rst
Labels: documentation :book:
