Repository argotorg/solidity, pull requests merged in 2025-04, with the labels that each got.

#15972 SMTChecker: Refactor processing invariants from the solver
  libsmtutil/CHCSmtLib2Interface.cpp
  libsmtutil/CHCSmtLib2Interface.h
  libsmtutil/CHCSolverInterface.h
  libsolidity/CMakeLists.txt
  libsolidity/formal/CHC.cpp
  libsolidity/formal/Invariants.cpp
  libsolidity/formal/Invariants.h
  libsolidity/formal/Predicate.cpp
  libsolidity/formal/Predicate.h
  libsolidity/formal/Z3CHCSmtLib2Interface.cpp
Labels: refactor, smt, :yellow_circle:

#15976 Add support for upcoming Boost 1.88.0
  libsolidity/formal/ModelChecker.cpp
  libsolidity/interface/SMTSolverCommand.cpp
  test/libyul/ControlFlowGraphTest.cpp
  test/libyul/SSAControlFlowGraphTest.cpp
  test/libyul/StackLayoutGeneratorTest.cpp
Labels: external contribution :star:

#16004 chore: remove redundant word in comment
  libsolidity/codegen/YulUtilFunctions.h
Labels: external contribution :star:

#15980 Language Server: Fix hover crashes on invalid parameters
  libsolidity/lsp/DocumentHoverHandler.cpp
Labels: external contribution :star:

#15966 Polishing up any minor spelling errors
  test/compilationTests/corion/premium.sol
  test/compilationTests/corion/publisher.sol
Labels: external contribution :star:

#15891 Fix font name from 'Overpass mono' to 'Overpass Mono
  docs/_static/css/custom.css
Labels: external contribution :star:

#15924 Fix grammar issues in events documentation
  docs/contracts/events.rst
Labels: external contribution :star:

#15897 Update calling_nonexisting_contract.sol
  test/libsolidity/semanticTests/functionCall/eof/calling_nonexisting_contract.sol
Labels: external contribution :star:

#15827 docs: Fix grammar in workflow trigger condition
  scripts/docker/buildpack-deps/README.md
Labels: external contribution :star:

#15904 Replace temporary std::string with std::string_view in _yulname literal
  libyul/YulString.h
Labels: external contribution :star:

#15885 Grammar & Clarity Fixes (Reopened)
  test/externalTests/brink.sh
  test/externalTests/elementfi.sh
Labels: documentation :book:, external contribution :star:

#15940 Fix opening comment marker in license header of some files
  libyul/CompilabilityChecker.cpp
  libyul/optimiser/CommonSubexpressionEliminator.cpp
  libyul/optimiser/DataFlowAnalyzer.cpp
  libyul/optimiser/Metrics.cpp
  libyul/optimiser/Rematerialiser.cpp
  libyul/optimiser/StackCompressor.cpp
  libyul/optimiser/SyntacticalEquality.cpp
  libyul/optimiser/UnusedPruner.cpp
Labels: documentation :book:, external contribution :star:

#15862 SMTChecker: Loop conditions should be analyzed as in loop context in BMC
  Changelog.md
  libsolidity/formal/BMC.cpp
  libsolidity/formal/BMC.h
  test/libsolidity/smtCheckerTests/loops/for_loop_condition_constant_true_in_first_iteration_and_constant_false_in_second.sol
  test/libsolidity/smtCheckerTests/loops/while_loop_condition_constant_true_in_first_iteration_and_constant_false_in_second.sol
Labels: smt, :yellow_circle:

#16019 SMTChecker: Clean up includes and remove unused functionality
  libsmtutil/SMTLib2Interface.cpp
  libsmtutil/SMTPortfolio.h
  libsmtutil/SolverInterface.h
  libsolidity/CMakeLists.txt
  libsolidity/formal/ArraySlicePredicate.cpp
  libsolidity/formal/ArraySlicePredicate.h
  libsolidity/formal/BMC.cpp
  libsolidity/formal/EncodingContext.cpp
  libsolidity/formal/EncodingContext.h
  libsolidity/formal/ExpressionFormatter.cpp
  libsolidity/formal/Predicate.cpp
  libsolidity/formal/Predicate.h
  libsolidity/formal/SMTEncoder.cpp
  libsolidity/formal/SMTEncoder.h
  libsolidity/formal/SymbolicTypes.cpp
  libsolidity/formal/SymbolicTypes.h
  libsolidity/formal/SymbolicVariables.cpp
  libsolidity/formal/VariableUsage.cpp
  libsolidity/formal/VariableUsage.h
Labels: refactor, smt, :yellow_circle:

#15473 docs: fixed a mismatch in the name of the function referenced in the micropayment example
  docs/examples/micropayment.rst
Labels: documentation :book:, external contribution :star:

#16012 evmasm test case
  libevmasm/EVMAssemblyStack.cpp
  libevmasm/EVMAssemblyStack.h
  libevmasm/Instruction.cpp
  libevmasm/Instruction.h
  test/CMakeLists.txt
  test/InteractiveTests.h
  test/TestCase.cpp
  test/TestCaseReader.h
  test/libevmasm/EVMAssemblyTest.cpp
  test/libevmasm/EVMAssemblyTest.h
  test/libevmasm/PlainAssemblyParser.cpp
  test/libevmasm/PlainAssemblyParser.h
  test/libevmasm/evmAssemblyTests/isoltestTesting/code_generation_error.asmjson
  test/libevmasm/evmAssemblyTests/isoltestTesting/comments.asm
  test/libevmasm/evmAssemblyTests/isoltestTesting/invalid_json.asmjson
  test/libevmasm/evmAssemblyTests/isoltestTesting/jumps.asm
  test/libevmasm/evmAssemblyTests/isoltestTesting/operations.asm
  test/libevmasm/evmAssemblyTests/isoltestTesting/push.asm
  test/libevmasm/evmAssemblyTests/isoltestTesting/settings_eof_version.asmjson
  test/libevmasm/evmAssemblyTests/isoltestTesting/settings_evm_version.asmjson
  test/libevmasm/evmAssemblyTests/isoltestTesting/settings_optimizer_constant_optimizer.asmjson
  test/libevmasm/evmAssemblyTests/isoltestTesting/settings_optimizer_cse.asmjson
  test/libevmasm/evmAssemblyTests/isoltestTesting/settings_optimizer_deduplicate.asmjson
  test/libevmasm/evmAssemblyTests/isoltestTesting/settings_optimizer_expected_executions_per_deployment.asmjson
  test/libevmasm/evmAssemblyTests/isoltestTesting/settings_optimizer_inliner.asmjson
  test/libevmasm/evmAssemblyTests/isoltestTesting/settings_optimizer_jumpdest_remover.asmjson
  test/libevmasm/evmAssemblyTests/isoltestTesting/settings_optimizer_peephole.asmjson
  test/libevmasm/evmAssemblyTests/isoltestTesting/settings_optimizer_preset.asmjson
  test/libevmasm/evmAssemblyTests/isoltestTesting/settings_outputs.asmjson
  test/libevmasm/evmAssemblyTests/isoltestTesting/smoke.asmjson
  test/libevmasm/evmAssemblyTests/isoltestTesting/smoke_plain.asm
  test/tools/CMakeLists.txt
  test/tools/isoltest.cpp
Labels: testing :hammer:

#15991 eof: Enable peephole optimizer for EOF.
  libevmasm/Assembly.cpp
  libevmasm/AssemblyItem.h
  libevmasm/PeepholeOptimiser.cpp
  test/Common.cpp
  test/Common.h
  test/libevmasm/Optimiser.cpp
  test/libyul/objectCompiler/eof/256_subcontainers.yul
Labels: external contribution :star:, optimizer, EOF

#16025 SMTChecker: Fix typo in SMTPortfolio.cpp
  libsmtutil/SMTPortfolio.cpp
Labels: external contribution :star:
