Repository argotorg/solidity, pull requests merged in 2025-02, with the labels that each got.

#15806 SMTChecker: Remove code left over after switch to SMT-LIB interface
  libsolidity/formal/BMC.cpp
  scripts/error_codes.py
Labels: smt

#15814 Fix typo in libsolidity/ast/AST.h
  libsolidity/ast/AST.h
Labels: external contribution :star:

#15812 tests: fix a typo in a yulphaser test case name
  test/yulPhaser/TestHelpersTest.cpp
Labels: external contribution :star:, testing :hammer:

#15816 Missing EVM restrictions and EOF compatibility in tests
  test/libsolidity/semanticTests/isoltestTesting/precompiles_ignoring_trailing_input.sol
  test/libyul/yulSyntaxTests/invalid/builtin_name_as_type.yul
  test/libyul/yulSyntaxTests/invalid/clash_with_reserved_pure_yul_builtin.yul
  test/libyul/yulSyntaxTests/invalid/clash_with_reserved_pure_yul_builtin_eof.yul
Labels: testing :hammer:, EOF

#15818 eof: Pass proper EOF flag to `Assembly` used by `EVMCodeTransformTest`
  test/libyul/EVMCodeTransformTest.cpp
  test/libyul/evmCodeTransform/stackReuse/eof/function_argument_reuse_without_retparams.yul
  test/libyul/evmCodeTransform/stackReuse/function_argument_reuse_without_retparams.yul
Labels: external contribution :star:, testing :hammer:, EOF

#15810 SMTChecker: Fix parsing bv2int expression from solver's response
  libsmtutil/CHCSmtLib2Interface.cpp
  test/libsolidity/smtCheckerTests/invariants/solver_response_involves_bv2int.sol
Labels: smt, :yellow_circle:

#15666 eof: Enable compilation to EOF for all `EVMVersionRestrictedTestCase` tests by default
  test/TestCase.cpp
  test/libsolidity/SemanticTest.cpp
  test/libsolidity/SyntaxTest.cpp
Labels: external contribution :star:, EOF

#15820 SMTChecker: Fix crash on external function call wrapped in 1-tuple
  Changelog.md
  libsolidity/formal/CHC.cpp
  libsolidity/formal/SMTEncoder.cpp
  test/libsolidity/smtCheckerTests/external_calls/external_call_extra_parentheses_1.sol
  test/libsolidity/smtCheckerTests/external_calls/external_call_extra_parentheses_2.sol
Labels: smt, :yellow_circle:

#15821 String view compatibility for joinHumanReadable and isYulKeyword
  liblangutil/Token.cpp
  liblangutil/Token.h
  libsolutil/StringUtils.h
Labels: refactor, :yellow_circle:

#15826 SMTChecker: Fix internal error involving string to bytes conversion
  Changelog.md
  libsolidity/formal/CHC.cpp
  test/libsolidity/smtCheckerTests/typecast/string_literal_to_fixed_bytes_constructor_for_deployment.sol
Labels: smt, :yellow_circle:

#15850 Yul optimizer utilities use string_view to determine if an identifier is restricted
  libyul/optimiser/NameDispenser.cpp
  libyul/optimiser/OptimizerUtilities.cpp
  libyul/optimiser/OptimizerUtilities.h
  libyul/optimiser/VarNameCleaner.cpp
Labels: refactor

#15853 SMTChecker: Fix reporting same target both as safe and unsafe
  Changelog.md
  libsolidity/formal/CHC.cpp
  test/libsolidity/smtCheckerTests/functions/free_function_multiple_contracts.sol
  test/libsolidity/smtCheckerTests/functions/internal_call_with_assertion_inheritance_1_fail.sol
  test/libsolidity/smtCheckerTests/functions/library_constant.sol
  test/libsolidity/smtCheckerTests/imports/import_library_2.sol
  test/libsolidity/smtCheckerTests/inheritance/base_contract_assertion_fail_1.sol
  test/libsolidity/smtCheckerTests/inheritance/base_contract_assertion_fail_2.sol
  test/libsolidity/smtCheckerTests/inheritance/base_contract_assertion_fail_3.sol
  test/libsolidity/smtCheckerTests/inheritance/base_contract_assertion_fail_4.sol
  test/libsolidity/smtCheckerTests/inheritance/base_contract_assertion_fail_5.sol
  test/libsolidity/smtCheckerTests/inheritance/base_contract_assertion_fail_7.sol
  test/libsolidity/smtCheckerTests/inheritance/base_contract_assertion_fail_9.sol
  test/libsolidity/smtCheckerTests/inheritance/constructor_state_variable_init_diamond_middle.sol
  test/libsolidity/smtCheckerTests/modifiers/modifier_overriding_4.sol
  test/libsolidity/smtCheckerTests/modifiers/modifier_two_invocations_2.sol
  test/libsolidity/smtCheckerTests/operators/assignment_chain_tuple_contract_3.sol
  test/libsolidity/smtCheckerTests/special/msg_value_inheritance_2.sol
  test/libsolidity/smtCheckerTests/special/msg_value_inheritance_3.sol
Labels: smt, :yellow_circle:

#15856 Testing: Fix unused variable warning in SMTCheckerTests on other platforms than Windows/Linux/Macos
  test/libsolidity/SMTCheckerTest.cpp
Labels: testing :hammer:, smt

#15834 Allows to run the asm optimizer on imported asm
  Changelog.md
  docs/using-the-compiler.rst
  libevmasm/Assembly.cpp
  libevmasm/Assembly.h
  libevmasm/EVMAssemblyStack.cpp
  libevmasm/EVMAssemblyStack.h
  libsolidity/codegen/CompilerContext.h
  libsolidity/interface/StandardCompiler.cpp
  libsolidity/interface/StandardCompiler.h
  libyul/YulStack.cpp
  solc/CommandLineInterface.cpp
  solc/CommandLineParser.cpp
  test/cmdlineTests/import_asm_json_no_optimize/args
  test/cmdlineTests/import_asm_json_no_optimize/output
  test/cmdlineTests/import_asm_json_no_optimize/stdin
  test/cmdlineTests/import_asm_json_optimize/args
  test/cmdlineTests/import_asm_json_optimize/exit
  test/cmdlineTests/import_asm_json_optimize/output
  test/cmdlineTests/import_asm_json_optimize/stdin
  test/cmdlineTests/import_asm_json_optimize_not_supported/args
  test/cmdlineTests/import_asm_json_optimize_not_supported/err
  test/cmdlineTests/import_asm_json_optimize_not_supported/exit
  test/cmdlineTests/import_asm_json_optimize_not_supported/stdin
  test/cmdlineTests/import_asm_json_standard_json_no_optimize/input.json
  test/cmdlineTests/import_asm_json_standard_json_no_optimize/output.json
  test/cmdlineTests/import_asm_json_standard_json_optimize/input.json
  test/cmdlineTests/import_asm_json_standard_json_optimize/output.json
  test/libevmasm/Optimiser.cpp
Labels: optimizer

#15858 fix: typos in a few syntax test file names
  test/libsolidity/syntaxTests/inheritance/override/public_var_parallel_function.sol
  test/libsolidity/syntaxTests/parsing/invalid_variable_mutability.sol
  test/libsolidity/syntaxTests/userDefinedValueType/recursive_function_parameter_err.sol
Labels: external contribution :star:, testing :hammer:

#15824 eof: Add EOF initial support changelog entry.
  Changelog.md
  docs/using-the-compiler.rst
Labels: documentation :book:, external contribution :star:, EOF

#15864 fix: typos in a few syntax and natspec test file names
  test/libsolidity/natspecJSON/dev_multiline_param_description.sol
  test/libsolidity/syntaxTests/types/mapping/abstract_constructor_param.sol
  test/libsolidity/syntaxTests/types/mapping/mapping_struct_recursive_data_location_memory.sol
Labels: external contribution :star:, testing :hammer:

#15866 Fix spelling errors in a few code comments in libsolidity and SMTChecker
  libsolidity/codegen/CompilerContext.h
  libsolidity/formal/BMC.cpp
  libsolidity/formal/SMTEncoder.h
Labels: documentation :book:, external contribution :star:

#15869 Grammar and typo fixes in code comments
  libyul/optimiser/SSATransform.h
  scripts/docker/buildpack-deps/emscripten.jam
Labels: documentation :book:, external contribution :star:

#15867 fix: typos in a few test file names
  test/libsolidity/syntaxTests/constructor/constructor_internal_function_abstract.sol
  test/libsolidity/syntaxTests/controlFlow/modifiers/non_implemented_modifier.sol
  test/libyul/yulOptimizerTests/disambiguator/function_call.yul
Labels: external contribution :star:, testing :hammer:

#15868 Updating copyright year to 2025 in docs configuration
  docs/conf.py
Labels: documentation :book:, external contribution :star:

#15809 SMTChecker: Allow printing queries without requiring `smtlib2` as the chosen solver
  Changelog.md
  libsolidity/formal/BMC.cpp
  libsolidity/formal/CHC.cpp
  libsolidity/interface/StandardCompiler.cpp
  solc/CommandLineParser.cpp
  test/cmdlineTests/model_checker_print_query_all/err
  test/cmdlineTests/model_checker_print_query_bmc/err
  test/cmdlineTests/model_checker_print_query_chc/err
  test/cmdlineTests/model_checker_print_query_no_smtlib2_solver_bmc/args
  test/cmdlineTests/model_checker_print_query_no_smtlib2_solver_bmc/err
  test/cmdlineTests/model_checker_print_query_no_smtlib2_solver_bmc/exit
  test/cmdlineTests/model_checker_print_query_no_smtlib2_solver_bmc/input.sol
  test/cmdlineTests/model_checker_print_query_no_smtlib2_solver_chc/args
  test/cmdlineTests/model_checker_print_query_no_smtlib2_solver_chc/err
  test/cmdlineTests/model_checker_print_query_no_smtlib2_solver_chc/exit
  test/cmdlineTests/model_checker_print_query_no_smtlib2_solver_chc/input.sol
  test/cmdlineTests/model_checker_print_query_superflous_solver/args
  test/cmdlineTests/model_checker_print_query_superflous_solver/err
  test/cmdlineTests/model_checker_print_query_superflous_solver/exit
  test/cmdlineTests/model_checker_print_query_superflous_solver/input.sol
  test/cmdlineTests/standard_model_checker_print_query_all/output.json
  test/cmdlineTests/standard_model_checker_print_query_bmc/output.json
  test/cmdlineTests/standard_model_checker_print_query_chc/output.json
  test/cmdlineTests/standard_model_checker_print_query_no_smtlib2_solver/input.json
  test/cmdlineTests/standard_model_checker_print_query_no_smtlib2_solver/output.json
  test/cmdlineTests/standard_model_checker_print_query_superflous_solver/input.json
  test/cmdlineTests/standard_model_checker_print_query_superflous_solver/output.json
Labels: smt, :yellow_circle:

#15845 eof: Add support for SWAPN/DUPN
  libevmasm/Assembly.cpp
  libevmasm/Assembly.h
  libevmasm/AssemblyItem.cpp
  libevmasm/AssemblyItem.h
  libevmasm/Instruction.cpp
  libevmasm/Instruction.h
  libevmasm/KnownState.cpp
  libevmasm/PeepholeOptimiser.cpp
  libevmasm/SemanticInformation.cpp
  libevmasm/SemanticInformation.h
  liblangutil/EVMVersion.cpp
  libyul/AsmAnalysis.cpp
  libyul/backends/evm/AbstractAssembly.h
  libyul/backends/evm/EVMDialect.cpp
  libyul/backends/evm/EthAssemblyAdapter.cpp
  libyul/backends/evm/EthAssemblyAdapter.h
  libyul/backends/evm/NoOutputAssembly.cpp
  libyul/backends/evm/NoOutputAssembly.h
  test/libyul/yulSyntaxTests/eof/eof_identifiers_not_defined_in_legacy.yul
  test/libyul/yulSyntaxTests/eof/eof_identifiers_not_reserved_in_legacy.yul
  test/libyul/yulSyntaxTests/eof/eof_opcodes_identifiers_reserved_in_eof.yul
  test/tools/yulInterpreter/EVMInstructionInterpreter.cpp
Labels: EOF

#15804 Tweaks in docker usage docs
  docs/installing-solidity.rst
Labels: documentation :book:

#15859 Fix custom cleanup sequence missing from metadata when other optimizer settings have default values
  Changelog.md
  libsolidity/interface/OptimiserSettings.h
  test/libsolidity/Metadata.cpp
Labels: optimizer

#15842 Optimize collection of references in dataflow analyzer clearValues
  libsolutil/CommonData.h
  libyul/optimiser/DataFlowAnalyzer.cpp
  libyul/optimiser/DataFlowAnalyzer.h
  libyul/optimiser/Rematerialiser.cpp
Labels: performance :racehorse:, optimizer

#15844 eof: Make use of EOF's SWAPN/DUPN
  libevmasm/GasMeter.cpp
  libevmasm/GasMeter.h
  libyul/backends/evm/EVMDialect.h
  libyul/backends/evm/OptimizedEVMCodeTransform.cpp
  libyul/backends/evm/OptimizedEVMCodeTransform.h
  libyul/backends/evm/StackHelpers.h
  libyul/backends/evm/StackLayoutGenerator.cpp
  libyul/backends/evm/StackLayoutGenerator.h
  libyul/optimiser/StackCompressor.cpp
  libyul/optimiser/StackLimitEvader.cpp
  libyul/optimiser/Suite.cpp
  test/libyul/StackLayoutGeneratorTest.cpp
  test/libyul/StackShufflingTest.cpp
  test/libyul/StackShufflingTest.h
  test/libyul/evmCodeTransform/eof_dup256.yul
  test/libyul/evmCodeTransform/eof_swap17.yul
  test/libyul/evmCodeTransform/eof_swap256.yul
  test/libyul/yulOptimizerTests/fakeStackLimitEvader/connected.yul
  test/libyul/yulOptimizerTests/fakeStackLimitEvader/function_arg.yul
  test/libyul/yulOptimizerTests/fakeStackLimitEvader/multi_variable_declaration_without_value.yul
  test/libyul/yulOptimizerTests/fakeStackLimitEvader/outer_block.yul
  test/libyul/yulOptimizerTests/fakeStackLimitEvader/return_leave.yul
  test/libyul/yulOptimizerTests/fakeStackLimitEvader/return_one.yul
  test/libyul/yulOptimizerTests/fakeStackLimitEvader/return_one_with_args.yul
  test/libyul/yulOptimizerTests/fakeStackLimitEvader/same_variable_in_lhs_and_rhs.yul
  test/libyul/yulOptimizerTests/fakeStackLimitEvader/stub.yul
  test/libyul/yulOptimizerTests/stackCompressor/noInline.yul
  test/libyul/yulOptimizerTests/stackLimitEvader/cycle.yul
  test/libyul/yulOptimizerTests/stackLimitEvader/cycle_after.yul
  test/libyul/yulOptimizerTests/stackLimitEvader/cycle_after_2.yul
  test/libyul/yulOptimizerTests/stackLimitEvader/cycle_before.yul
  test/libyul/yulOptimizerTests/stackLimitEvader/cycle_before_2.yul
  test/libyul/yulOptimizerTests/stackLimitEvader/cycle_before_after.yul
  test/libyul/yulOptimizerTests/stackLimitEvader/function_arg.yul
  test/libyul/yulOptimizerTests/stackLimitEvader/stub.yul
  test/libyul/yulOptimizerTests/stackLimitEvader/too_many_args_14.yul
  test/libyul/yulOptimizerTests/stackLimitEvader/too_many_args_15.yul
  test/libyul/yulOptimizerTests/stackLimitEvader/too_many_args_16.yul
  test/libyul/yulOptimizerTests/stackLimitEvader/too_many_returns_15.yul
  test/libyul/yulOptimizerTests/stackLimitEvader/too_many_returns_16.yul
  test/libyul/yulOptimizerTests/stackLimitEvader/tree.yul
  test/libyul/yulOptimizerTests/stackLimitEvader/verbatim_many_arguments.yul
  test/libyul/yulOptimizerTests/stackLimitEvader/verbatim_many_arguments_and_returns.yul
  test/libyul/yulOptimizerTests/stackLimitEvader/verbatim_many_returns.yul
  test/libyul/yulStackShuffling/pop_early_to_avoid_swap17.stack
  test/libyul/yulStackShuffling/swap17.stack
  test/libyul/yulStackShuffling/swap_cycle.stack
Labels: EOF
