Repository argotorg/solidity, pull requests merged in 2025-08, with the labels that each got.

#16132 docs: fix unnecessary `uint160(bytes20(b))` casting
  docs/types/value-types.rst
Labels: documentation :book:, external contribution :star:

#16046 docs: fix typos in comments across multiple files (`assignmed`, `captital`, `runds`)
  libyul/backends/evm/StackLayoutGenerator.cpp
  test/compilationTests/corion/provider.sol
  test/compilationTests/corion/schelling.sol
Labels: documentation :book:, external contribution :star:

#16147 [SMTChecker] Fix comparison of `CHCVerificationTarget` for proper `std::set` ordering
  libsolidity/formal/CHC.h
Labels: external contribution :star:, smt

#16164 refactor(formal): remove unused `clear()`/`solver()` from `EncodingContext`
  libsolidity/formal/EncodingContext.h
Labels: external contribution :star:, refactor, smt

#16163 Remove the hard dependency on `boost::system` compatibility library to fix builds with Boost 1.89.0
  cmake/EthDependencies.cmake
  libsolutil/CMakeLists.txt
  test/tools/CMakeLists.txt
Labels: build system :building_construction:, external contribution :star:

#16176 update to boost 1.70.0 for non-windows builds
  Changelog.md
  cmake/EthDependencies.cmake
  docs/installing-solidity.rst
Labels: build system :building_construction:
