Repository argotorg/solidity, pull requests merged in 2025-03, with the labels that each got.

#15807 More info about unreported fatal errors
  liblangutil/ErrorReporter.cpp
  libsolidity/analysis/NameAndTypeResolver.cpp
  libsolidity/analysis/TypeChecker.cpp
  libsolidity/interface/CompilerStack.cpp
  libsolidity/parsing/Parser.cpp
  libyul/AsmAnalysis.cpp
  libyul/AsmParser.cpp
  libyul/ObjectParser.cpp
Labels: refactor

#15906 Get rid of `assertThrow()` in soltest
  test/Common.cpp
  test/EVMHost.cpp
  test/Metadata.cpp
  test/tools/IsolTestOptions.cpp
Labels: testing :hammer:

#15905 Validations against using EOF on pre-Osaka EVMs
  libsolidity/interface/StandardCompiler.cpp
  solc/CommandLineParser.cpp
  test/Common.cpp
  test/EVMHost.cpp
  test/cmdlineTests/eof_unavailable_before_osaka/args
  test/cmdlineTests/eof_unavailable_before_osaka/err
  test/cmdlineTests/eof_unavailable_before_osaka/exit
  test/cmdlineTests/eof_unavailable_before_osaka/input.sol
  test/cmdlineTests/import_asm_json_eof_unavailable_before_osaka/args
  test/cmdlineTests/import_asm_json_eof_unavailable_before_osaka/err
  test/cmdlineTests/import_asm_json_eof_unavailable_before_osaka/exit
  test/cmdlineTests/import_asm_json_eof_unavailable_before_osaka/stdin
  test/cmdlineTests/standard_eof_unavailable_before_osaka/input.json
  test/cmdlineTests/standard_eof_unavailable_before_osaka/output.json
  test/cmdlineTests/standard_import_asm_json_eof_unavailable_before_osaka/input.json
  test/cmdlineTests/standard_import_asm_json_eof_unavailable_before_osaka/output.json
  test/cmdlineTests/standard_yul_eof_unavailable_before_osaka/input.json
  test/cmdlineTests/standard_yul_eof_unavailable_before_osaka/output.json
  test/cmdlineTests/strict_asm_eof_unavailable_before_osaka/args
  test/cmdlineTests/strict_asm_eof_unavailable_before_osaka/err
  test/cmdlineTests/strict_asm_eof_unavailable_before_osaka/exit
  test/cmdlineTests/strict_asm_eof_unavailable_before_osaka/input.yul
Labels: EOF

#15909 Fix reversed conditions in `ObjectOptimizer::calculateCacheKey()`
  Changelog.md
  libyul/ObjectOptimizer.cpp
Labels: performance :racehorse:, optimizer

#15907 Error and ICE reporting tweaks
  Changelog.md
  liblangutil/SourceReferenceFormatter.cpp
  libsolidity/interface/CompilerStack.cpp
  libsolidity/interface/StandardCompiler.cpp
  libyul/AsmAnalysis.cpp
  libyul/Exceptions.h
  solc/CommandLineInterface.cpp
  solc/main.cpp
  test/CommonSyntaxTest.cpp
  test/cmdlineTests/stack_too_deep_from_code_transform/args
  test/cmdlineTests/stack_too_deep_from_code_transform/err
  test/cmdlineTests/stack_too_deep_from_code_transform/exit
  test/cmdlineTests/stack_too_deep_from_code_transform/input.sol
  test/cmdlineTests/standard_empty_file_name/output.json
  test/cmdlineTests/standard_stack_too_deep_from_code_transform/in.sol
  test/cmdlineTests/standard_stack_too_deep_from_code_transform/input.json
  test/cmdlineTests/standard_stack_too_deep_from_code_transform/output.json
Labels: testing :hammer:, refactor

#15822 fix errors in comments
  libsolc/libsolc.cpp
  libsolidity/analysis/ControlFlowBuilder.h
  libsolidity/interface/ABI.h
Labels: documentation :book:, external contribution :star:

#15910 Document Node.js required version change for Solc-Js.
  Changelog.md
Labels: documentation :book:, solcjs, has dependencies

#15840 Yul FunctionCallFinder uses FunctionName instead of strings as search key
  libyul/backends/evm/EVMObjectCompiler.cpp
  libyul/optimiser/FullInliner.cpp
  libyul/optimiser/FunctionCallFinder.cpp
  libyul/optimiser/FunctionCallFinder.h
  libyul/optimiser/StackLimitEvader.cpp
  test/cmdlineTests/memoryguard_shadowing_by_inline_assembly_identifiers/args
  test/cmdlineTests/memoryguard_shadowing_by_inline_assembly_identifiers/input.sol
  test/cmdlineTests/memoryguard_shadowing_by_inline_assembly_identifiers/output
  test/libsolidity/MemoryGuardTest.cpp
  test/libsolidity/memoryGuardTests/shadowing_memoryguard_with_inline_assembly_identifiers.sol
Labels: optimizer

#15892 Storage layout specifier docs
  docs/contracts.rst
  docs/contracts/custom-storage-layout.rst
  docs/internals/layout_in_storage.rst
Labels: documentation :book:

#15928 Document the EOF version setting in Standard JSON and metadata
  docs/metadata.rst
  docs/using-the-compiler.rst
Labels: documentation :book:

#15898 Fix spelling and improve solc version parsing in base.py
  scripts/externalTests/runners/base.py
Labels: external contribution :star:

#15939 Remove double backticks and indented bullet points from Markdown files
  CODING_STYLE.md
  ReleaseChecklist.md
Labels: documentation :book:

#15942 Name dependent CSE bug: Compare ASM only
  test/cmdlineTests/~name_dependent_cse_bug/test.sh
Labels: testing :hammer:

#15950 SSACFG Builder: Improve function call visitor
  libyul/backends/evm/SSAControlFlowGraphBuilder.cpp
Labels: refactor, :yellow_circle:

#15880 SMTChecker: Fix analysis for selected contracts
  Changelog.md
  libsolidity/formal/BMC.cpp
  libsolidity/formal/CHC.cpp
  libsolidity/formal/ModelCheckerSettings.cpp
  libsolidity/formal/SMTEncoder.cpp
  libsolidity/formal/SMTEncoder.h
  test/cmdlineTests/model_checker_contracts_inexistent_contract/err
  test/cmdlineTests/model_checker_contracts_only_one/err
  test/cmdlineTests/standard_model_checker_contracts_inexistent_contract/output.json
  test/cmdlineTests/standard_model_checker_contracts_multi_source/output.json
  test/cmdlineTests/standard_model_checker_contracts_only_one/output.json
  test/libsolidity/SMTCheckerTest.cpp
  test/libsolidity/smtCheckerTests/external_calls/external_call_from_constructor_1_trusted.sol
  test/libsolidity/smtCheckerTests/external_calls/external_call_from_constructor_3_trusted.sol
  test/libsolidity/smtCheckerTests/imports/target_in_imported_contract_analyzed_when_called_from_selection_with_trusted_calls.sol
  test/libsolidity/smtCheckerTests/imports/target_in_imported_contract_not_analyzed_when_not_selected_and_not_called_from_selection.sol
  test/libsolidity/smtCheckerTests/verification_target/target_in_constructor_of_same_source_contract_not_analyzed_when_not_selected_and_not_called_from_selection.sol
  test/libsolidity/smtCheckerTests/verification_target/target_in_same_source_contract_not_analyzed_when_not_selected_and_not_called_from_selection.sol
Labels: smt, :yellow_circle:

#15951 Yul Disambiguator: Don't check for builtins when translating identifiers
  libyul/optimiser/Disambiguator.cpp
  libyul/optimiser/Disambiguator.h
Labels: optimizer

#15952 IRGeneratorForStatements: Remove outdated check against usr$ prefixing of builtins
  libsolidity/codegen/ir/IRGeneratorForStatements.cpp
  libsolidity/experimental/codegen/IRGeneratorForStatements.cpp
Labels: refactor

#15963 SMTChecker: Fix string literal to fixed bytes conversion with user-defined type
  Changelog.md
  libsolidity/formal/SMTEncoder.cpp
  test/libsolidity/smtCheckerTests/userTypes/user_type_over_fixed_bytes_can_be_initialized_from_string_literal.sol
Labels: smt, :yellow_circle:

#15895 Update metadata docs for "libraries" and "compilationSettings" fields
  docs/metadata.rst
  docs/using-the-compiler.rst
Labels: documentation :book:, external contribution :star:

#15941 AsmAnalysis: Stronger use of fmt, refactor function call analysis
  libyul/AsmAnalysis.cpp
  libyul/AsmAnalysis.h
  test/libyul/yulSyntaxTests/eof/eofcreate_invalid_object_name_data.yul
Labels: refactor

#15954 ossfuzz and Yul interpreter use ast over block
  test/libyul/YulInterpreterTest.cpp
  test/tools/ossfuzz/strictasm_diff_ossfuzz.cpp
  test/tools/ossfuzz/yulFuzzerCommon.cpp
  test/tools/ossfuzz/yulFuzzerCommon.h
  test/tools/ossfuzz/yulProto_diff_ossfuzz.cpp
  test/tools/yulInterpreter/Inspector.cpp
  test/tools/yulInterpreter/Inspector.h
  test/tools/yulInterpreter/Interpreter.cpp
  test/tools/yulInterpreter/Interpreter.h
  test/tools/yulrun.cpp
Labels: testing :hammer:, refactor

#15967 fix: Remove unnecessary Expression temporary in CHCSmtLib2Interface
  libsmtutil/CHCSmtLib2Interface.cpp
Labels: external contribution :star:, refactor, smt
